### PR TITLE
[0.68] MustBeNoExceptVoidFunctor should depend on the template type parameter to avoid being evaluated too early

### PR DESCRIPTION
**Pull request by JunielKatarn**
Backport of #9562

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9609)

### CODE REVIEW

**Review by vmoroz — APPROVED** [review]
:shipit:

**Comment by asklar** [comment]
we shouldn't see this on older releases if we are using our own VS image (using vs2019), this should only repro with vs2022. Do you have a link to a failure on vs2019 @tido64 ?

**Comment by tido64** [comment]
You're right, it looks like `windows-latest` is now using VS2022: https://github.com/microsoft/react-native-test-app/runs/5344100326?check_suite_focus=true

I guess a workaround is to explicitly set `windows-2019`?

**Comment by asklar** [comment]
@tido64 yes, we don't "officially" support vs2022 yet since the project can't yet build with the default toolset that ships in 2022 (v143). One can work around it by installing the v142 toolset in vs2022 (in fact that's what I have on my laptop since 2022 is faster). We have workitems to move to v143 but it will take some time (and requires Office to be able to move too...).

Ideally, you should have CI run the currently-supported config, which is windows-2019.

**Pull request merged**
