### PR TITLE
Port windows fork of Pressable to win32

### PR DESCRIPTION
**Pull request by Saadnajmi**
### Type of Change
- New feature (non-breaking change which adds functionality)

### Why

Copy the windows port of Pressable to win32. This port adds extra desktop functionality like keyboard focus state and mouse hover state support. This is primarily so that FluentUI React Native can use Pressable downstream, and remove it's own copy of Pressability (https://github.com/microsoft/fluentui-react-native/issues/743). 

### What
What changes were made to the codebase to solve the bug, add the functionality, etc. that you specified above.

I simply wholesale copied `Pressable.windows.js` to `Pressable.win32.js`, along with the PressableExample page in rn-tester. I also added two lines to the test to test that onHoverIn/onHoverOut are indeed registered.

## Screenshots

Screenshot 2021-12-17 133056

## Testing

Added test pages for Pressable, which is also a copy of the windows one.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9132)

### CODE REVIEW

**Review by NickGerleman — APPROVED** [review]
Consistency between platforms is 👍

**Comment by NickGerleman** [comment]
Running "yarn lint:fix" should resolve CI errors. If you plan to do long term RNW dev, the eslint extension for VSCode is a must.

**Comment by PPatBoyd** [comment]
how will we stay consistent with changes?  Can we instead make a common file that's exported from the platform-specific files?

**Comment by Saadnajmi** [comment]
> how will we stay consistent with changes?  Can we instead make a common file that's exported from the platform-specific files?

I'm not sure how win32 and windows generally stay in sync, as a newcomer to this repo. Ideas:

If we don't need any platform specific types (like ViewWin32), then this file could just be
```
Import { Pressable } from 'react-native-windows' 
Export default Pressable
```

If we do need platform specific types, then I have the feeling that the maintainers generally  just keep two copies of the file (windows and win32).

**Comment by Saadnajmi** [comment]
> Running "yarn lint:fix" should resolve CI errors. If you plan to do long term RNW dev, the eslint extension for VSCode is a must. 

Thanks! I'll update with both of those things.
I also had issues actually running the test app, so I'll probably reach out for more specific questions on what should be overridden / how to run the test app properly when I come back to this change.

**Comment by Saadnajmi** [comment]
Issues I'm having with this Pull Request:

1) I'm not sure if the win32 port of Pressable should be a direct flow-types and all copy, or if I should change things to be more win32 specific. Examples include changing/removing the `// [Windows` comments, or switching the type `View -> ViewWin32`. If we wanted a typescript version of Pressable, I could probably directly copy our typescript port in FURN.

2) I can't get Pressable to show up in the RN-Tester-win32 list. I had to edit some seemingly autogenerated code to get it to show up on the list. And when I did, the mouse hover events were not working (sad). 

3) I also wasn't sure if the example test page should be `PressableExample.win32` or PressableExampleWin32`. Perhaps that has to do with Issue 2 as well.

I understand the windows team is out for the holidays, so I'll pick this up and figure out who to. bug to answer my questions when people are more available :D

**Comment by Saadnajmi** [comment]
Huzzah! Hover events :D 

image

**Comment by Saadnajmi** [comment]
New year, new ping! Would someone help me understand why the lint check is failing? The types it's complaining about definitely exist..

**Comment by acoates-ms** [comment]
Looks like its complaining about some of the Key events not being on view?  That type exists on the windows fork of CoreEventTypes, but not any win32 fork of that file.

**Comment by Saadnajmi** [comment]
> Looks like its complaining about some of the Key events not being on view? That type exists on the windows fork of CoreEventTypes, but not any win32 fork of that file.

Right, I did fork the CoreEvent types to win32 as well with my last commit (which includes `KeyEvent` but no dice.

Am I correct to assume that react-native-win32 doesn't also inherit overrides from react-native-windows, so any overrides from Core you want to do would need to be done twice?

**Comment by acoates-ms** [comment]
Yes, any overrides need to be done for win32 and windows separately.  Did you add the Key types to view.win32.js too?  Just adding the types to CoreEventTypes wouldn't do anything unless they were added to view.

**Comment by Saadnajmi** [comment]
> Yes, any overrides need to be done for win32 and windows separately. Did you add the Key types to view.win32.js too? Just adding the types to CoreEventTypes wouldn't do anything unless they were added to view.

Ah, that's probably it. Looking at it, I probably want to use `ViewWin32.tsx` not `view.win32.js` . The former already includes types for key events, and I'm not sure what the purpose of the latter is. Thanks, I'll try that!

**Comment by Saadnajmi** [comment]
> > Yes, any overrides need to be done for win32 and windows separately. Did you add the Key types to view.win32.js too? Just adding the types to CoreEventTypes wouldn't do anything unless they were added to view.
> 
> Ah, that's probably it. Looking at it, I probably want to use `ViewWin32.tsx` not `view.win32.js` . The former already includes types for key events, and I'm not sure what the purpose of the latter is. Thanks, I'll try that!
> 
> EDIT: Actually, I'll copy the overrides from `view.windows.js`, since this is all Flow. I'm still not quite sure what the difference between View vs ViewWindows/ViewWin32 is, but I'll assume it's just for typing. https://github.com/microsoft/react-native-windows/blob/main/vnext/src/Libraries/Components/View/View.windows.js

I added key types to View.win32.js, and also forked ViewPropTypes.win32.js, but I'm still seeing the same errors. I'm not sure why flow doesn't think the types exists. I think I've overridden everything properly..

**Comment by NickGerleman** [comment]
@Saadnajmi looking at the error, I think the Flow type checker might be using the non `.win32` variants of the files. In the `.flowconfig` file, there is a section where we tell the type-checker to ignore certain shared files, to force it to resolve the forked version. I think you may need to add the shared files you forked to that list.

**Comment by Saadnajmi** [comment]
> @Saadnajmi looking at the error, I think the Flow type checker might be using the non `.win32` variants of the files. In the `.flowconfig` file, there is a section where we tell the type-checker to ignore certain shared files, to force it to resolve the forked version. I think you may need to add the shared files you forked to that list.

Looks like that was it! Thank you =)

**Pull request merged**
