### PR TITLE
Use current version of Metro and Community CLI

### PR DESCRIPTION
**Pull request by NickGerleman**
This removes the resolution forcing an older version of Metro, now that the newest CLI version has been updated to fix compatibility with the current version of Metro.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9573)

### CODE REVIEW

**Comment by NickGerleman** [comment]
Looks like there was a hiccup, where the latest CLI version is pulling in a separate CLI package that doesn't include the fixes.

**Comment by acoates-ms** [comment]
Looks like https://github.com/react-native-community/cli/issues/1564 has been closed?  Can we avoid the resolution now?

**Comment by NickGerleman** [comment]
Yep. Let me update this again.

**Comment by NickGerleman** [comment]
I want to integrate the [next 0.68 RC](https://github.com/facebook/react-native/commits/0.68-stable) into our 0.68-stable, since it has some changes, we want. I plan to clean up the resolution there at the same time.

**Review by jonthysell — APPROVED** [review]

**Pull request merged**
