### PR TITLE
[Telemetry] Enable data uploading

### LINKED ISSUE #14089: Enable 1DS telemetry by setting the RNW instrumentation key
### Summary

We need to explicitly declare the instrumentation key, so the telemetry data gets uploaded, then we can see data flowing and processed in the measures.

### Motivation

Drive decision making based on data (usage, reliability, performance, etc.)

### Basic Example

_No response_

### Open Questions

_No response_

### PR DESCRIPTION
**Pull request by danielayala94**
## Description
Set the telemetry instrumentation key to upload telemetry.

**Resolves #14089**

### Type of Change
- New feature (non-breaking change which adds functionality)

### Why
Currently, the telemetry data goes nowhere.

As the backend is taking shape, we can start to let the data to flow upstream.

### What
Instead of an empty instrumentation key, set the one associated to the RNW telemetry project.

## Screenshots
N/A

## Testing
Ran the telemetry unit tests. Number of telemetry instances is correctly updated to the backend, with little to no delay. Measures are getting updated too with the new data.

## Changelog
Yes

_Enables telemetry collection to monitor RNW reliability, performance, and usage._

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/14039)

### CODE REVIEW

**Comment by danielayala94** [comment]
Closing this PR for now. Once privacy review has cleared all telemetry aspects of RNW, I'll reopen this.

**Comment by danielayala94** [comment]
Bring this PR back to life as we have the blessing of privacy folks.

**Review by TatianaKapos — APPROVED** [review]
LGTM! I see you put "yes" on the changelog section, can you write what short blurb of what should go on the changelog for this PR?

**Pull request merged**
