### PR TITLE
Remove Insecure Trees of E2ETest Dependencies

### PR DESCRIPTION
**Pull request by NickGerleman**
There's a multitude of insecure dependencies brought in by Appium, with some present even on the latest versions. Appium includes large packages for platform-specific drivers that are the source of this, and are unneeded for our purposes.

This change adds stub packages to our workspace for some of these to cut out large forests of our dependency tree, which still contain the insecure dependencies.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6185)

### CODE REVIEW

**Comment by NickGerleman** [comment]
I think this might also fix the minimist issue since jimp was bringing that in and was updated here. Let me check.

**Comment by NickGerleman** [comment]
Forced new resolutions for the entire tree and got to the point where that doesn't blow up the world. We still can't get around bringing in a bad version of minimist because of a adependence on an older version of mkdirp, so we have a resolution for that now.

**Comment by NickGerleman** [comment]
Wow, E2ETest has both runtime and build-time issues for different depenedencies :)

New plan. Going to try to install WinAppDriver 1.2 as part of the pipeline to try to fix the dependency issue properly.

**Comment by NickGerleman** [comment]
Doing something less scoped is hard. Going back to scoped duct taping our dependencies.

**Review by dannyvv — APPROVED** [review]

**Review by acoates-ms — APPROVED** [review]

**Review by jonthysell — APPROVED** [review]

**Comment by NickGerleman** [comment]
FYI @jonthysell this change + another overlap in removing the last dependents on the legacy yargs-parser. We should be able to get rid of that now with a yarn install changing the lockfile again I think.

**Pull request merged**
