### PR TITLE
Start removal of ReactUWP

### PR DESCRIPTION
**Pull request by acoates-ms**
Now that playground-win32 is not using ReactUWP, we can start cleaning up code related to reactUWP.

First step basically just removes the actual ReactUWP project, and the test projects that test the ReactUWP project.  The files within ReactUWP folder are used a bunch by Microsoft.ReactNative, so I can't delete the directory out right yet. 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4920)

### CODE REVIEW

**Comment by NickGerleman** [comment]
@acoates-ms some of the ReactUwp tests are for things used in MSRN still :/. Can we keep this coverage?

**Comment by NickGerleman** [comment]
See #4867

**Comment by acoates-ms** [comment]
I dont think these tests are useful:

Universal.UnitTests:
 - AppState: Tests that a stub impl of AppState that always returns Active returns active (MS.RN uses a new AppState module
 - CreateModulesTest verifies that it can run the ctor of several core native modules that are all run on boot on an instance, so already covered by E2E tests (which will actually run methods on them)
 - CreateViewMangersTest verifies that it can run the ctor of several view managers that are all run on boot of E2E, which also actually verifies their functionality.
 - StringConversionsTest verifies some chakra specific string conversion logic (this one seems like the only real test in here)  -- I'll look at moving it

Universal.IntegrationTests:
 - Boots a very simple bundle that does much less than the E2E test, and does it all through the ReactUwp APIs which we dont care about.

**Comment by vmoroz** [comment]
I agree with @acoates-ms that current tests are not that much useful. @aeulitz already created the Microsoft.ReactNative.IntegrationTests where we start to add more and more end-to-end tests. There is also similar test project for the Desktop react-native-win32.dll. The unit tests Microsoft.ReactNative.Cxx.UnitTests and Microsoft.ReactNative.Managed.UnitTests test code that works on top of the ABI-safe APIs. We already have a much better test coverage than before. Removing the ReactUWP should free us for much more project improvements and remove extra level of indirections, convert native modules to TurboModules, etc. We can always restore/add the couple of tests which we are removing today.

**Comment by acoates-ms** [comment]
I'll also mention that these tests do not appear to be being run today.  (They are built, but never run)

**Comment by NickGerleman** [comment]
Makes sense. Thanks for looking at the details 🙂

**Pull request merged**
