### PR TITLE
Adds optional API for window sizing root

### LINKED ISSUE #10211: Remove assumptions that XamlRoot::Content() matches Window size
### Problem Description

There are at least two callsites that assume that the XamlRoot Size or the ActualSize of the XamlRoot::Content matches the size of the XAML Islands HWND:
- https://github.com/microsoft/react-native-windows/blob/003602b90aeda1b2a43702c6a9307c0f01010e59/vnext/Microsoft.ReactNative/Modules/LogBoxModule.cpp#L48-L54
- https://github.com/microsoft/react-native-windows/blob/cc7095ce487625a9a0a9b99b4b8df4043698eb78/vnext/Microsoft.ReactNative/Modules/AlertModule.cpp#L67-L85

While this is generally a good assumption, this may not always be the case. For example, in our app, we've worked around a XAML Islands bug https://github.com/microsoft/microsoft-ui-xaml/issues/2101 by making the root Grid larger than the HWND by a factor equivalent to the DPI scale factor.

As such, we need to 

### Steps To Reproduce

There's no immediate repro in this repo, but one way to repro is to try and build a drag and drop handler for a XAML Islands react-native-windows app, and see that the full window is not a valid drop target for high DPI scale settings.

### Expected Results

React Native Windows may want to assume that the root level content or XamlRoot matches the HWND size by default, but we should allow apps to override this behavior with a "window sizing root" target element that does match the window size.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

_No response_

### Target Device(s)

_No response_

### Visual Studio Version

_No response_

### Build Configuration

_No response_

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by rozele**
### Type of Change
_Erase all that don't apply._
- Bug fix (non-breaking change which fixes an issue)

### Why
It may not always be the case that the XamlRoot is the same size as the HWND. For example, in our app, to work around https://github.com/microsoft/microsoft-ui-xaml/issues/2101, we resize the XamlRoot content to be larger than the window by the DPI scale factor and then resizes the ReactRootView to be the same size as the HWND. However, this breaks the LogBoxModule and the AlertModule, which make the assumption that the XamlRoot is the same size as the window.

Resolves #10211

### What
To workaround this assumption, this change adds an API to XamlUIService that allows you to specify which view under XamlRoot is equivalent to the window size for the purpose of sizing things like the ContentDialog smoke screen and the LogBox popup.

## Testing
As a demonstration example, I changed the Playground-win32 app to set the ReactRootView as the window sizing root and forced the ReactRootView to be smaller than the XamlRoot grid. You'll notice that the LogBox popup and ContentDialog smoke screen still attach to the window at the origin (they are not offset to the position of the window sizing root), but this is not something I plan to change as the intention of the window sizing root is that it actually matches the size of the window (so no offsets should be required):

https://user-images.githubusercontent.com/1106239/176501861-d53483d8-d6c9-467e-bd76-d5177c523b5b.mp4

Here's the same working correctly when the ReactRootView actually matches the size of the HWND:

https://user-images.githubusercontent.com/1106239/176502260-705d743c-ee0b-4afb-b63b-f33234742e24.mp4

_Optional_: Describe the tests that you ran locally to verify your changes.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10221)

### CODE REVIEW

**Review by asklar — CHANGES_REQUESTED** [review]
I left a comment in the issue but just so that it's on here too, we had some discussions about how this should work and don't feel this is exactly the right approach. Let's sync up offline @rozele @jonthysell @acoates-ms @stmoy  to discuss further

**Comment by rozele** [comment]
How about something like this:

winrt::Size XamlUIService::GetWindowSize()
void XamlUIService::OnWindowSizeChanged(std::function<void()> callback)
void XamlUIService::SetWindowSize(winrt::Size size)

**Comment by chrisglein** [comment]
@rozele @asklar Did that offline conversation end up happening? How can unstick this PR?

**Comment by rozele** [comment]
It did not. Presumably some API will be needed for Fabric that doesn't depend on XAML, so we'll migrate to that once it's available. This can be closed if there's no near term interest for Paper.

**Comment by chiaramooney** [comment]
Discussed in PR Triage. No near term interest for this change on Paper.

**Pull request closed without merging**
