### PR TITLE
[ActivityIndicator] Map color property to Control.Foreground

### PR DESCRIPTION
**Pull request by marlenecota**
#2110 

This change adds the color property to the ActivityIndicator component. 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2253)

### CODE REVIEW

**Comment by jonthysell** [comment]
Do you need to even add the TryUpdateForeground? Won't ControlViewManager::UpdateProperties take care of it?

**Comment by randy-flynn** [comment]
> Do you need to even add the TryUpdateForeground? Won't ControlViewManager::UpdateProperties take care of it?

Yes, it should. ControlViewManager implements a bunch of properties without declaring them. It's up to the subclasses to declare the ones they implement. So, the addition to GetNativeProps() should be sufficient.

**Comment by ahimberg** [comment]
interesting, the base class has TryUpdateForeground but not all react-native controls are documented to have a 'color' prop.  Picker, ActivityIndicator, Text do but everything else is just backgroundColor.  so maybe TryUpdateForeground shouldn't be in the base.

**Comment by randy-flynn** [comment]
> If not now we can log an issue to figure out which controls actually support this

Another angle on this is that it's okay to "support" it at this level as long as the JavaScript/TypeScript enforce what can be set. But I am not sure this is wise. If the default implementations trigger any weird conflicts this could be an issue. E.g. if "color" needs to map to BackgroundBrush for one view implementation then this will get in the way.

**Pull request merged**
