### PR TITLE
[0.64] Improve Microsoft.ReactNative compilation speed (#7148)

### PR DESCRIPTION
**Pull request by vmoroz**
Cherry pick PR #7148
Other changes
- Removed forked TurboModuleUtils.h/.cpp files - part of PR #6832.
- Fixed Microsoft.ReactNative.vcxproj.filters corrupted by PR #7360.

Original PR #7148 description:

Previously we have reduced size of our PCH files to make sure that our code compiles on computers with low resources.
The issue is that it significantly increased compilation time on powerful computers.

In this change we improve the compilation speed by putting back includes into the pch.h file, but we make it conditional.
To improve the compilation speed developers can set `RNW_FASTBUILD` environment variable to `true`. It will result in bigger PCH file, but faster compilation speed.

Other related changes to improve the compilation speed:
- Added PCH to Folly and ReactCommon projects. We add `pch.h` to the `ForcedIncludeFiles`.
- Make sure that Microsoft.ReactNative always uses generated C++/WinRT files instead of occasionally picking them up from the SDK folder. While working on the PR I have noticed that the same C++/WinRT header file can be picked up by different .cpp files from different locations. We add the `$(GeneratedFilesDir)` to `AdditionalIncludeDirectories` to fix it.
- Make sure that we do not compile again RN files inside of Microsoft.ReactNative project: they are linked from the ReactCommon, and we disable their compilation in Microsoft.ReactNative.Cxx shared project. See the `BuildMSRNCxxReactCommon` property.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7379)

### CODE REVIEW

**Review by asklar — APPROVED** [review]

**Comment by NickGerleman** [comment]
> Fixed Microsoft.ReactNative.vcxproj.filters corrupted by PR #7360.

This one seems important. From testing the preview, VS is still able to open the template solution without issues luckily. We need to be super careful if we're backporting changes, since the structure of 0.64 is four months older than master.

@vmoroz  @asklar 0.64 is at the age where we need to consider only low risk or business-critical changes. My gut instinct is that removing a source copy, or undocumented opt-in build changes wouldn't fit the bill, but I would like to understand your thoughts.

**Comment by asklar** [comment]
I'm not super worried about the PCH part (i.e. I'd be ok if 0.64 doesn't get it); main thing I saw of value in this PR was deforking the turbomodule files which seems like a good/necessary thing if RN core is now stable and forked

**Comment by NickGerleman** [comment]
Note that changes to Facebook's master branch since last November will not effect our 0.64-stable branch unless they are cherry-picked into Facebook's 0.64-stable branch.

The file we have locally is a source copy of Facebook's, so the change shouldn't have a functional impact. Deforking does help us in the event that changes happen to the file in the upstream 0.64-stable branch. Upstream 0.64-stable has been largely frozen since November though.

**Comment by NickGerleman** [comment]
FWIW I don't think this change is particularly high risk, but there have been plenty of "low-risk" changes over the last year that have bitten us 😂.

**Pull request merged**
