### PR TITLE
[0.62] Fixed external targets for apps and libs

### LINKED ISSUE #5581: Unable to build and deploy new app in RNW 0.62
It seems in the external app targets for 0.62 we're missing the "Deploy" target, which means while everything works with "run-windows", you can't build and deploy your app from visual studio.

### PR DESCRIPTION
**Pull request by jonthysell**
This change adds the "Deploy" target to Microsoft.ReactNative.Uwp.CppApp.targets  and Microsoft.ReactNative.Uwp.CSharpApp.targets .

This change also adds the "Private" flag to the M.RN project reference for libs, which was missing and causes problems when trying to consume the modules in your app.

Closes #5581

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5582)

### CODE REVIEW

**Comment by NickGerleman** [comment]
Going to mark this as approved since two folks from triage already looked at it. Seems like a no brainer to me, but will start a quick thread to keep folks in the loop.

**Comment by jonthysell** [comment]
> we probably need other changes: #5454 and #5500

I looked into these changes, and unfortunately, not only have the local-cli scripts been transformed from js to ts, it looks like these changes depend on other changes in the deploy scripts and I'm not sure how to cut out just what we would need.

**Comment by jonthysell** [comment]
Currently doing one final local test before checking this in.

**Comment by asklar** [comment]
> Currently doing one final local test before checking this in.

@jonthysell let me know if you'd like me to take a look at anything regarding porting these down

**Comment by jonthysell** [comment]
> @jonthysell let me know if you'd like me to take a look at anything regarding porting these down

@asklar I just wanted to verify that both cs and cpp apps work, both with run-windows and via VS. Everything looks good with just the changes to the targets I've done, but I'm not sure how to port the framework dependency packages stuff since there are lots of changes in deploy.js from 62-63. Do you want to get that into this PR or make another one?

**Comment by jonthysell** [comment]
And this is why you have to actually test everything. I literally accidentally set `<Private>true</Private>` when it's  supposed to be `<Private>false</Private>`

**Comment by asklar** [comment]
> > @jonthysell let me know if you'd like me to take a look at anything regarding porting these down
> 
> @asklar I just wanted to verify that both cs and cpp apps work, both with run-windows and via VS. Everything looks good with just the changes to the targets I've done, but I'm not sure how to port the framework dependency packages stuff since there are lots of changes in deploy.js from 62-63. Do you want to get that into this PR or make another one?

@jonthysell I see that - it looks like 62 forked way earlier than I remembered :-/

Worst case scenario, we can turn off deploy from layout all up by changing this piece of code to **always** use `Install-App` instead of trying to be smart:

```js
  // #4749 - need to deploy from appx for .net projects.
  if (options.release || (await hasDotNetProjects(slnFile))) {
    await runPowerShellScriptFunction(
      'Installing new version of the app',
      windowsStoreAppUtils,
      `Install-App "${script}" -Force`,
      verbose,
    );
  } else {
    const realAppxManifestPath = fs.realpathSync(appxManifestPath);
    await runPowerShellScriptFunction(
      'Installing new version of the app from layout',
      windowsStoreAppUtils,
      `Install-AppFromDirectory "${realAppxManifestPath}"`,
      verbose,
    );
  }
```

**Comment by jonthysell** [comment]
> ```js
>   // #4749 - need to deploy from appx for .net projects.
>   if (options.release || (await hasDotNetProjects(slnFile))) {
>     await runPowerShellScriptFunction(
>       'Installing new version of the app',
>       windowsStoreAppUtils,
>       `Install-App "${script}" -Force`,
>       verbose,
>     );
>   } else {
>     const realAppxManifestPath = fs.realpathSync(appxManifestPath);
>     await runPowerShellScriptFunction(
>       'Installing new version of the app from layout',
>       windowsStoreAppUtils,
>       `Install-AppFromDirectory "${realAppxManifestPath}"`,
>       verbose,
>     );
>   }
> ```

@asklar Is replacing this block with just the contents of the first clause sufficient?

> ```js
>     await runPowerShellScriptFunction(
>       'Installing new version of the app',
>       windowsStoreAppUtils,
>       `Install-App "${script}" -Force`,
>       verbose,
>     );
> ```

**Comment by asklar** [comment]
> > ```js
> >   // #4749 - need to deploy from appx for .net projects.
> >   if (options.release || (await hasDotNetProjects(slnFile))) {
> >     await runPowerShellScriptFunction(
> >       'Installing new version of the app',
> >       windowsStoreAppUtils,
> >       `Install-App "${script}" -Force`,
> >       verbose,
> >     );
> >   } else {
> >     const realAppxManifestPath = fs.realpathSync(appxManifestPath);
> >     await runPowerShellScriptFunction(
> >       'Installing new version of the app from layout',
> >       windowsStoreAppUtils,
> >       `Install-AppFromDirectory "${realAppxManifestPath}"`,
> >       verbose,
> >     );
> >   }
> > ```
> 
> @asklar Is replacing the above block with just the contents of the first clause sufficient?
> 
> > ```js
> >     await runPowerShellScriptFunction(
> >       'Installing new version of the app',
> >       windowsStoreAppUtils,
> >       `Install-App "${script}" -Force`,
> >       verbose,
> >     );
> > ```

Yes that would turn off deploy-from-layout and always require full installation.
Note that this means the user would have to run the build (npx react-native run-windows) elevated or the installation would fail.
So this should be done as a last resort. Are there scenarios that still fail after your fix that you need me to look at before we pull the plug on this for 62?

**Comment by jonthysell** [comment]
> Are there scenarios that still fail after your fix that you need me to look at before we pull the plug on this for 62?

I have confirmed that I've fixed the issues with deploying new cli apps from VS and also fixed the issues with consuming modules that use the new lib targets.

I have done nothing to test issues around having different framework package versions though. Given the work it'll take to backport and test enough of the cli to fix the issue, I'd rather get this PR in as-is and wait and see if anyone complains about framework package problems with 62. Is that okay with you @asklar?

**Comment by asklar** [comment]
> > Are there scenarios that still fail after your fix that you need me to look at before we pull the plug on this for 62?
> 
> I have confirmed that I've fixed the issues with deploying new cli apps from VS and also fixed the issues with consuming modules that use the new lib targets.
> 
> I have done nothing to test issues around having different framework package versions though. Given the work it'll take to backport and test enough of the cli to fix the issue, I'd rather get this PR in as-is and wait and see if anyone complains about framework package problems with 62. Is that okay with you @asklar?

@jonthysell yes that's fine by me thank you for checking :)

**Pull request merged**
