### PR TITLE
Dependencies installer: display expected answers and default one

### PR DESCRIPTION
**Pull request by dgellow**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5547)

### CODE REVIEW

**Comment by dgellow** [comment]
@asklar A bunch of tests are failing but they don't seem to be related to this PR. Not sure what I can do about that...

**Comment by acoates-ms** [comment]
Please run `yarn change` in the root of the repo to generate changefile information for this change.

**Comment by dgellow** [comment]
Is that correct?

image

**Comment by asklar** [comment]
> Is that correct?
> 
> image

@dgellow I'd pick prerelease just in case :)

**Comment by dannyvv** [comment]
@dgellow Thank you very much for your contribution!

**Pull request merged**
