### PR TITLE
[0.64] Component Governance fixes

### PR DESCRIPTION
**Pull request by jonthysell**
* Bumps jszip to 3.7.1
* Bumps tar to 4.4.17
* Bumps xmldom to 0.7.0

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8426)

### CODE REVIEW

**Comment by jonthysell** [comment]
Note, xmldom is having issues publishing their fix to npm, which is why this change points to the github release. See https://github.com/xmldom/xmldom/issues/271

**Review by dannyvv — APPROVED** [review]

**Review by NickGerleman — APPROVED** [review]
Looks like the sample app cert has expired. Will probably need to backport changes to remove the cert into older branches.

**Comment by jonthysell** [comment]
> Looks like the sample app cert has expired. Will probably need to backport changes to remove the cert into older branches.

Yes, @chiaramooney is looking into it, as she did the work for 0.65.

**Comment by jonthysell** [comment]
Waiting for https://github.com/microsoft/react-native-windows/pull/8436

**Comment by NickGerleman** [comment]
YOLO

**Pull request merged**
