### PR TITLE
Add an empty test project Microsoft.ReactNative.ComponentTests.vcxproj

### PR DESCRIPTION
**Pull request by ZihanChen-MSFT**
This project is for testing private APIs in Microsoft.ReactNative
This project currently cannot compile under x86, because MSO files want to use __cdecl by default, but folly files want to use __stdcall by default, which cause unresolved external symbol errors. But x64 is fine.
But we can still use it to test whatever we want in Microsoft.ReactNative for x64, it is better than nothing.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5003)

### CODE REVIEW

**Comment by vmoroz** [comment]
@ZihanChen-MSFT this PR has a number of unrelated changes. I would suggest the following algorithm to prepare you changes when sending PR:
- Do all the changes in your branch as usual. E.g. the branch name could be "MyChanges".
- Before sending PR fetch the latest code from the upstream/master and merge it to your branch.
- Create a new branch in your repo out of upstream/master. E.g. it could be "PR/MyChanges".
- Do a squash merge from the "MyChanges" into your current "PR/MyChanges": 
`git merge --squash --no-commit MyChanges`
- Review all the new files and remove/modify any unnecessary changes. It is like a final review before sending your change.
- Commit the change.  Use up to 56 characters for the commit description. It will be your PR title.
- Run `yarn change` to create a change file. Select there the commit description. 
- Note that your "PR/MyChanges" branch has only two commits: your changes and the change file.
- Create the PR. GitHub usually suggests your latest commit for the PR.  Copy&paste the commit description as the title.

The main benefits of this workflow:
- You have a fine grain control on what goes into the PR.
- The history of all changes are still in your 'developer' branch and can be reused/reviewed by you at any time. E.g. if the "PR/MyChanges" does not look right, the in it can be removed and recreated again.
- Reviewers in CodeFlow see only two iterations.

**Comment by ZihanChen-MSFT** [comment]
@vmoroz Hi, it looks like that once I forked microsoft/react-native-windows, all new changes after I forked will display here, regardless whether I have manually merged or not. I did merged from master before I created since there are a few conflicts. It is a github bug but they prioritized it down several years ago.

**Comment by vmoroz** [comment]
@ZihanChen-MSFT you can always eliminate any unnecessary changes when you do the squash merge as it was described above.

**Comment by ZihanChen-MSFT** [comment]
Open another one https://github.com/microsoft/react-native-windows/pull/5006 to clean changes history

**Pull request closed without merging**
