### PR TITLE
Cleaning up ReactUWP's WinRT code

### PR DESCRIPTION
**Pull request by jonthysell**
* Broke up the megalithic ReactControl.g.idl into separate files
* Fixed the build to clean up midl generated files
* Overall just make it easier for us to iterate on the winrt stuff

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2307)

### CODE REVIEW

**Comment by acoates-ms** [comment]
/azp run
(just testing)

**Comment by kmelmon** [comment]
Version 2 only has one file with changes.  What happened to the other changes?

**Comment by jonthysell** [comment]
> 
> 
> Version 2 only has one file with changes. What happened to the other changes?

CodeFlow shows each commit as a separate version. The changes are all there if you view the PR on GitHub.

**Comment by kmelmon** [comment]
Thanks.  Looking at the history of the Commits in your topic branch, these two commits are listed in the reverse order of what I would expect, which seems to explain version 2 showing fewer changes.  Would you happen to know what operations you did that made this happen?

---
In reply to: [485574379](https://github.com/Microsoft/react-native-windows/pull/2307#issuecomment-485574379) [](ancestors = 485574379)

**Comment by jonthysell** [comment]
I'm going to cancel this and merge and open a new PR into master.

**Pull request closed without merging**
