### PR TITLE
Revert "feat(HighContrast): Expose the XAML HighContrastChanged event to JS"

### PR DESCRIPTION
**Pull request by rozele**
Reverts Microsoft/react-native-windows#1443

### CODE REVIEW

**Comment by antonkh** [comment]
What is broken? I'm testing it with S4L which is based on a slightly outdated fork of RNW.

**Comment by antonkh** [comment]
I think I've found the problem you meant: in the Playground app I get an "Element not found" exception with a callstack referring to `add_HighContrastChanged`

**Comment by antonkh** [comment]
Looks like in case of the playground app the event subscription happens on a wrong thread. I fixed it this way:

```cs
        public override void Initialize()
        {
            DispatcherHelpers.RunOnDispatcher(() =>
            {
                _accessibility.HighContrastChanged += OnHighContrastChanged;
            });
        }
```

It's not clear to me why in S4L it doesn't cause an exception.

**Comment by rozele** [comment]
Ah, right, I think we updated so that Initialize and OnReactInstanceDispose run on the native module queue thread.

**Comment by antonkh** [comment]
I've sent a PR to fix this: #1476

**Comment by rozele** [comment]
Will close this and merge #1476

**Pull request closed without merging**
