### PR TITLE
[main] Set `Content-Length` on the content object and not on the request.

### LINKED ISSUE #6407: XMLHttpRequest doesn't work with Content-Length property
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
```
4.13.0
```

2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.78 GB / 15.62 GB
  Binaries:
    Node: 14.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.7.30517.126 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.5
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. Run the following code. 
2. Press both buttons. 
3. Observer the debug log.

First button works fine, the second one errors out (see what actually happens in the end of this issue).

**Sample Code**

```javascript
import React from 'react';
import {
  SafeAreaView,
  Text,
  StatusBar,
  Button,
} from 'react-native';

const testXmlHttpRequest = (addContentSize) => {
    let xhr = new XMLHttpRequest();
    xhr.onreadystatechange = () => {
        console.log(`request done readyState=${xhr.readyState} status=${xhr.status}`);
    };

    xhr.onerror = () => {
      console.log("an error occured");
    }
    xhr.open("GET", "https://wikipedia.org", true);

    if (addContentSize) {
      xhr.setRequestHeader('Content-Length', 0);
    }

    xhr.send();
}

const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <Button title="Test Without Content-Length" onPress={() => testXmlHttpRequest(false)} />
        <Button title="Test With Content-Length" onPress={() => testXmlHttpRequest(true)} />
      </SafeAreaView>
    </>
  );
};

export default App;
```

## Expected Results
Requests for both buttons don't fail.

## Snack, code example, screenshot, or link to a repository:

The code is failing in NetworkingModule.cpp:289 with the following exception `"Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects."`

I know that my example uses a GET request where `Content-Length` makes no sense, but some libraries (like Amazon's Amplify) set it for POST requests. So it is important for compatibility reasons.

This example also works correctly (both buttons succeed) on every other platform I tested (macOS, iOS, Android).

### PR DESCRIPTION
**Pull request by mandrigin**
fixes #6407

the same as https://github.com/microsoft/react-native-windows/pull/6414 but against the main branch

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6415)

### CODE REVIEW

**Comment by dannyvv** [comment]
@mandrigin: To pass the validation could you run `yarn change` at the root of your repo and push the changes? This will introduce a change file that we use to keep track of semantic versioning the various packages in our repo.

**Comment by mandrigin** [comment]
@dannyvv done

**Review by asklar — APPROVED** [review]

**Comment by dannyvv** [comment]
Thanks for your contribution @mandrigin! The PR is tagged with Request for BackPort. The stake holders will review this PR and make a judgement based on risk/benefits if it warrants backporting. When approved, we can take care of doing that.
Thanks again!

**Comment by mandrigin** [comment]
@dannyvv thanks so much! we have this issue in 0.63.x that we use so I'd love to see it backported!

**Comment by mandrigin** [comment]
@dannyvv I just figured out that we also use the mac version... that means that this needs to be backported to 0.62 too, right? or will there be 0.63 for mac specifically?

**Comment by Khalef1** [comment]
Hi @mandrigin. Thank you for your contribution to react-native-windows! 

I approved the backport request to 0.63. Could you please submit a PR for it?

Regarding your question on the Mac version - this code is not shared between Windows and Mac. I just want to confirm that you are also reproing this issue on Mac

**Comment by mandrigin** [comment]
@Khalef1 I had this PR opened initially, to the  0.63 branch. I can reopen it: https://github.com/microsoft/react-native-windows/pull/6414

This issue isn’t present on a Mac, everything works fine there.

**Comment by Khalef1** [comment]
@mandrigin - Yes reopening #6414 should be fine.

**Pull request merged**
