### PR TITLE
Fix relative include path for Views/Image

### PR DESCRIPTION
**Pull request by rozele**
### Type of Change
_Erase all that don't apply._
- Bug fix (non-breaking change which fixes an issue)

### Why
The DynamicAutomationPeer.h header is in the parent `Views` folder and this include path is not supported by clang. 

### What
This change adjusts the include path.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10275)

### CODE REVIEW

**Review by TatianaKapos — APPROVED** [review]
lgtm!

**Comment by asklar** [comment]
I think including "../foo.h" goes against some cpp core guideline... trying to find the link...

**Review by asklar — CHANGES_REQUESTED** [review]
looking for the cpp guideline that calls this out; in the meantime marking RC to avoid accidental merging

**Comment by rozele** [comment]
@asklar - fixed

**Review by vmoroz — APPROVED** [review]
:shipit:

**Review by asklar — APPROVED** [review]

**Pull request merged**
