### PR TITLE
enable inline source maps

### PR DESCRIPTION
**Pull request by stecrain**
We have been adding this to get source maps working with a project we made from the c# template (well started with the c# template then replaced the app project with c++/winrt).

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/2553)

### CODE REVIEW

**Comment by Thristhart** [comment]
this fixes #2482 (or more accurately works around it)

**Comment by akrantz** [comment]
What's the reason regular source maps don't work?

**Comment by Thristhart** [comment]
@akrantz see https://github.com/microsoft/react-native-windows/issues/2482#issuecomment-494178040 -- it's an issue with metro

**Comment by stecrain** [comment]
@akrantz 
> What's the reason regular source maps don't work?

Not 100% sure honestly. It has something to do with the source maps trying to be served over blob:// instead of http://. All the details we know are in #2482

**Comment by akrantz** [comment]
@stecrain Thanks, I already saw that so I had deleted my question. I saw it is related to using Metro for the packager. I know we use Haul and source maps work.

**Comment by matthargett** [comment]
FWIW, we also found that source maps had to be inline for WebInspector to debug properly when metro was serving the dev bundle. Haul packager and other debuggers may not have the issue.

**Pull request merged**
