### PR TITLE
Fixes bug in BatchingEventEmitter

### PR DESCRIPTION
**Pull request by rozele**
The `eventName` parameter is std::move'd into the BatchedEvent object that gets enqueued. As such, the event removal test `evt.eventName == eventName` was always false because `eventName` had been moved.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7820)

### CODE REVIEW

**Review by NickGerleman — APPROVED** [review]
Thanks! Not sure how this one slipped in...

**Comment by acoates-ms** [comment]
How much does this break?  Should this be ported to 0.65?  0.64?  When was this code introduced?

**Comment by rozele** [comment]
> How much does this break? Should this be ported to 0.65? 0.64? When was this code introduced?

@acoates-ms BatchingEventEmitter did not make it into 0.64. I can't find the stable branch for 0.65, so I don't know if it needs to be cherry-picked there (thoughts @NickGerleman?). I suspect if Nick's original PR winds up in 0.65, then we should pick this change, as without the change, the BatchingEventEmitter is actually a performance regression for events rather than an optimization.

**Comment by NickGerleman** [comment]
This is new for 0.65 and was not cherry picked.

**Comment by NickGerleman** [comment]
> How much does this break? Should this be ported to 0.65? 0.64? When was this code introduced?

As for how much is broken, it totally breaks the optimization. I definitely tested the change, so I'm guessing I might have made this as a last minute edit that introduced the issue.

**Pull request merged**
