### PR TITLE
Add windows adk to machine setup script

### PR DESCRIPTION
**Pull request by dannyvv**
This is useful to have on the build agents so we can capture ETW traces to diagnose issues.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5541)

### CODE REVIEW

**Comment by dannyvv** [comment]
> can you make this optional?
> rnw-dependencies should be used primarily to set up dependencies for getting started with RNW (i.e. to write an app), and optionally to set up dependencies for RNW devs, but we shouldn't force dependencies that are specific to RNW devs onto app devs. Can this and the other RNW dev deps be added only if you pass something like -internal or something? -dev?
> (Appium and winappdriver fall in this category too)

@asklar I see 3 options, let me know what you prefer. This is my order of preference:
1.  Add support for tag filters like: "Minimal", "BuildMachine"
     This would help me wiht the CI machines as well since the scripts time out after 1 hour and with VS being so slow to install... it might help splitting that out into a separate step.
2. Shall I replace the `Enterprise` flag with `BuildMachine` and hang these on that?
3. Add new flags for each added task

**Comment by asklar** [comment]
> > can you make this optional?
> > rnw-dependencies should be used primarily to set up dependencies for getting started with RNW (i.e. to write an app), and optionally to set up dependencies for RNW devs, but we shouldn't force dependencies that are specific to RNW devs onto app devs. Can this and the other RNW dev deps be added only if you pass something like -internal or something? -dev?
> > (Appium and winappdriver fall in this category too)
> 
> @asklar I see 3 options, let me know what you prefer. This is my order of preference:
> 
> 1. Add support for tag filters like: "Minimal", "BuildMachine"
>    This would help me wiht the CI machines as well since the scripts time out after 1 hour and with VS being so slow to install... it might help splitting that out into a separate step.
> 2. Shall I replace the `Enterprise` flag with `BuildMachine` and hang these on that?
> 3. Add new flags for each added task

yeah that's my order of preference too. Maybe -innerLoop ? or -complete ? I'm not too concerned about what we call it as long as it's clear that people writing apps with RNW don't need to pass that and that it's only or us to use either on build machines or to set up our own PCs (e.g. I use it to verify changes in a Windows Sandbox session)

**Comment by dannyvv** [comment]
> > > can you make this optional?
> > > rnw-dependencies should be used primarily to set up dependencies for getting started with RNW (i.e. to write an app), and optionally to set up dependencies for RNW devs, but we shouldn't force dependencies that are specific to RNW devs onto app devs. Can this and the other RNW dev deps be added only if you pass something like -internal or something? -dev?
> > > (Appium and winappdriver fall in this category too)
> > 
> > 
> > @asklar I see 3 options, let me know what you prefer. This is my order of preference:
> > 
> > 1. Add support for tag filters like: "Minimal", "BuildMachine"
> >    This would help me wiht the CI machines as well since the scripts time out after 1 hour and with VS being so slow to install... it might help splitting that out into a separate step.
> > 2. Shall I replace the `Enterprise` flag with `BuildMachine` and hang these on that?
> > 3. Add new flags for each added task
> 
> yeah that's my order of preference too. Maybe -innerLoop ? or -complete ? I'm not too concerned about what we call it as long as it's clear that people writing apps with RNW don't need to pass that and that it's only or us to use either on build machines or to set up our own PCs (e.g. I use it to verify changes in a Windows Sandbox session)

sounds good. will do

**Comment by dannyvv** [comment]
@asklar: Added infrastructure using tags with PR: #5554 The ADK is now only part of the buildlab tag.

**Pull request merged**
