### PR TITLE
Expose placeholder prop on Picker

### PR DESCRIPTION
**Pull request by lyahdav**
This exposes the ComboBox PlaceholderText as a prop on Picker called placeholder.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6552)

### CODE REVIEW

**Comment by NickGerleman** [comment]
@lyahdav the built-in Picker component is close to being jettisoned from react-native, and react-native-windows by proxy. E.g. the RNTester example for it was recently removed after the component has been deprecated for a few releases.

I'd definitely reccomend making any changes to the Picker community module, which supports Windows and has a very similar implementation. Not sure if FB's build system for RNW Would make that challenging, but it's likely this change will otherwise go away when the component is removed.

**Comment by NickGerleman** [comment]
I think @rectified95 might have some additional context

**Comment by NickGerleman** [comment]
Link to the community module. It looks like it does also have macos support https://github.com/react-native-picker/picker

**Comment by rectified95** [comment]
I agree with Nick - this code is only here because it has not been removed from RN core yet after deprecation. The community module repo is the way to go - the change should map 1-1 there.

**Pull request closed without merging**
