### PR TITLE
Revert telemetry update in 0.63

### PR DESCRIPTION
**Pull request by dannyvv**
This reverts commit 1df9474858223ada25c2cb214808edabb1286b4e.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6462)

### CODE REVIEW

**Comment by NickGerleman** [comment]
@dannyvv its likely tests with Verdaccio will fail until we do a beachball bump.

**Review by NickGerleman — APPROVED** [review]

**Comment by dannyvv** [comment]
@NickGerleman added a 'bump'

**Comment by dannyvv** [comment]
Actually I see that we have to do this in differtn order...

**Comment by NickGerleman** [comment]
If the package is already published, we might just want to wait on a forward fix if we think we can make one quickly, to avoid pushing out three versions in quick succession.

**Comment by dannyvv** [comment]
Abandoning in favor of roll forward

**Pull request closed without merging**
