### PR TITLE
[Fix PR] Update dependencies script to support new ADO images that don't have node 12

### LINKED ISSUE #5704: The rnw-dependencies.ps1 script does not reinstall the node version if it has version 14.x
## Environment
Target Platform Version(s):Desktop
Target Device(s): Visual Studio 2019
Visual Studio Version: Debug
npx react-native --version: 4.11.0
npx react-native run-windows --info:
System:
OS: Windows 10 10.0.18362
CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Memory: 1.04 GB / 7.89 GB
Binaries:
Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.19.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
npmPackages:
react: 16.11.0 => 16.11.0
react-native: ^0.62.0-0 => 0.62.2
react-native-windows: ^0.62.0-0 => 0.62.4
Installed UWP SDKs:
10.0.17134.0
10.0.17763.0
10.0.18362.0
10.0.19041.0

reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock":
AllowDevelopmentWithoutDevLicense REG_DWORD 0x1
AllowAllTrustedApps REG_DWORD 0x1

## Steps To Reproduce
1.Run script on elevated power shell 'https://raw.githubusercontent.com/microsoft/react-native-windows/master/vnext/Scripts/rnw-dependencies.ps1'
2.The script detects that I don't have the version of node 12 or 13 and asks me if I want to install it
3.When i response 'yes' the window close, doesn't install a different version node.

## Expected Results
Install node version and dont close de power shell window

scripterror2
scripterror1

### PR DESCRIPTION
**Pull request by dannyvv**
closes  #5704

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6427)

### CODE REVIEW

**Comment by dannyvv** [comment]
If this doesn't work I'll add a Node install step to the CI...

**Review by asklar — APPROVED** [review]
we've had issues with v14 (e.g. #5725) but it sounds like Nick is able to use v14 so maybe this is ok. 
Does it mean this PR will fix #5704?

**Comment by NickGerleman** [comment]
Yeah, Node 14 should be fine as far as I know. I fixed the issue of warnings printed while using it and have been using it as a daily driver for a few months, manually validating various bits and pieces.

**Review by NickGerleman — APPROVED** [review]

**Comment by dannyvv** [comment]
> we've had issues with v14 (e.g. #5725) but it sounds like Nick is able to use v14 so maybe this is ok.
> Does it mean this PR will fix #5704?

Not sure if it will 'fix' I suspect for that customer choco when launching the 12 installer, the 12 installer says: no need you have 14.
So this change treats the symptoms :)

**Pull request merged**
