### PR TITLE
ToAscii.h Fork Unblocking CI Failure

### PR DESCRIPTION
**Pull request by AgneLukoseviciute**
[CI is hitting Warning C4127](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fms%2Freact-native-windows%2F_build%2Fresults%3FbuildId%3D169980%26view%3Dresults&data=04%7C01%7Cagnel%40microsoft.com%7C32243c7c90524fc8c9bd08d91ed4df9e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637574721893454388%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fYa7QCpOebcbcL3MEeK4sgdx3vCFVQV2MbJ7EY2MouU%3D&reserved=0)(conditional expression is constant) which is treated as an error -- needs change in ToAscii.h(215) to fix so I'm adding a forked file for now. I will put in a change in Folly to get rid of the fork going forward. 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7830)

### CODE REVIEW

**Review by dannyvv — APPROVED** [review]

**Comment by asklar** [comment]
did this break due to a VS update? or due to a new ingestion of Folly?

**Review by asklar — APPROVED** [review]

**Comment by dannyvv** [comment]
@asklar : It seemed a new version of Folly
@AgneLukoseviciute : The PR is not running due to me renaming the main branch. You'll need to merge the latest of `origin/main`

**Comment by asklar** [comment]
@dannyvv ok so my follow up question is why did we ingest a new version of folly if it didn't pass CI :)

**Comment by dannyvv** [comment]
@asklar : PR doesn't build the full matrix. It builds X64ReleaseFast and X86DebugFast. This error only occurred on X64Debug

**Pull request merged**
