### PR TITLE
Removed Microsoft.ReactNative.Manager.ReactPackageProvider registration from C# template

### PR DESCRIPTION
**Pull request by qmatteoq**
This PR addresses issue #8108 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8109)

### CODE REVIEW

**Review by asklar — APPROVED** [review]

**Comment by vmoroz** [comment]
@dannyvv, do you remember why do we have two different package providers in the default C# app template?

**Comment by asklar** [comment]
> @dannyvv, do you remember why do we have two different package providers in the default C# app template?
+ @jonthysell who debugged this
the managed project used to be a shared-items project, so the reflection worked inside of that assembly.
however the managed project later became its own DLL, and reflection won't work outside of the app assembly (unless we add runtime directives). I'm unclear on why this isn't a problem for more / non-WAP customers though, maybe Jon will know.

**Comment by dannyvv** [comment]
The old one was left there for backwards compat to not force people to update that don't want to. So user had a choice of using the old or the new model.

**Comment by dannyvv** [comment]
@asklar / @vmoroz  / @jonthysell : Please note that there is a reflection based one if one really wants to sue that one that takes a generic type as argument:
```cs
PackageProviders.Add(new ReflectionReactPackageProvider<App>());
```

This is documented in [Return to use reflection](https://microsoft.github.io/react-native-windows/docs/native-modules-csharp-codegen#return-to-use-reflection)

**Review by dannyvv — APPROVED** [review]

**Pull request merged**
