### PR TITLE
Automatically find the proper remote for `yarn change`

### PR DESCRIPTION
**Pull request by dannyvv**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6742)

### CODE REVIEW

**Comment by NickGerleman** [comment]
This won't work for stable branches, where we change the change script automatically for cutting a new branch. We should change that as well, or even better would be to add this sort of logic to beachball itself to add a configurable remote url.

**Comment by dannyvv** [comment]
> This won't work for stable branches, where we change the change script automatically for cutting a new branch. We should change that as well, or even better would be to add this sort of logic to beachball itself to add a configurable remote url.

Yeah, was about to type you a message for when back on how to update this when we create forks :)
In the mean time I filed [beachball#460](https://github.com/microsoft/beachball/issues/460)

**Comment by vmoroz** [comment]
Could we put this logic into a separate .ps1 file? The new string in package.json looks too long for a causal reading.

**Comment by vmoroz** [comment]
Currently the 'master' branch is hardcoded. Ideally we should take the current branch and see what it is based on. I guess the algorithm could walk commits in the current branch until it sees a remote branch from Microsoft repo. We usually create our bug or feature branches out of the Microsoft repo branch.

**Comment by jonthysell** [comment]
> Currently the 'master' branch is hardcoded. Ideally we should take the current branch and see what it is based on. I guess the algorithm could walk commits in the current branch until it sees a remote branch from Microsoft repo. We usually create our bug or feature branches out of the Microsoft repo branch.

I'd rather a script that just prompts the user with a list of branches (filtered down to master / stable branches) if the branch isn't specified.

**Comment by dannyvv** [comment]
I'll wait for beachball to fix things.

**Pull request closed without merging**
