### PR TITLE
Reduce ReactRootView coupling and add support for InitialProps changes

### PR DESCRIPTION
**Pull request by aschultz**
-Introduce ReactRootViewBase to reduce coupling with ReactInstanceManager and permit custom implementations that control their own lifecycle and insertion into the manager.
-Add support for updating InitialProps. Changes will trigger componentWillReceiveProps on the React component.

Together these changes should help anyone attempting to integrate individual ReactNative components into a larger C# application.

### CODE REVIEW

**Comment by rozele** [comment]
@aschultz - it would be great if you could separate these changes. I think it's incredibly valuable to be able to update root view props. I'm not yet convinced we need more base classes for root views.

Also, is there some documentation for updating RN root view props you can point to?

**Comment by aschultz** [comment]
@rozele I can do that.

The basis for the ReactRootViewBase is some experimentation I've been doing with hosting multiple React components as separate root views that can be embedded on a XAML page with code like <react:ReactPanel ModuleName="MyComponent" />. Instead of being initialized programmatically with StartReactApplication, the element hooks Loaded and Unloaded events to call AttachMeasuredRootView and DetachRootView respectively (using a global reference to a ReactInstanceManager).

Such a ReactPanel can't be built right now without using reflection to set the _jsModuleName and _initialProps fields. To avoid that, either ReactRootView needs to be changed to support both usage patterns, or decoupled with a Base implementation so that AttachMeasuredRootView is more agnostic.

**Comment by rozele** [comment]
@aschultz - follow up question - is there any benefit to using Panel over Canvas? Does everything work as expected? I assume the first child of the root view uses `Canvas.SetLeft` and `Canvas.SetTop` like any other view, but thinking about it, in general the first child of the root view will likely always be at 0,0...

**Comment by aschultz** [comment]
@rozele Sorry for the confusion. My "ReactPanel" still inherits from SizeMonitoringCanvas because the React UI managers require it.

**Pull request closed without merging**
