### PR TITLE
Add beachball branch config to package.json

### PR DESCRIPTION
**Pull request by rozele**
With the recent renaming of the main branch, we should also set the default branch name in package.json so we don't need to run:

```
yarn change -b main
```

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7838)

### CODE REVIEW

**Comment by NickGerleman** [comment]
cc @dannyvv who updated the branch name. I know we also recently bumped to Beachball 2.0 (not sure if it does this by default now).

**Review by AgneLukoseviciute — APPROVED** [review]

**Comment by AgneLukoseviciute** [comment]
@NickGerleman from running `yarn change` locally it looks like even with the BeachBall update the default is still to check against upstream/master.

**Comment by NickGerleman** [comment]
Good to know. This might need a little bit of extra work though, since we script changing the branch name in stable branches, and pass branch name via CLI args.

**Comment by dannyvv** [comment]
I'm chatting with @kenotron about this.

**Review by dannyvv — APPROVED** [review]

**Pull request merged**
