### PR TITLE
Update to react-native@0.58.6-microsoft.8

### PR DESCRIPTION
**Pull request by acoates-ms**

### CODE REVIEW

**Comment by acoates-ms** [comment]
No - this one will need some changes.  This is an auto generated PR.
-- Lets hold off on merging this one for a bit.

**Comment by jonthysell** [comment]
Ah okay. Well, at least there'll be a bunch of build failures to look at, right?

**Comment by acoates-ms** [comment]
Actually the change to make it work should just be to update some of the other dependencies in package.json to match the versions used in react-native 58.  But I'm waiting for some fixed in react-native for mac before we update windows.

**Comment by jonthysell** [comment]
At the very least you'll need to bump react to 16.6.0

**Pull request closed without merging**
