### PR TITLE
Fixed typo in template which breaks C# autolinking

### LINKED ISSUE #7097: Autolinking doesn't work with React Native 0.63 if you use a C# host app
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:

4.14.0

2. `npx react-native info`:

```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.41 GB / 15.60 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.15063.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.31005.135 (Visual Studio Enterprise 2019), 16.9.31004.235 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.20
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new React Native project and initialize the Windows extension using the C# language

```
npx react-native-windows-init --overwrite --language cs
```

2. Add any native module via package manager, for example:

```
yarn add react-native-camera
```

3. Run the application:

```
npx react-native run-windows
```

4. Write some code to use the native module you have just installed.

## Expected Results
The module works just fine, thanks to autolinking. Instead, the application complains about not being able to find the native module.
The problem happens because, when the host app is based on C#, the AutoLinkedNativeModule.g.cs file isn't filled properly:

```
// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from react-native-camera
using ReactNativeCameraCPP;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
        }
    }
}
```

As you can see, the namespaces of the native module are added to the header, but the `RegisterAutolinkedNativeModulePackages()`  method is empty.

If you repeat the same steps with a C++ host app, instead, the ` RegisterAutolinkedNativeModulePackages()`  method is implemented in the right way.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

### PR DESCRIPTION
**Pull request by jonthysell**
Closes #7097

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7102)

### CODE REVIEW

**Review by dannyvv — APPROVED** [review]

**Comment by dannyvv** [comment]
I saw a recent rename for this go into master. It could be that the rename just missed this case. I saw that you created backports for all branches. I didn't see the rename backport all the way, so these backports might accidentally break it.

**Review by asklar — APPROVED** [review]

**Comment by jonthysell** [comment]
> I saw a recent rename for this go into master. It could be that the rename just missed this case. I saw that you created backports for all branches. I didn't see the rename backport all the way, so these backports might accidentally break it.

I've opened three PRs, one for master, one for 0.64, and one for 0.63. None of those branches already have this fix.

**Comment by jonthysell** [comment]
I can't seem to be able to generate the proper changes files for this PR. It says it already sees the change file from @asklar 
 's https://github.com/microsoft/react-native-windows/commit/d7a56e503a532058321fc962664fb013e531541d

**Comment by asklar** [comment]
> I can't seem to be able to generate the proper changes files for this PR. It says it already sees the change file from @asklar Alexander Sklar FTE
> 's [d7a56e5](https://github.com/microsoft/react-native-windows/commit/d7a56e503a532058321fc962664fb013e531541d)

make sure you're calling `yarn change --branch upstream/master`

**Review by NickGerleman — APPROVED** [review]

**Pull request merged**
