### PR TITLE
Update comments in IReactDispatcher.idl

### PR DESCRIPTION
**Pull request by xidachenfb**
## Description
This is a follow up change requested in https://github.com/microsoft/react-native-windows/pull/9900

### Type of Change
- This change requires a documentation update

### Why
What is the motivation for this change? Add a few sentences describing the context and overall goals of the pull request's commits.
This change updates comments for better readability.

## Screenshots
Add any relevant screen captures here from before or after your changes. 
N/A

## Testing
If you added tests that prove your changes are effective or that your feature works, add a few sentences here detailing the added test scenarios.
N/A

_Optional_: Describe the tests that you ran locally to verify your changes.
N/A

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9959)

### CODE REVIEW

**Review by asklar — APPROVED** [review]
thanks @xidachenfb!!

**Comment by asklar** [comment]
can you run `yarn change` at the root of the repo to produce a changefile and commit the result?

**Comment by xidachenfb** [comment]
@asklar Change file has been uploaded. If it looks good, please merge it for me as I am not a contributor yet. Thank you.

**Pull request merged**
