### PR TITLE
Adding Accessibility Prop accessibilityItemType on ViewWin32

### PR DESCRIPTION
**Pull request by samuelfreiberg**
This accessibility prop is needed by some partners for the help of reading comments/replies.

I will backport this to .65/.64/.63

**[UIA_ItemTypePropertyID](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-automation-element-propids)** - 
Identifies the ItemType property, which is a text string describing the type of the automation element.
ItemType is used to obtain information about items in a list, tree view, or data grid. For example, an item in a file directory view might be a "Document File" or a "Folder".
When ItemType is supported, the string must match the application UI language or the operating system default UI language.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8543)

### CODE REVIEW

**Comment by acoates-ms** [comment]
Is this prop in core?
How does this map to aria? Or what is the web equivalent?
How is it different than say accessibilityRole?

**Comment by samuelfreiberg** [comment]
@acoates-ms 

I looked in core and did **not** see this property.

We couldn't find the web-equivalent of this prop. It's defined [here as a UIA property](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-automation-element-propids). 

As for the difference between this an accessibilityRole, accessibilityRole is the name of the control as a whole. For example, RadioGroup or List. The accessibilityItemType allows the user to get more specific. For example, the usage for ModernComments is marking each comment card as "Comment" or "Reply". It's not necessarily the name of the control, but rather the specific type of the control

**Comment by NickGerleman** [comment]
@samuelfreiberg I am in the current process of cutting the 0.66-stable branch from last night's release. You will want to create this commit against `0.66-stable` as well, later today.

**Review by ksiler — APPROVED** [review]

**Comment by samuelfreiberg** [comment]
@acoates-ms Just checking if my above answers satisfied your questions, or if there are more action items to be done.

**Review by acoates-ms — APPROVED** [review]

**Pull request merged**
