### PR TITLE
Fix warning of double-importing ExperimentalFeatures.props

### PR DESCRIPTION
**Pull request by dannyvv**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8301)

### CODE REVIEW

**Comment by dannyvv** [comment]
I'm planning to enable `/warnaserror` on the msbuild invocation once we are at zero warnings.

**Comment by NickGerleman** [comment]
Thanks for looking at this. I've been meaning to but never got around to it...

This change does make things a little bit more fragile/harder to reason about bc ExperimentalFeatures.props controls more than JS engine related bits. So we're relying on JSEngine.props to be imported to propagate things we want to.

We had the same multiple import problem with JSEngine.props, and we solved it a slightly different way. Basically modeling after a header guard. The prop sheet sets `JsEnginePropsDefined` to true, then we condition include sites at the property sheet not yet being included.

This guarantees the property sheets are still included, even if transitive dependencies change, and removes the need to reason about where props are coming from.

**Comment by NickGerleman** [comment]
We wouldn't want to define that directly for ExperimentalFeatures.props, so there would need to be another layer in front of that.

This is probably fine as is unless we start adding more experimental props, or including it in more places.

**Review by NickGerleman — APPROVED** [review]

**Comment by dannyvv** [comment]
I tried the header guard but was not succesfull.

**Comment by dannyvv** [comment]
I hope to enable warnaserror once these PR's are in. We can cross that bridge when we get there as it will be obvious and blocking.

**Pull request merged**
