### PR TITLE
Updating the chakracore debugger to the lastest version

### PR DESCRIPTION
**Pull request by asachin96**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/2543)

### CODE REVIEW

**Comment by akrantz** [comment]
This is for the Microsoft.ChakraCore.Debugger package not Microsoft.ChakraCore itself. This isn't used by current.

**Comment by akrantz** [comment]
The main improvement is if you inspect an object under the debugger when using ChakraCore, you get the stringified json for it instead of "[object Object]"

**Comment by acoates-ms** [comment]
Oh sorry.  Missed which package it was.

**Pull request merged**
