### PR TITLE
[0.64] Update Microsoft.ChakraCore to 1.11.24 (#7628)

### PR DESCRIPTION
**Pull request by jonthysell**
This backports #7628 to 0.64.

* Update Microsoft.ChakraCore to 1.11.24

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7653)

### CODE REVIEW

**Comment by jonthysell** [comment]
@JunielKatarn I started this backport of ReactWindows.ChakraCore from 1.11.20 to 1.11.24 to get it in before publishing the next 0.64 today, but I see 0.64 also has a Microsoft.ChakraCore.ARM64 with a similar version number. Do these need to be in sync? I don't see a 1.11.24 package for Microsoft.ChakraCore.ARM64.

**Review by dannyvv — APPROVED** [review]

**Comment by JunielKatarn** [comment]
> @JunielKatarn I started this backport of ReactWindows.ChakraCore from 1.11.20 to 1.11.24 to get it in before publishing the next 0.64 today, but I see 0.64 also has a Microsoft.ChakraCore.ARM64 with a similar version number. Do these need to be in sync? I don't see a 1.11.24 package for Microsoft.ChakraCore.ARM64.

Ideally yes, they should be in sync,but the ChakraCore team refused to add the ARM64 binaries to their build pipeline so they need to be reached out to provide us with such binaries and we would need to package them ourselves.

**Review by NickGerleman — APPROVED** [review]

**Comment by jonthysell** [comment]
This CG alert is now showing up in 0.64 for publish, so I've updated the PR and set it to AutoMerge so we can publish the next 0.64 next week.

However we still won't have an update for the ARM64 package. @JunielKatarn Any chance we could get that package built and uploaded by then?

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
@jonthysell in case this does come up again, we don't use the ChakraCore package in RNW apart from development scenarios, so there shouldn't be user-facing security concerns here. Uwp will use system Chakra, and Office internally specifies its own NuGet packages for the desktop DLL. I think the only place in RNW we use this is for testing the desktop DLL.

**Pull request merged**
