### PR TITLE
Added Microsoft.ReactNative dependency on Mso

### PR DESCRIPTION
**Pull request by vmoroz**
In preparation for changing the ReactInstance management, I need to make sure that we can add Mso as a dependency to Microsoft.ReactNative project. My previous attempt failed due to CI loop failures. This PR has only a bare minimal set of changes to establish this dependency. Hopefully developers who are more familiar with CI loops could help me to resolve the build issues.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/3997)

### CODE REVIEW

**Comment by NickGerleman** [comment]
@vmoroz I think you may need to do some work to ensure your projects sources are included in our published npm package.

**Comment by jonthysell** [comment]
The errors are from the missing `debugAssertApi/debugAssertApi.h`. That file does not exist in your branch. Did you forget to add it to the commit?

**Comment by vmoroz** [comment]
I know about it... The question is what exactly I should do? If you know the answer, then I would appreciate the help!

---
In reply to: [580437104](https://github.com/microsoft/react-native-windows/pull/3997#issuecomment-580437104) [](ancestors = 580437104)

**Comment by vmoroz** [comment]
OK, I was about to send you a link to the file as it already exists in the repo, but it does not!!! The whole time I was looking for a wrong include path, but the issues was that the file somehow disappeared during previous merge in the react-native-windows repo... Ouch! Thank you!

---
In reply to: [580469522](https://github.com/microsoft/react-native-windows/pull/3997#issuecomment-580469522) [](ancestors = 580469522)

**Comment by vmoroz** [comment]
The issue was with the .gitignore that used to eliminate all folders that start with words debug and release. Thus, the debugAssertApi was excluded, while existing on my machine locally.

---
In reply to: [580474828](https://github.com/microsoft/react-native-windows/pull/3997#issuecomment-580474828) [](ancestors = 580474828,580469522)

**Comment by vmoroz** [comment]
Done!

---
In reply to: [351159826](https://github.com/microsoft/react-native-windows/pull/3997#issuecomment-351159826) [](ancestors = 351159826)

**Comment by NickGerleman** [comment]
@vmoroz Do you need to add the project as a dependency to more solutions? E.g. MyApp.sln (the cli template), the solutions in packages depending on Microsoft.ReactNative, Desktop and Universal.

CLI will still pass even if you don't add the dependency to the solution, since it relies on raw MSBuild, but Visual Studio won't actually build the project unless its part of the solutions. I.e. if Microsoft.ReactNative depends on Mso building something, Visual Studio will fail to build even if CI passes.

This gets a little bit hairy depending on how temporary the Mso project is, since we would need to change the cli template which is hard to reverse after people already run it.

**Comment by NickGerleman** [comment]
I'm not actually 100% sure if this is the same for vcxitems, but would you be willing to manually check that expected files are built when using the desktop or universal solution?

**Comment by vmoroz** [comment]
The issue is already solved. It was a bug in the .gitignore.

---
In reply to: [580489585](https://github.com/microsoft/react-native-windows/pull/3997#issuecomment-580489585) [](ancestors = 580489585)

**Pull request merged**
