### PR TITLE
Don't return an error if AsyncStorage is empty

### LINKED ISSUE #6428: Empty AsyncStorage.getAllKeys() behaviour on Windows isn't consistent with other platforms
## Environment

This bug reproduces on both 0.62.x and 0.63.x on Windows, I only will share 0.63 details here.

Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
`4.13.0`

2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 9.81 GB / 15.62 GB
  Binaries:
    Node: 14.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.7.30517.126 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.6
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create an app with the following code.
```javascript
import React from 'react';
import {
  SafeAreaView,
  Text,
  AsyncStorage,
  Button,
  StatusBar,
} from 'react-native';

const testAsyncStorage = () => {
  AsyncStorage.getAllKeys()
    .then(keys => {
      if (typeof keys === typeof []) {
        console.log("TEST SUCCESS, keys is expected", keys);
      } else {
        console.log("TEST FAILED, unexpected keys value (expected [])", keys)
      }
    })
    .catch(err => {
      console.log("TEST FAILED, unexpected error", err);
    })
}

const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <Text>Test AsyncStorage</Text>
        <Button onPress={() => testAsyncStorage()} title="Test"/>
      </SafeAreaView>
    </>
  );
};

export default App;
```
2. run it on macOS, iOS, Android & Windows. For windows, use react-native-windows 0.62 and 0.63.

3. Actual result
   * On macOS, iOS & Android, you see `TEST SUCCESS, keys is expected []` message in the console. Empty list is returned and no errors.
   * **On Windows, you see "Test failed, unexpected error Error" in the console.** Actually, from what I can see, it returns `undefined` and an error, so some libraries that ignore the error still crash on trying to enumerate this `undefined` value.

That breaks some 3rd party libraries (like AWS amplify, that expects empty keys in that scenario).

## Expected Results

The behaviour is the same across all 4 platforms. 
When AsyncStorage is empty `getAllKeys()` should return an empty list and no errors.

### PR DESCRIPTION
**Pull request by mandrigin**
fixes #6428

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6429)

### CODE REVIEW

**Review by NickGerleman — APPROVED** [review]
Looks good to me!

Think you may have discovered this already, but as a heads up, the builtin implementation of AsyncStorage on Windows is less correct/complete than the community module. There's been some recent discussion about whether we should try to unify the implementations if the builtin one will be around a while longer, but this is definitely an improvement.

**Comment by mandrigin** [comment]
@NickGerleman yeah, the point of this PR was to improve support of 3rd party libraries. In our code I should use the community module, but some libraries aren't updated in time and I really want to avoid supporting a lot of forks...

**Review by dannyvv — APPROVED** [review]

**Comment by dannyvv** [comment]
@mandrigin: Thank you for your contribution improving react-native-windows!

**Comment by mandrigin** [comment]
Thanks! @dannyvv would it be possible to backport it to 0.62 and 0.63?

**Comment by mandrigin** [comment]
@NickGerleman @dannyvv I've opened a PR for 0.63 with the same change: https://github.com/microsoft/react-native-windows/pull/6491

I'd really like to see it backported ;-)

**Pull request merged**
