### PR TITLE
[0.64] Replace __APPLE__ with __clang__ where applicable

### PR DESCRIPTION
**Pull request by JunielKatarn**
Backport of #9461

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9481)

### CODE REVIEW

**Review by Khalef1 — APPROVED** [review]

**Comment by JunielKatarn** [comment]
@NickGerleman we are still facing unrelated issues with the CI runs.

Can you please do an admin merge so the change is ready by tomorrow?

**Comment by NickGerleman** [comment]
cc @jonthysell for CI stability

**Comment by jonthysell** [comment]
64 has no CI.

**Comment by NickGerleman** [comment]
@jonthysell to clarify, I mean PR and tests, rather than the specific "CI pipeline". Is the 0.64 PR issue something on your radar?

**Comment by NickGerleman** [comment]
> we'll see what happens when it tries to publish.

It was published 6 days ago, as part of the automated Monday morning patch release. See https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.64.30

**Pull request merged**
