### PR TITLE
Update some packages*.json files after the WinAppSDK udpate

### PR DESCRIPTION
**Pull request by JesseCol**
## Description
I did a WinAppSDK update recently, there are some packages*.json files that I missed when doing that update. 

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
Without this change, the "e2e-test-app-fabric" doesn't build successfully.

### What
This change modifies some *.json files so the new version of WindowsAppSDK is the expected version.

I found and ran the script "NuGetRestoreForceEvaluateAllSolutions.ps1"

## Testing
cd packages\e2e-test-app-fabric
yarn windows --no-launch --no-deploy

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/14056)

### CODE REVIEW

**Comment by Yajur-Grover** [comment]
Looks like SampleAppFabric is also on the old WinAppSDK: https://github.com/microsoft/react-native-windows/blob/a9afb5fddac4fb8741bb27de14aa563ddb35c254/packages/sample-app-fabric/windows/SampleAppFabric/packages.lock.json#L85

**Comment by JesseCol** [comment]
> Looks like SampleAppFabric is also on the old WinAppSDK:
> 
> https://github.com/microsoft/react-native-windows/blob/a9afb5fddac4fb8741bb27de14aa563ddb35c254/packages/sample-app-fabric/windows/SampleAppFabric/packages.lock.json#L85

Thanks!  I've now found and ran the script "NuGetRestoreForceEvaluateAllSolutions.ps1" which does what we need.  I've verified that after this there are no references to the old version number (1.5.240227000).

**Review by Yajur-Grover — APPROVED** [review]

**Review by marlenecota — APPROVED** [review]

**Review by TatianaKapos — APPROVED** [review]
LGTM! Do we also need to backport this to 0.76?

**Comment by JesseCol** [comment]
> LGTM! Do we also need to backport this to 0.76?

Thanks for looking!  Yes, looks like we should backport to 0.76 because the first part of the WinAppSDK update is there.  Can you point me to instructions?

**Pull request merged**
