### PR TITLE
[0.75] Backport certificate fixes to unblock CI

### PR DESCRIPTION
**Pull request by jonthysell**
## Description

This PR cherry-picks the following certificate-related commits to unblock CI in 0.75:

https://github.com/microsoft/react-native-windows/commit/3a5ca66aab21739e168bd7d236de2f420bf3090c
https://github.com/microsoft/react-native-windows/commit/3534af4fdfb0e5b73b1ecf6b3da6c48f129d008b
https://github.com/microsoft/react-native-windows/commit/5fad854368beb3bee4a1526bb7fc97ad0f7bf8ad
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/14057)

### CODE REVIEW

**Review by marlenecota — APPROVED** [review]

**Review by marlenecota — APPROVED** [review]

**Comment by jonthysell** [comment]
I also threw in the workaround for this bug: https://github.com/callstack/react-native-builder-bob/issues/674

**Pull request merged**
