### PR TITLE
Prevent rnbot from tracking microsoft/react-native

### PR DESCRIPTION
**Pull request by NickGerleman**
We will no longer be updating against microsoft/react-native, and it will be
some time until trying to keep up to date with facebook's master. Remove
evergreen related scripts/tasks for now. We may eventually want
something similar to track facebook/master, but will still have this in
source history if we want to create a modified version of it.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/3972)

### CODE REVIEW

**Comment by NickGerleman** [comment]
@acoates-ms thoughts on deleting the scripts vs just removing the task? I would personally bias towards removing the script, just because I could see a world where we do something different for facebook/master and this lives forever, unused and containing microsoft/react-native logic.

**Comment by acoates-ms** [comment]
There is no need to delete the scripts until we have actually stopped using MS/RN.   We can turn off the build that runs these externally without having to remove the scripts.

I'd also like to keep it in place right now since until we are off MS/RN, we need to keep this to be able to get updates end to end into sdx-platform / devmain.

Basically, lets not do this change until we are no longer using MS/RN.

**Comment by NickGerleman** [comment]
I can definitely hold off on merging this. Is the concern with sdx-platform about mismatched peer deoendencies?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by acoates-ms** [comment]
Yeah, I guess the other option is to ensure that we get the broader peerdependency before we do it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by NickGerleman** [comment]
@acoates-ms I think this is ready to go in now.

**Pull request merged**
