### PR TITLE
Bump Microsoft.Windows.CppWinRT to 2.0.230706.1

### PR DESCRIPTION
**Pull request by jonthysell**
## Description

This PR updates RNW to default version of `Microsoft.Windows.CppWinRT` to `2.0.230706.1`, the same version used by the VS 2022's WinAppSDK new app template.

This PR also makes sure that we use the 64bit toolset by default, because CppWinRT projectd require lots of resources to build, and compiling some configurations with the new version (namely for us, ARM64 new arch) requires more RAM than the 32-bit tools (compiler and linker) can access.

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
We haven't update CppWinRT in several years, and as we build towards the new architecture on top of WinAppSDK we don't want to be using an outdated configuration.

### What
See above.

## Screenshots
N/A

## Testing
N/A

_Optional_: Describe the tests that you ran locally to verify your changes.

## Changelog
Should this change be included in the release notes: _yes_

Projects now depend on Microsoft.Windows.CppWinRT >= 2.0.230706.1

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/12798)

### CODE REVIEW

**Comment by jonthysell** [comment]
Hmm, this happens when building release: `Component too big for incremental LTCG with 32-bit toolset, build without incremental LTCG; Consider switching to 64-bit toolset.`

**Comment by jonthysell** [comment]
This PR should work once #12849 gets in and I can rebase this.

**Review by marlenecota — APPROVED** [review]

**Pull request merged**
