### PR TITLE
Add more WPF ScrollView supported props

### PR DESCRIPTION
**Pull request by Kudo**
props to support:

- horizontal
- contentOffset

Also fix `scrollEnabled={false}` will hide scroll bar issue.

### CODE REVIEW

**Comment by rozele** [comment]
@matthargett or @kevinvangelder, is this good to merge?

**Comment by Kudo** [comment]
I've fixed the problem that set `scrollEnabled={false}` will hide scrollbar.
Please take a look. Thank you.

**Comment by kevinvangelder** [comment]
@rozele Yep, please merge.

**Comment by Kudo** [comment]
Just rebase to latest upstream

**Pull request merged**
