### PR TITLE
Readme: fix macOS and website naming

### PR DESCRIPTION
**Pull request by Simek**
Just a small & simple PR to keep website and platform naming consistent.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6197)

### CODE REVIEW

**Review by alloy — APPROVED** [review]
Looks good to me, this is indeed the correct marketing name nowadays. However, I’ll defer to @harinikmsft @kikisaints to check if there’s any reason to use ‘Mac’.

**Comment by asklar** [comment]
:shipit:

**Comment by dannyvv** [comment]
@Simek: our apologies this hasn't merge yet. We are having some technical difficulties running the PR validation per [vs dev community](https://developercommunity.visualstudio.com/content/problem/1210382/azure-devops-fails-to-trigger-on-github-commit.html) I'll keep an eye out and merge it as soon as it has been sovled.

Thank you for contribution!

**Comment by dannyvv** [comment]
@Simek: I merged your PR. Thank you again for improving react-native-windows.

**Pull request merged**
