### PR TITLE
Update to folly 2022.11.07

### PR DESCRIPTION
**Pull request by acoates-ms**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10881)

### CODE REVIEW

**Comment by mganandraj** [comment]
>   

I'm curious where we are with these PRs .. Do we still need these patches ?

---
Refers to: vnext/Folly/Folly.vcxproj:322 in 612b073. [](commit_id = 612b073889302e5361082203109447d1ebe6cf19, deletion_comment = False)

**Review by mganandraj — APPROVED** [review]
:shipit:

**Comment by acoates-ms** [comment]
> > 
> 
> I'm curious where we are with these PRs .. Do we still need these patches ?
> 
> Refers to: vnext/Folly/Folly.vcxproj:322 in [612b073](https://github.com/microsoft/react-native-windows/commit/612b073889302e5361082203109447d1ebe6cf19). [](commit_id = [612b073](https://github.com/microsoft/react-native-windows/commit/612b073889302e5361082203109447d1ebe6cf19), deletion_comment = False)

Once Office is full on the ABI code path, we will no longer need most/all of these patches.  They are mostly to prevent exported DATA blocks from the dll. -- Once we get on the ABI we should be able to remove folly from the dll boundary.

**Comment by mganandraj** [comment]
> 

And convert all CxxModules to non-Windows

**Review by vmoroz — APPROVED** [review]

**Pull request merged**
