### PR TITLE
Move contributor docs to website

### LINKED ISSUE #4265: Onboarding for RNW is steep
At the very least we need instructions (in the form of a .md file maybe), for a new person trying to build with RNW (not just building an app). Specifically: what does each folder under vNext refer to? There's Microsoft.ReactNative, ReactUWP, but there's also ReactWindowsCore...

### PR DESCRIPTION
**Pull request by asklar**
In tandem with https://github.com/microsoft/react-native-windows-samples/pull/91 this removes the now stale contributor docs from the repo and points folks to the website.

Fixes #4265 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4819)

### CODE REVIEW

**Comment by NickGerleman** [comment]
What's the motivation for moving documentation for doing development inside the repo to outside of the repo? We have a bunch of adhoc documentation that developers are writing, and putting them external will discourage that and fragment what we have.

**Comment by NickGerleman** [comment]
Contribution guidelines seem fine, but something like project structure of the repo seems like a pain to have outside of the repo.

**Comment by asklar** [comment]
> Contribution guidelines seem fine, but something like project structure of the repo or how to run internal tools seems like a pain to have outside of the repo.

This aligns with the rest of the documentation which has already moved outside of the repo. The contributor docs in the repo had gotten out of sync with some of the stuff in the website so this is removing the stale copy.

**Comment by acoates-ms** [comment]
This does seem counter intuitive to me.  The standard practice for repos is that you have the developer /contribution docs in GitHub, and you a separate website for consumers of the project.

This is how core react-native works, and most other GitHub projects that I've seen.  I wouldn't want the contribution docs to be in the same place as the user docs.  They are targeting different audiences and having results for one show up when someone is searching for the other would be unhelpful to both user groups.

**Comment by asklar** [comment]
> Holding until we have time to come to a consensus on where we want this documentation.
> 
> The tasks linked indicated that the application developer documents should move to the website. There was nothing in there that said all the repo documents should move out the repo.

@acoates-ms @NickGerleman 
Actually the task was filed (by me) with the contributor/team member in mind, not specific to app developers (see my comment in the task that says "not just building an app"). 
We've started to see external developers having trouble finding docs about e.g. testing changes to RNW. The website already includes some of this info (like building etc.), and the files in the repo have less up-to-date versions of that, which complicates things. Moreover you don't get a rendered view out of markdown, and it makes navigation and discoverability a lot harder. We discussed this on a thread with PM and I believe we had consensus.

**Comment by NickGerleman** [comment]
From my perspective, moving to a separate repo goes pretty against discoverability. I would have no expectation working in this repo to go to an external website to try to figure out how to find things.

If you want to make navigation easier you could consider putting documentation into this repos wiki. We already have documentation there, along with in other files in the repo not touched by this.

Not doubting your intent here, but contributors will look for documentation in-repo in my experience. If you want to help discoverability, I'd consider using the wiki, but judging by the fact that since this PR was opened there have already been conflicts, in repo docs is something developers expect. I've personally never tried to look for anything on the docs site when starting in here. 

My vote would be to move things to the repo wiki and link to that if you want. This is a pattern I've seen in other repos that helps your concern about the docs folder without causing fragmentation or discoverability issues.

**Comment by asklar** [comment]
abandoning since it looks like we are not in agreement on the strategy.

**Pull request closed without merging**
