### PR TITLE
Fix AppState Module

### LINKED ISSUE #6482: AppState.currentState is always returning undefined in RNW 0.63.6
My team is trying to upgrade to RNW 0.63, and I've noticed what looks like a regression in a component that relies on AppState from react-native, where AppState.currentState is always returning undefined.

Digging into the code, it looks like a possible regression from updating \node_modules\react-native-windows\Microsoft.ReactNative\Modules\AppStateModule.cpp - GetCurrentAppState returns a plain string, either "active" or "background". However, node_modules\react-native-windows\Libraries\AppState\AppState.js attempts to compare its currentState value to appStateData.app_state, which is not a valid field to reference.

### PR DESCRIPTION
**Pull request by acoates-ms**
When I moved AppState to a turbomodule I broke one of the events on AppState.  This fixes it.  Verified in the RNTester page for AppState.

Fixes #6482 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6500)

### CODE REVIEW

**Review by asklar — APPROVED** [review]

**Comment by NickGerleman** [comment]
Does the AppStateDidChange call need a similar update?

**Comment by NickGerleman** [comment]
Consider adding a quick integration test for this, since it should be pretty simple.

**Review by dannyvv — APPROVED** [review]

**Comment by NickGerleman** [comment]
E2ETest is failing due to the WinAppDriver upgrade. Working on a workaround until we have a moment to make things work correctly with 1.2.

**Comment by NickGerleman** [comment]
The E2ETest CI issue should be fixed if you pull master

**Pull request merged**
