### PR TITLE
[0.63] Make BaseWebSocketResource destructor noexcept #7417

### PR DESCRIPTION
**Pull request by JunielKatarn**
Backport of #7415 and #7319.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7418)

### CODE REVIEW

**Review by hansenyy — APPROVED** [review]

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
@asklar looks like the ReactUwpTestApp cert issue needs to be fixed in 0.63

**Comment by NickGerleman** [comment]
It looks like this also needs the UT fix that was ported to 0.64 but not 0.63. I think that was also @asklar ?

**Comment by asklar** [comment]
Yes, we need the change in 63. Tagging @AgneLukoseviciute who's taking on the "Unblocker of CIs" role :)

**Comment by AgneLukoseviciute** [comment]
Yep, taking a look now. Bear with me as I learn, might take me a second longer than Alex 😄 Should have it fixed soon.

**Comment by asklar** [comment]
Superseded by #7428. Closing this, @JunielKatarn

**Pull request closed without merging**
