### PR TITLE
Documentation migration, updates, and file removals

### PR DESCRIPTION
**Pull request by kikisaints**
As per our email thread on the doc migration and updates, the changes are as follows:

- Removed the blogs folder (this is now only in [react-native-windows-samples](https://github.com/microsoft/react-native-windows-samples))
- Moved the docs folder from the vnext/docs location to the root
- Removed/kept the following markdown files under the docs folder:
image
- Renamed all upper-case/camel-case file names to lower-case with dashes
- Updated the README links to reflect the folder structure rearrangement and doc file renames

**This work is related to** [this PR in the react-native-windows-samples](https://github.com/microsoft/react-native-windows-samples/pull/14) repo where all the removed documentation from the docs folder her in the main repo went to live.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/3974)

### CODE REVIEW

**Comment by kikisaints** [comment]
@chrisglein  These are the changes to the docs and blogs we spoke about on an internal thread. Not sure why files I've removed in this PR are causing conflicts - can you advise?

**Comment by chrisglein** [comment]
> @chrisglein Chris Glein FTE These are the changes to the docs and blogs we spoke about on an internal thread. Not sure why files I've removed in this PR are causing conflicts - can you advise?

I'm tied up the next 2 days and then OOF for 2 weeks after. @marlenecota can you help unblock @kikisaints?

**Comment by marlenecota** [comment]
> > @chrisglein Chris Glein FTE These are the changes to the docs and blogs we spoke about on an internal thread. Not sure why files I've removed in this PR are causing conflicts - can you advise?
> 
> I'm tied up the next 2 days and then OOF for 2 weeks after. @marlenecota can you help unblock @kikisaints?

@kikisaints You need to sync your repro. Those 3 files showing merge conflicts were modified in master after you created your branch.

**Comment by kikisaints** [comment]
@marlenecota  I've update the BuildingRNW.md to match these changes. However the other two should be removed and not updated.

@kaiguo and @ddalp can you two instead update the native modules information [over here](https://github.com/microsoft/react-native-windows-samples/tree/master/docs)?

I've copied over the changes made to both native modules files over in the website repo, but since they are getting removed from this repo I'd like further changes to go there.

**Comment by kikisaints** [comment]
@marlenecota and @kmelmon can either/both of you two check out this PR? I'd like to have it merged so I don't have to keep updating duplicate information between the RNW website and this repo.

Thanks!

**Pull request merged**
