### PR TITLE
Fix padding for Text views.

### PR DESCRIPTION
**Pull request by randy-flynn**
When padding was applied to a Text view it was essentially added twice - once in the native control and once in yoga layout.

This change adds the ability for a view to say it implements the padding so the yoga layout can avoid doing it. This is expressed in the ShadowNode, so a custom node is required.

Only the Text view was given this ability for now, but the Control base view manager will need to be looked at for this as well.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2200)

### CODE REVIEW

**Comment by acoates-ms** [comment]
Where does the padding get applied to the XAML element now?  I only see the path that updates the yoga layout.

**Comment by randy-flynn** [comment]
> Where does the padding get applied to the XAML element now?  I only see the path that updates the yoga layout.

This is still in the same place in the TextViewManager and is unchanged. We apply it during UpdateProperties as usual.

**Comment by acoates-ms** [comment]
Oh ok, I found it.  It does look like the same change should probably be applied to control too.

**Comment by randy-flynn** [comment]
a /azp run

**Pull request merged**
