### PR TITLE
Fixes registration name for TextInput onScroll

### LINKED ISSUE #7258: TextInput does not fire `onScroll` events
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Modified the RNTester TextInput sample: https://github.com/rozele/react-native-windows/commit/f15854128d10eeaab6284aa8c090e0da69fe8064
2. Opened RNTester > TextInput example > Attributed Text example
3. Added multiple lines of text until the TextBox view changes

## Expected Results

I expect that an onScroll event would fire, update the state, and render text that gives the y-offset of the TextBox view.

## Snack, code example, screenshot, or link to a repository:

Here's a branch with the repro: https://github.com/rozele/react-native-windows/commit/f15854128d10eeaab6284aa8c090e0da69fe8064

Here's a video repro:

https://user-images.githubusercontent.com/1106239/109832549-72107680-7c0e-11eb-92bf-61f1cb89c98e.mp4

### PR DESCRIPTION
**Pull request by rozele**
Previously, scroll events on TextInput mapped to `onOnScroll`. The
correct event name is `onScroll`. This fixes that.

Fixes #7258

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7259)

### CODE REVIEW

**Comment by rozele** [comment]
Here's the repro example used: https://github.com/rozele/react-native-windows/commit/f15854128d10eeaab6284aa8c090e0da69fe8064

Here's a video of it working correctly:

https://user-images.githubusercontent.com/1106239/109833204-109cd780-7c0f-11eb-8bda-7556da978ff8.mp4

**Review by asklar — APPROVED** [review]
nice catch. It would be good to add to the e2e test if you have the cycles.
IIRC we had a similar typo/wrong event name somewhere else recently... I wish we could use "known constants" for these things as they are a fragile part of the system interface between JS and native

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
> I wish we could use "known constants" for these things as they are a fragile part of the system interface between JS and native

This should all be codegen'd for Fabric I think.

**Review by rectified95 — APPROVED** [review]

**Pull request merged**
