### PR TITLE
Revert Usage of PackageReference for C++ Projects 

### PR DESCRIPTION
**Pull request by NickGerleman**
This reverts #8195, since it looks like it added some pretty critical regressions to user scenarios.

The CLI relies on a system installed `nuget.exe` to restore, This causes the CLI to crash when the user has not separately installed `nuget.exe`. It also may call an incompatible version of `nuget.exe`, since the installed system version may not be compatible. This was not picked up in CI, since we have steps to manage the NuGet binary on the machine, for us to manually restore.

First restore is also failing locally when using Visual Studio. The error pointed to a GitHub issue around C++ PackageReference usage in VS. NuGet/Home#11392. The inability to restore on first usage is a known issue, that the VS team is not investing in, claiming they do not officially support C++ PackageReference.

On my own dev machine, this led to errors both trying to restore via VS, or our CLI. This is a fairly serious regression, that may block work of other engineers, and prevent us from shipping the current branch.

Creating this PR to revert, unless we think we can forward-fix these issues in a short-term timeframe.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9301)

### CODE REVIEW

**Comment by NickGerleman** [comment]
@JunielKatarn re "nuget.exe" from CLI, we had a solution a couple branches ago for this issue. https://github.com/microsoft/react-native-windows/pull/6548

We controlled the NuGet version from the CLI, and just redistributed the executable.

This was after some bugs hit customers, of mismatched NuGet versions. That's what transitioned us at the time to use MSBuild restore, even for packages.config.

**Comment by JunielKatarn** [comment]
The amount of work to maintain this branch in a mergeable state is non-trivial.
 
Can we look at alternatives as the discussed implicit NuGet installation?

**Review by JunielKatarn — CHANGES_REQUESTED** [review]
As discussed offline, we have alternatives for most failing scenarios, pure VS restore/build being the exception.

I think we should have a broader discussion on the trade-off between running `msbuild /t:restore` manually and never being able to benefit from `PackageReference`.

**Comment by NickGerleman** [comment]
Talking more offline, there are a couple of ideas for both VS restore, and `run-windows` NuGet restore. The point where I think we would want to revert, is if we see additional RNW contributors blocked by build issues.

**Review by NikoAri — APPROVED** [review]
:shipit:

**Comment by NickGerleman** [comment]
Closing, since @JunielKatarn is wanting to forward fix.

**Pull request closed without merging**
