### PR TITLE
Fix error for failing autolink check

### PR DESCRIPTION
**Pull request by jonthysell**
The autolinking check part of an app's build can fail if the autolinked
files are out of date, but the result should be an actionable warning,
not an actual build failure.

This address part of #6761.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6763)

### CODE REVIEW

**Comment by asklar** [comment]
can you clarify why it shouldn't fail? Building the wrong files seems wrong... 
Ideally one can build the app from either VS or the CLI, without requiring building in the CLI first.

**Review by dannyvv — APPROVED** [review]

**Comment by jonthysell** [comment]
> can you clarify why it shouldn't fail? Building the wrong files seems wrong...
> Ideally one can build the app from either VS or the CLI, without requiring building in the CLI first.

The design was such that VS users are free to operate without being "forced" to deal with autolinking. If their code compiles, and they're happy with the result, they don't have to run autolinking and we don't run it automatically and change their files for them. If it builds but is not working as expected, the warning has the command for them to run.

If they're really anti-autolinking, they can disable the check altogether if they're willing to edit their project with the property (or create a props file), though I don't think we really advertise that option.

We could take a harder stance and make it block the build (which is what it's doing now) but then we still need to:
* Add the command back to the error message so they can fix it
* Make sure the telemetry properly sanitizes the message to remove the solution and project names I just added

I'm fine with treating autolinking as a necessary (i.e. potentially blocking) part of our tooling, but that was not the consensus at the time.

**Comment by jonthysell** [comment]
I'm fine leaving this PR unmerged until we decide.

**Comment by asklar** [comment]
@jonthysell thanks for the explanation :) I think it would make more sense to fail as warnings are easy to ignore, "if it builds, it ships!" :-D  and then people end up chasing a bug about why their project isn't working as expected. If nobody is blocked on this, maybe get Chris's opinion once he's back?
Also note that I have a PR out to change the way we collect telemetry so that we never log an "on screen" message and instead only log known values, so that should take care of the issue of logging the autolink command (which would have been taken care of even before that PR, by virtue of the path sanitization logic I had already added, anyway), I'd love to get your eyes on it too.

**Comment by asklar** [comment]
here's the PR I was referring to: https://github.com/microsoft/react-native-windows/pull/6664

**Comment by NickGerleman** [comment]
Is this still needed with the line ending normalization fixes?

**Comment by jonthysell** [comment]
> Is this still needed with the line ending normalization fixes?

Yes, this is a separate issue - should a failing autolink check just throw a warning or an error? We went with warning to not impeded VS-focused devs who didn't want the check to block them building, even if the files were potentially "wrong".

**Pull request closed without merging**
