### PR TITLE
Moving C# implementation into RNWCS sub-folder

### PR DESCRIPTION
**Pull request by jonthysell**
* Moved most files for RNW C# from the root into a RNWCS sub-folder
* Updates to paths of remaining root documentation files (readme, releases, contributing)
* Updated appveyor to make sure the build still works
* Added CODEOWNERS
* Fixed package.json so RNTester runs again
* Issues #2183, #2199

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2190)

### CODE REVIEW

**Comment by jonthysell** [comment]
@acoates-ms, @rozele - is there anything specific I should check to make sure this is working? I built myself, appveyor is passing, but it feels too easy...

**Comment by acoates-ms** [comment]
Did you run through the steps in https://github.com/Microsoft/react-native-windows/blob/master/CONTRIBUTING.md ?  Basically manually run the tests and run RNTester

**Comment by jonthysell** [comment]
Tests are working, having trouble with RNTester, investigating....

**Comment by jonthysell** [comment]
Ok, I've verified the tests and RNTester now all run as expected.

**Pull request merged**
