### PR TITLE
Make ScrollView and ActivityIndicator not focusable by default

### PR DESCRIPTION
**Pull request by lyahdav**
## Description

Make ScrollView and ActivityIndicator not focusable by default as this was an inadvertent change made at some point after RNW 0.68.

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
In #11032 there was a change which made all ControlViewManager subclasses focusable by default. ScrollViewManager and ActivityIndicatorViewManager are two of those view managers, but both of those should not be focusable by default. Previously (e.g. in RNW 0.68) ScrollView and ActivityIndicator were not focusable by default.

### What
Make ScrollView and ActivityIndicator not focusable by default.

## Screenshots
Before all ScrollView components have a tab stop by default:

https://github.com/microsoft/react-native-windows/assets/359157/6f975c85-58ac-4358-ae8a-b37d041d238e

Before all ActivityIndicator components have a tab stop by default (note there's no focus ring but you can tell its focusing since the ScrollView is scrolling when focusing ActivityIndicators below the fold):

https://github.com/microsoft/react-native-windows/assets/359157/25b40a13-2a19-46d5-b2e3-259a674b6816

After (and in RNW 0.68) all ScrollView components don't have a tab stop by default:

https://github.com/microsoft/react-native-windows/assets/359157/a1c11fa8-0807-48cf-9a70-2a54c73a3608

After (and in RNW 0.68) all ActivityIndicator components don't have a tab stop by default:

https://github.com/microsoft/react-native-windows/assets/359157/0e9c78a4-a3ba-4fc6-9c9e-05da83b9d11f

## Testing
Tab through ScrollView and ActivityIndicator components. Ensure they don't have a tab stop by default.

CC @chiaramooney since you worked on #11032

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/11675)

### CODE REVIEW

**Comment by lyahdav** [comment]
I plan to update this based on discussion offline, please don't review yet

**Comment by chiaramooney** [comment]
Ok here is where the "focusable by default" is set [here](https://github.com/microsoft/react-native-windows/blob/729b78ea58c15d53b889009975128310f4a13608/vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h#LL134C7-L134C7). It's actually set for all views in shadownoebase and then we undo that behavior for the viewviewmanager [here](https://github.com/microsoft/react-native-windows/blob/729b78ea58c15d53b889009975128310f4a13608/vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp#L50). I don't have a strong pref between opt-in to focusable or focusable by default. Tallying up which side has fewer controls seems to make sense to me. Let me know if you run into issues fixing ActivityIndicator.

**Comment by lyahdav** [comment]
OK, I just updated this PR to address ActivityIndicator as well. It's ready for review.

**Review by chiaramooney — APPROVED** [review]

**Comment by chiaramooney** [comment]
@lyahdav Let's backport this into previous versions as well!

**Comment by lyahdav** [comment]
@chiaramooney Which versions? And to backport I assume I create a PR off the stable branch, e.g. 0.71-stable?

**Comment by chiaramooney** [comment]
@lyahdav Sorry was OOF. Yes exactly! And repeat for whichever versions you need the change added to.

**Comment by lyahdav** [comment]
For posterity, this issue existed on 0.71 branch as well because the original PR was backported to 0.71 in #https://github.com/microsoft/react-native-windows/pull/11153.

**Pull request merged**
