### PR TITLE
Adjust Prettier Config to Match react-native

### LINKED ISSUE #9217: Remove Patch for Virtualized List Tests
From https://github.com/microsoft/react-native-windows/pull/9214/, 

FillRateHelper-test.js
FlatList-test.js
SectionList-test.js
ViewabilityHelper-test.js
VirtualizedList-test.js
VirtualizedSectionList-tests.js
VirtualizeUtils-test.js

have incorrect prettier formatting. Forked files in order to restore `yarn validate-overrides` build until files are updated.

### PR DESCRIPTION
**Pull request by chiaramooney**
### Type of Change
_Erase all that don't apply._
- Bug fix (non-breaking change which fixes an issue)

### Why
Adjust prettier arrowParens configuration to match react-native. Should be set to 'avoid'. Remove forked files in List testing, now that upstream has resolved the linting errors in these files. 

Resolves #9217

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9682)

### CODE REVIEW

**Review by jonthysell — APPROVED** [review]

**Comment by NickGerleman** [comment]
I think this change actually removes the coverage. The override was originally set to be "copies" files from the RN repository. This is because the files are normally not part of the published npm package.

Could you check if the tests are still run as part of "Node Tests"?

**Comment by chiaramooney** [comment]
Turns out the original files still have a few prettier errors. Making a PR upstream now. Closing PR until they fix those.

**Comment by chiaramooney** [comment]
Migrating to New PR because reset was needed.

**Pull request closed without merging**
