### PR TITLE
Update version of ChakraCore

### PR DESCRIPTION
**Pull request by acoates-ms**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2334)

### CODE REVIEW

**Comment by akrantz** [comment]
@acoates-ms  1.11.8 is the latest now.

**Comment by acoates-ms** [comment]
Is it public?  Last time I checked 1.11.7 was the latest public version? -- This matches the versions we are using in RNWCPP and RNWCS.

**Comment by akrantz** [comment]
Yes, it is. It's the update made on Patch Tuesday with the security fixes. "Manage Nuget for Solution" in Visual Studio shows it on the Updates tab.

**Comment by akrantz** [comment]
https://github.com/Microsoft/ChakraCore/releases

**Pull request merged**
