### PR TITLE
Integrate May 5th RN nightly build.

### LINKED ISSUE #7591: Remove fork of MapBufferBuilder.cpp
Build break coming from Core. PR to fix this: https://github.com/facebook/react-native/pull/31363

### PR DESCRIPTION
**Pull request by rectified95**
Few changes this time. Commits https://github.com/facebook/react-native/compare/7e05480cc...438a4cf59
- removed fork of `MapBufferBuilder.cpp` - Closes #7591
- `getViewManagerConfig()` got deprecated
- filed https://github.com/microsoft/react-native-windows/issues/7856 about new ToggleButton accessibility role.
- filed https://github.com/microsoft/react-native-windows/issues/7929 to track re-enabling a measurement test for Switch pending upstream fix ingestion  

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7857)

### CODE REVIEW

**Comment by NickGerleman** [comment]
Looks like a new switch JS component was shipped. Integration tests are having trouble measuring it, but does it work correctly manually?

**Comment by asklar** [comment]
anyone have more context on getViewManagerConfig() being deprecated / should we call this out in changelog?

**Comment by NickGerleman** [comment]
Skimming through PRs, I think these are the ones we probably want to validate manually:

Note that we do not care much about https://github.com/facebook/react-native/commit/2b67631210070de0c07b21c69fb9d0ccd9e9fcba (bumping the hermes-engine npm package) since we control that for Windows via NuGet package version.

Picking these is more of an art than a science. It helps when you learn what breaks we see. Some of what we care about here ends up being:

- Anything at the RNW RN Core boundary
  - E.g. anything directly interacting with a native component
- Platform-specific instance management code (e.g. Instance, NativeToJSBridge, JSIExecutor)
- JS Engine or JSI changes
  - Our implementations live in other repos
  - And, we think they kind of have to unless we impacted RNW dev experience
- JS logic around desktop-specific behavior
  - E.g. anything we forked to add mouse support
- OSS packages
  - E.g. CLI, Metro
- Code-generation frontend
  - Backend (e.g. Android) we don't much care about
- RNTester
  - Mostly just custom examples at this point
- New usages of unimplemented APIs
  - E.g. if a property becomes needed for more regular operation

**Comment by NickGerleman** [comment]
cc @HeyImChris who will also have some experience from RN macOS integration. Have anything to add to the above list that you've encountered for macOS?

**Comment by asklar** [comment]
meta: curious about how RN breaking changes like these are marked; if they're not, it would be good to establish a process to do so : )

**Comment by NickGerleman** [comment]
> meta: curious about how RN breaking changes like these are marked; if they're not, it would be good to establish a process to do so : )

They aren't really breaking to the general public, so they usually aren't marked in my experience. We are working at what are essentially private API boundaries. There are definitely cases where we can make a cleaner, more public or platform-neutral boundary in upstream code (or push that new changes do that 😉).

**Review by dannyvv — APPROVED** [review]

**Comment by NickGerleman** [comment]
@TheSavior I’ve gotten the take that FB internal also has some custom platforms. Are there any tags/labels on internal stacks which alter the paper view manager boundary?

**Comment by TheSavior** [comment]
I'm not sure what you mean, can you elaborate?

For the new Switch component, one of the work streams on our team right now is to make React Native concurrent mode compatible. This has involved rewriting a lot of our components. We have been A/B testing those rewrites in prod to verify neutral metrics before we replace the old implementation.

**Comment by NickGerleman** [comment]
If an engineer changes a native component, do they ensure compat with React VR, or other platforms that are not Android/iOS?

The meta is I think finding way to create signal for changes which requires attention of anyone with native implementations of stock components.

**Comment by TheSavior** [comment]
Ah. It depends, but we aren't in that ideal state. The group working on the architecture don't currently focus on compact for other platforms today. They are working on parity and performance of the new architecture vs the legacy architecture. While that group doesn't block their work on other platforms having implementations already, they *do* make sure, as best they can, that their approaches and boundaries *could* be implemented for the other platforms.

For the group working on the core components, they actively design their APIs with the desktop group, although the implementations start on mobile because the other platforms are downstream forks (like microsoft's GitHub repos)

**Comment by NickGerleman** [comment]
Fix for the test is in https://github.com/facebook/react-native/pull/31629

For now you can feel free to skip the test if we will integrate this soon, and everything else is working.

**Pull request merged**
