### PR TITLE
[0.62] Enable integer-type native runtime settings.

### PR DESCRIPTION
**Pull request by JunielKatarn**
Backport of #5669

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5712)

### CODE REVIEW

**Comment by NickGerleman** [comment]
Going to merge this in now to batch it with another change going into a new 0.62 version.

**Comment by JunielKatarn** [comment]
Thanks! I don’t know what was blocking the automerge, since the last validation run was successful.

**Comment by NickGerleman** [comment]
@JunielKatarn There's a branch policy on stable branches that requires CI run on the latest commit in the branch (guessing we wanted to be extra cautious?). ACoates checked in a separate change to bump the version of Rex used for react-native-win32, so that invalidated CI results here. GitHub has a button you can click to automatically pull master when this happens, but only the author can click the button to do it. Since the last commit doesn't intersect at all with this, I just merged this in.

**Pull request merged**
