### PR TITLE
Fix nuget packages path

### PR DESCRIPTION
**Pull request by marlenecota**
Fix for #2312 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/2582)

### CODE REVIEW

**Comment by stecrain** [comment]
@marlenecota What was the issue with using solutionDir?

This change broke my setup, packages were downloading next to my solution in a packages folder.

Now it is looking for boost in node_modules\react-native-windows\packages\

**Comment by stecrain** [comment]
Fixed my issue by adding a nunget.config for my solution and specifying ..\node_modules\react-native-windows\packages as the repositoryPath

**Comment by acoates-ms** [comment]
We should make sure that the default cli does the right thing here if this is the solution we decide on.

**Comment by kmelmon** [comment]
@marlenecota please circle back with stephen to understand his scenario.  Is there another solution here?

**Comment by stecrain** [comment]
I might be reading the original issue incorrectly. 
But it seems like this might also be solved by deleting this file 
https://github.com/microsoft/react-native-windows/blob/master/vnext/NuGet.Config
and changing these back to SolutionDir.

I believe the nuget.config I linked is causing the packages to be restored in a non-default location. then this PR fixes the references in the projects to look at the overridden package install location.

So for my local workaround I added a similar nuget.config instructing nuget to place the packages in node_modules\react-native-windows\packages
It feels a little un-natural though.

I prefer just deleting the nuget.config and allowing the packages to be restored to a directory next to the solution file regardless of which solution file (ex the samples in the repo, and for my solution file which consumes these projects)

**Comment by stecrain** [comment]
Ryan on my team confirmed that the default cli produces a broken build after these changes.
We are planning to submit a PR which deletes the nuget.config linked above and switches these back to SolutionDir after we verify that it works for both scenarios. (project created from cli and running solutions in the repo)

**Comment by kmelmon** [comment]
Thanks everyone for jumping on this and fixing it!

**Pull request merged**
