### PR TITLE
Keep Templates in react-native-windows Package

### LINKED ISSUE #5884: Move CLI template files back to vnext
Currently, if you want to test changes to the CLI template app, it is a bit complicated and "unnatural".  See description below.

This task is tracking moving the CLI template app files back into the vnext directory, as it will remove the complication and make it easier to test changes to it.  Such changes happen fairly often so this has pretty high value.

---------------------------------------------

Details from email thread:

Nick says:
Got it. I only tested dev experience using --useDevMode / yarn link instead of file versions, so it looks like I missed that scenario.

I would have no issues with moving the template files specifically back into the react-native-windows package if that makes things easier. That's actually the pattern Core follows, where the CLI is in a separate package but there's a root level template directory in react-native https://github.com/facebook/react-native/tree/master/template

Using a file version instead of linking would still potentially pull outdated packages, but would have new template files. 

Jon says:
So you can make changes to the cli JS code, then use node to test it locally.
 
You can make changes to the init JS code, then use node to test it locally.
 
You can specify to use your local rnw when calling init.
 
But if you want to change the actual new app template files and test them, you have to use yarn link/unlink.
 
Before everything moved, a single parameter to the init script (--version file:path/to/vnext) supported testing the entire stack. No ambiguity over where things came from.

Jon says:
Since the template files are included in the cli package, using react-native-windows-init (either via npx or by calling the script locally with node) will still always download the template files from the published cli package.
 
So you can’t actually make template file changes and then try them out locally.
 
npx react-native-windows-init --version path\to\vnext will make sure you have the local version of what’s in vnext, but again, it will get the template files from the published cli package. 
 
The only way I got it to work was to use the yarn link/unlink stuff, but then you have to make sure that you remember that you linked your app repo to your local rnw repo, where-as before since it was actual file copies you could move with your local repo without worrying that the app repo was going to get busted.

### PR DESCRIPTION
**Pull request by NickGerleman**
Fixes #5884

Testing new app creation with `react-native-windows-init` can be done using `--useDevMode` and `yarn link`, or can be done by pointing `react-native-windows-init` to a fille-path. The former works by symlinking to the monorepo, and the latter copies the single package.

The latter workflow will not pick up changes to packages outside of react-native-windows. This includes template files that were moved outside the package.

This change moves template files back into react-native-windows to ease that workflow, but keeps the CLI as a separate package to avoid previous issues of intermingled dependencies, duplicated build logic, etc. We keep the templates in a top-level `template` directory, similar to what is done by react-native core. https://github.com/facebook/react-native/tree/master/template

This change complicates logic a bit to resolve template location, since we can't create a cyclical peer dependency on react-native-windows. We instead need to resolve the location of react-native-windows dynamically. We do that by searching from the project directory.

Will validate by init tests in CI. Not sure if there is a current way to validate autolinking.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5893)

### CODE REVIEW

**Comment by NickGerleman** [comment]
@jonthysell let me know if there is a way I can validate the autolinking code.

**Comment by alloy** [comment]
:ceiling-cat: What does `--useDevMode` do?

**Comment by NickGerleman** [comment]
> :ceiling-cat: What does `--useDevMode` do?

`--useDevMode` is a flag for `react-native-windows-init` to use `yarn link` instead of `yarn install` to point to `react-native-windows`. The idea is to allow testing the creation of a new app without having to copy/publish anything.

**Comment by alloy** [comment]
> `--useDevMode` is a flag for `react-native-windows-init` to use `yarn link` instead of `yarn install` to point to `react-native-windows`. The idea is to allow testing the creation of a new app without having to copy/publish anything.

Ooh nice, we should add that to the macOS init command too. /cc @tom-un

**Comment by NikoAri** [comment]
(nit) There is whole bunch of useless .png files. Can they be removed? Or collapsed into single file?

**Comment by kmelmon** [comment]
Thanks for jumping on this!

**Comment by NickGerleman** [comment]
> (nit) There is whole bunch of useless .png files. Can they be removed? Or collapsed into single file?

This PR is just a move, but the PNGs are placeholders which react-native-windows-init adds to new projects to match what would be created by Visual Studio for a new UWP app.

**Pull request merged**
