### PR TITLE
Fixed Releases broken link

### PR DESCRIPTION
**Pull request by slobo80**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2344)

### CODE REVIEW

**Comment by slobo80** [comment]
@acoates-ms can you tell me what i need to do to unblock this PR?

**Comment by acoates-ms** [comment]
Replacing with #2361 which targets master

**Pull request closed without merging**
