### PR TITLE
[0.62] Update react-native config to handle (userConfig === null)

### LINKED ISSUE #5752: [0.62] Cannot read property 'sourceDir' of null
I am getting error when installing pods.

## Environment
1. `npx react-native --version`: 4.12.0
2. `npx react-native run-windows --info`: 
```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 902.91 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @react-native-community/cli: 4.10.1 => 4.10.1 
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
    react-native-windows: 0.62.0 => 0.62.0
  Installed UWP SDKs:
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add some library for native
2. Run `pod install`

## Expected Results
Expected to install without error.

Instead getting this error:

```
[!] Invalid `Podfile` file: 767: unexpected token at 'TypeError: Cannot read property 'sourceDir' of null

    at Object.dependencyConfigWindows [as dependencyConfig] (/Users/myusername/Projects/myproject/node_modules/react-native-windows/local-cli/config/dependencyConfig.js:7:32)

    at /Users/myusername/Projects/myproject/node_modules/@react-native-community/cli/build/tools/config/index.js:63:61

    at Array.reduce (<anonymous>)

    at getDependencyConfig (/Users/myusername/Projects/myproject/node_modules/@react-native-community/cli/build/tools/config/index.js:60:51)

    at Object.get react-native-safe-area-context [as react-native-safe-area-context] (/Users/myusername/Projects/myproject/node_modules/@react-native-community/cli/build/tools/config/index.js:135:18)

    at /Users/myusername/Projects/myproject/node_modules/@react-native-community/cli/build/commands/config/config.js:16:51

    at Array.forEach (<anonymous>)

    at filterConfig (/Users/myusername/Projects/myproject/node_modules/@react-native-community/cli/build/commands/config/config.js:15:38)

    at Object.func (/Users/myusername/Projects/myproject/node_modules/@react-native-community/cli/build/commands/config/config.js:27:32)

    at Command.handleAction (/Users/myusername/Projects/myproject/node_modules/@react-native-community/cli/build/index.js:186:23)
'.

 #  from /Users/myusername/Projects/myproject/ios/Podfile:49
 #  -------------------------------------------
 #  
 >    use_native_modules!
 #  
 #  -------------------------------------------
```

**Quick Fix:**

Change the line 7 in `local-cli/config/dependencyConfig.js`
```
function dependencyConfigWindows(folder, userConfig = {}) {
  const sourceDir = userConfig.sourceDir || findWindowsAppFolder(folder);
```
with this:
```
function dependencyConfigWindows(folder, userConfig = {}) {
  const sourceDir = userConfig & userConfig.sourceDir || findWindowsAppFolder(folder);
```

### PR DESCRIPTION
**Pull request by jonthysell**
The react-native config implementation introduced in RNW 0.61 does not
properly handle when userConfig is explicitly null. This can cause
errors when projects use null (correctly) to prevent the config from
running.

Closes #5752

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5754)

### CODE REVIEW

**Comment by jonthysell** [comment]
This issue is technically also present in 61, though no one's opened a bug on us for it.

This issue doesn't exist in 63 as the config code was entirely rewritten.

**Comment by NickGerleman** [comment]
If this is totally untested, you could also consider not setting projectConfig and dependency config at all in react-native.config.js to not run any of this.

**Comment by jonthysell** [comment]
> If this is totally untested, you could also consider not setting projectConfig and dependency config at all in react-native.config.js to not run any of this.

Yes that is an option, I figured I'd just start with the most minimal change - fixing the exact bug. If there's a consensus to block the codepath entirely, I can make that change.

**Comment by NickGerleman** [comment]
> > If this is totally untested, you could also consider not setting projectConfig and dependency config at all in react-native.config.js to not run any of this.
> 
> Yes that is an option, I figured I'd just start with the most minimal change - fixing the exact bug. If there's a consensus to block the codepath entirely, I can make that change.

I don't have too strong of an opinion either way. The only concern would have is that we could have more issues than what was found, which would make not running anything a bit safer if the config hooks aren't providing value.

**Pull request merged**
