### PR TITLE
Stop scaling fontSize property.

### PR DESCRIPTION
**Pull request by randy-flynn**
The code that scaled this value was from an earlier iteration but isn't correct and needs to be removed. It will have impact on existing clients as they have scaled their fonts to match the existing behavior.

### CODE REVIEW

**Comment by randy-flynn** [comment]
azp /run

**Comment by acoates-ms** [comment]
This presumably will have a pretty large effect on existing uwp RN apps?  Ex: is LPC ready for this?

**Comment by randy-flynn** [comment]
> This presumably will have a pretty large effect on existing uwp RN apps?  Ex: is LPC ready for this?

They definitely have work to do, but it has been discussed with them. The need for work is obvious when you run LPC with this change - 2/3 of the text gets smaller. The other 1/3 is interesting, likely using a default size. Will talk with Sverre about it.

**Comment by ahimberg** [comment]
fixes this issue: https://github.com/Microsoft/react-native-windows/issues/2114

**Pull request merged**
