### PR TITLE
remove-JsBigAbiString

### PR DESCRIPTION
**Pull request by Oscar-Santacruz**
This type is not used by anybody, should be deleted.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7520)

### CODE REVIEW

**Review by AgneLukoseviciute — COMMENTED** [review]
Looks like you're missing the change file, if you run `yarn change --branch upstream/master` in the root of the repo that'll be generated which should unblock the CI build :-)

**Comment by NickGerleman** [comment]
Do these files need to be removed from vcxproj and filters?

**Comment by vmoroz** [comment]
These files are currently used by the RN desktop version in Office. Please do not delete. We will delete them when we finish up the implementation of the ABI safe API for Office. The RNW code is originated from the MS Office code base. While we made a lot of changes in the current RNW implementation, we are still working on changing Office code to use new APIs.

**Review by vmoroz — CHANGES_REQUESTED** [review]
:clock1:

**Comment by rectified95** [comment]
Closing, since these files are used internally.

**Comment by NickGerleman** [comment]
This sounds familiar to the prototype work @aeulitz did some time ago. Do we know if there are usages of this (beyond exposing to the ABI)?

**Comment by vmoroz** [comment]
> This sounds familiar to the prototype work @aeulitz did some time ago. Do we know if there are usages of this (beyond exposing to the ABI)?

I have added this API sometimes ago when we saw crashes caused by react-native-win32.dll and Office using different memory allocation/deallocation. The goal of the fix was to ensure that objects must be allocated and deallocated in the same DLL. In this case when we pass a bundle to react-native-win32.dll as JsBigString, we allocate it using the JsBigAbiString in the react-native-win32.dll and then let it to be destroyed in the same DLL. More specifically we use it for our "platform" bundles.

It is not a "true" ABI-safe API because it only takes care about the memory allocation/deallocation.
The work that we had started with @aeulitz as a part of https://github.com/microsoft/react-native-windows/projects/33 is targeting creation of proper ABI-safe boundary using either WinRT API or C-based APIs. We already did it for the Microsoft.ReactNative.dll, but not for the react-native-win32.dll.

In future we will transform the react-native-win32.dll to be Microsoft.ReactNative.Core.dll that has no knowledge about XAML or any other UI technology, while the Microsoft.ReactNative.dll will be XAML-specific. Though we may need different Microsoft.ReactNative.dll for the different flavors of XAML: System vs WinUI 3, e.g. Microsoft.ReactNative.Xaml.dll and Microsoft.ReactNative.WinUI3.dll.

**Comment by NickGerleman** [comment]
Thanks for the explanation. It was super helpful for my own understanding of how this is used.

**Pull request closed without merging**
