### PR TITLE
Change order of JavaScript tests to get failures earlier

### PR DESCRIPTION
**Pull request by dannyvv**
The most common failure we have in this test are:
a) Missing Change File
b) Linting errors

This PR moves the link checks to the end of this job to ensure we get a failure signal as fast as possible.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6198)

### CODE REVIEW

**Review by NickGerleman — APPROVED** [review]

**Review by jonthysell — APPROVED** [review]

**Comment by NickGerleman** [comment]
@dannyvv @asklar Is it possible to scope Unbroken to only search file trees? Looks like its finding markdown in node_modules after a yarn install, but also pre-install it was still taking around a minute, which makes me wonder if its traversing too much of the filesysystem. We've seen that issue before with repo scripts that have used globs I know.

**Comment by dannyvv** [comment]
> @dannyvv Danny van Velzen FTE @asklar Alexander Sklar FTE Is it possible to scope Unbroken to only search file trees? Looks like its finding markdown in node_modules after a yarn install, but also pre-install it was still taking around a minute, which makes me wonder if its traversing too much of the filesysystem. We've seen that issue before with repo scripts that have used globs I know.

Yeah, I realized whey I put them at the beginning :) It has some way to do that, let me explore...

**Comment by asklar** [comment]
> @dannyvv Danny van Velzen FTE @asklar Alexander Sklar FTE Is it possible to scope Unbroken to only search file trees? Looks like its finding markdown in node_modules after a yarn install, but also pre-install it was still taking around a minute, which makes me wonder if its traversing too much of the filesysystem. We've seen that issue before with repo scripts that have used globs I know.

yes, there is an .unbroken_exclusions file you can add paths to (or errors you want to suppress)

**Comment by dannyvv** [comment]
> > @dannyvv
> >             
> >             Danny van Velzen
> >             FTE Danny van Velzen FTE @asklar
> >             
> >             Alexander Sklar
> >             FTE Alexander Sklar FTE Is it possible to scope Unbroken to only search file trees? Looks like its finding markdown in node_modules after a yarn install, but also pre-install it was still taking around a minute, which makes me wonder if its traversing too much of the filesysystem. We've seen that issue before with repo scripts that have used globs I know.
> 
> yes, there is an .unbroken_exclusions file you can add paths to (or errors you want to suppress)

I made two changes:
1. update the exclusions to `!**/node_modules` instead of `!node_modules`
1. We copy readme.md from the root into vnext to package it in our npm package, I updated the copy to also take care of the LICENCE file which the readme refers to.

**Pull request merged**
