### PR TITLE
[0.60] Patch Folly headers in 0.60-stable release branch with C++20 compiler fixes

### PR DESCRIPTION
**Pull request by tom-un**
## Description
The Folly headers in the UWP version published from the 0.60-stable release branch do not compile properly with C++20 compiler settings.

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
The `OfficeReact.Uwp` NuGet package version `0.60.0-vnext` is published from the `0.60-stable` branch and is still consumed in some Office projects.   Some of the Folly C++ headers are not compatible with C++20 compiler settings.

### What
The version of Folly used by the build scripts is https://github.com/facebook/folly/archive/v2019.09.30.00.zip.   The build scripts will patch the zip's headers with any headers found in the `vnext/Folly/TEMP_UntilFollyUpdate/` folder.

The following PR's in the Folly project address c++20 compile issues.  Each change was picked into the matching header in v2019.09.30.00.zip and verified in an Office build:

PR | Description | Files | Status 
--- | --- | --- | ---
https://github.com/facebook/folly/pull/1628 | Fix static_assert   for C++20 #1628 | folly/concurrency/CacheLocality.h | Not applicable in 0.60-stable version of the file.
https://github.com/facebook/folly/pull/1544 | [folly/container/F14]   avoid operator!= ambiguity in c++20 #1544 | folly/container/detail/F14Policy.h | Verified
https://github.com/facebook/folly/pull/1542 | Fix Range.h to   compile in c++20 #1542 | folly/Range.h | Verified
https://github.com/facebook/folly/pull/1329 | Fix compilation   errors for C++20 #1329 | folly/FBString.h     folly/detail/Iterators.h | Verified

## Testing
Testing was performed in internal Office builds.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9192)

### CODE REVIEW

**Comment by asklar** [comment]
I don't think we should be adding new features (like C++20 support) to a release as old as 0.60. @chrisglein ?

**Comment by chrisglein** [comment]
> I don't think we should be adding new features (like C++20 support) to a release as old as 0.60. @chrisglein?

Generally we aren't going to do anything at all with 0.60. For most active RNW customers I'd consider that well out of dedicated support at N-6. This is likely to affect Office and no one else.

But I imagine @tom-un has a good reason for wanting to touch 0.60 for some Office servicing? Is this to keep 0.60 building with the evolving toolchain?

**Comment by NickGerleman** [comment]
As a matter of practicality, it might take some effort to publish a new NuGet package for this...

**Comment by tiagomacarios** [comment]
This is the last blocker to moving Word to C++20. We already have other activities that depend on C++20 as well. If this PR will be contentious can someone start an internal thread with a proposed plan-B?

**Comment by Khalef1** [comment]
Taking offline with Office team

**Comment by NickGerleman** [comment]
From offline discussion, the last remaining user of ReactUwp is now detached from Office devmain, so I don't think this PR is still needed. Going to close this, but feel free to reopen if I misinterpreted.

**Pull request closed without merging**
