### PR TITLE
[0.62] Prevent Switches from Erroneously Becoming Disabled (#5205)

### LINKED ISSUE #5204: Switch gets incorrectly disabled in very basic scenario with 2 Switches
If I put 2 Switches into a barebones app and hook them both up with basic on/off behavior, interacting with one of the switches causes the other switch to become disabled. 

See this snack:
https://snack.expo.io/g5a5hvCnK

When I run this on Android/iOS it behaves as expected:  You can interact with either switch and both switches stay enabled.  For example if I flip the first switch on, it looks like this:

Capture_Android

On Windows, if I do the same thing, the second switch becomes disabled:

Capture_Windows

That ain't right.

### PR DESCRIPTION
**Pull request by NickGerleman**
* Prevent Switches from Accidentally Becoming Disabled

Fixes #5204

When implementing a new ViewManager command in 0.62 to set switch value, I accidentally wired it to the native prop to enable or disable the switch instead of set value. This shows up in a simple test, and the RNTester example "Switches are controlled components", but strangely not any of the other switch examples. This seems to be a factor of implementation details of when JS sends the ViewManager command vs not.

Confirmed that this change prevents the switch from getting disabled in the "Switches are controlled components" RNTester example. We now see the switch flicker back into the off state instead of disabled (This same flicker is confirmed to happen on iOS/Android when the switch is uncontrolled).

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5215)

### CODE REVIEW

**Comment by NickGerleman** [comment]
From merge conflicts, it looks like 0.62 was using a different tree-dump representation. Need to grab that from the E2ETest  CI run that will fail.

**Comment by asklar** [comment]
> From merge conflicts, it looks like 0.62 was using a different tree-dump representation. Need to grab that from the E2ETest CI run that will fail.

we used to do a key=value representation but moved to json.

**Comment by NickGerleman** [comment]
I think 0.62 never got the reliability fixes that were needed to add the switch back to the test page. So, we would still be seeing hidden elements, and we seem to pass tests without updating switch masters.

**Pull request merged**
