### PR TITLE
Point react-native fork dependency to github tar

### PR DESCRIPTION
**Pull request by marlenecota**
#2094 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2279)

### CODE REVIEW

**Comment by acoates-ms** [comment]
I dont think an or works in the dependency field.  You'll have to move it to a peer dependency for this change to work.

You'll also have to update the logic in evergreen.js to properly bump the package version.

**Comment by marlenecota** [comment]
Is there a reason why we would want to move to peer dependencies instead of removing "0.58.6-microsoft.21" and only pointing to the tar? Moving it to peer dependencies would add an extra install step as it would only give a warning, right?

**Comment by acoates-ms** [comment]
Having it as a peer dependency allows the users of the package to determine which version they want to use.  Some people will want to take the tar and publish it to their internal feeds so that they dont rely on a public tar existing forever.

Internally we do this, so having the normal version allows us to publish it to our feed and use it directly which allows our infra to cache the package, and generally work better with the rest of our tooling.

**Pull request merged**
