### PR TITLE
Cleaning up ReactUWP's WinRT code

### PR DESCRIPTION
**Pull request by jonthysell**
- Broke up the megalithic ReactControl.g.idl into separate files
- Fixed the build to clean up midl generated files
- Overall just make it easier for us to iterate on the winrt stuff

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2332)

### CODE REVIEW

**Comment by jonthysell** [comment]
This is the same code as #2307, only re-targeting master.

**Comment by kmelmon** [comment]
I left this comment on the previous PR...  Still looking for an answer.

Looking at the history of the Commits in your topic branch, these two commits are listed in the reverse order of what I would expect, which seems to explain version 2 showing fewer changes. Would you happen to know what operations you did that made this happen?

88652ea Author Date 4/5 <- listed as the latest version
a5b9fc6 Author Date 4/12

**Comment by jonthysell** [comment]
> 
> 
> I left this comment on the previous PR... Still looking for an answer.
> 
> Looking at the history of the Commits in your topic branch, these two commits are listed in the reverse order of what I would expect, which seems to explain version 2 showing fewer changes. Would you happen to know what operations you did that made this happen?
> 
> [88652ea](https://github.com/Microsoft/react-native-windows/commit/88652ea085dab59487b640d51fb0b9436e5bf176) Author Date 4/5 <- listed as the latest version
> [a5b9fc6](https://github.com/Microsoft/react-native-windows/commit/a5b9fc65581764ec57da4990f8d1fb91e780c671) Author Date 4/12

The original branch also included experiments to implement WinRT view managers, and I believe that I didn't actually implement the AfterCppClean stuff until after the initial refactor. So when I re-based to remove the commits I may have rearranged the order.

Looks like CodeFlow is looking at commit date metadata and not the actual parent/child relationship of the commits.

It'll all get squashed together anyway when I complete the PR.

**Comment by kmelmon** [comment]
Thanks.  @StephenlPeters also observed strange re-ordering back in WinUI repo, so we were both wondering how this can happen.  I'm not concerned about the merge being incorrect, more about just trying to avoid this if possible as it's confusing.

---
In reply to: [485981891](https://github.com/Microsoft/react-native-windows/pull/2332#issuecomment-485981891) [](ancestors = 485981891)

**Pull request merged**
