### PR TITLE
Allow batches to complete during load

### PR DESCRIPTION
**Pull request by acoates-ms**
During boot we have an undecorated callInvoker since the decorated one is not available until later in the instance boot sequence.  This means that early calls into turbomodules do not call into `NativeToJsBridge::recordTurboModuleAsyncMethodCall` which causes `NativeToJsBridge` to not call `onBatchComplete` at the end of a batch.

Changing the if in `BridgeUIBatchInstanceCallback::onBatchComplete` to allow batches to be completed during boot helps so that we do not miss any batch completions that are triggered.  But we also need to ensure that any calls queued before we were using the decoratedCallInvoker also triggers an `onBatchComplete`, which we do by using the decoratedCallInvoker when queuing the switch between the invokers.

Closes https://github.com/microsoft/react-native-windows/issues/10255

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10298)

### CODE REVIEW

**Review by jonthysell — APPROVED** [review]
Looks good to me. Verified it fixes #10255.

**Comment by asklar** [comment]
@acoates-ms @jonthysell is this needed for 0.69 too?

**Comment by cjhines** [comment]
is this published?

**Comment by cjhines** [comment]
I'm still encountering this on 0.69.6, [where I believe the fix was published](https://github.com/microsoft/react-native-windows/compare/react-native-windows_v0.69.6...main).

Weirdly, when I build a package in Visual Studio the bug does not occur. This is still a blocker however, as it prevent our CI deployment.

**Comment by acoates-ms** [comment]
That change was never ported to 0.69, I just opened a PR to port it.

**Comment by cjhines** [comment]
@acoates-ms Ah that's great news! Thank you for clarifying. We'll be eagerly awaiting the new 0.69 version.

**Pull request merged**
