### PR TITLE
[0.65] Update WinUI to 2.6.0

### LINKED ISSUE #7425: Upgrade RNW 0.65 to use WinUI 2.6 by default (when available)
RNW currently pulls in 2.5 ([as of this change](https://github.com/microsoft/react-native-windows/issues/6182))

2.6 is coming. We'll want to start pointing to that once it's available.

A current preview here:
https://www.nuget.org/packages/Microsoft.UI.Xaml/2.6.0-prerelease.210217002

### PR DESCRIPTION
**Pull request by chiaramooney**
**_Why_**
Updating React Native Windows to use the most up to date copy of WinUI: 2.6.0

**_What_**
Updated version of WinUI consumed by React Native Windows and all of the sample apps to be 2.6.0.

Resolves #7425

Backport #8110 to 0.65.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8131)

### CODE REVIEW

**Review by asklar — APPROVED** [review]

**Comment by asklar** [comment]
don't we need to update the snapshots too?

**Comment by chiaramooney** [comment]
Bugs in 2.6 that need to be resolved before this PR should be merged. Intentionally leaving open for now.

**Comment by NickGerleman** [comment]
Should we revert the change in our master branch if 2.6 introduced regressions?

**Comment by chiaramooney** [comment]
Bugs shown to not occur within React Native Gallery. Ready to merge.

**Pull request merged**
