### PR TITLE
Testing CODEOWNERS (DO NOT MERGE OR REVIEW)

### PR DESCRIPTION
**Pull request by jonthysell**
This is a test PR to verify if *all* codeowners must sign off in order to check in a change. Please do not review unless I ask you to. :)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9033)

### CODE REVIEW

**Review by chiaramooney — APPROVED** [review]
👍

**Review by dannyvv — APPROVED** [review]
Before I signed off:
image
and
image

After I signed off

**Comment by dannyvv** [comment]
Looks like GH is missing the concept or "Required" and "Optional" reviewers...

**Comment by jonthysell** [comment]
Waiting to see if

> Looks like GH is missing the concept or "Required" and "Optional" reviewers...

Yes, the CODEOWNERS protection uses user1 OR user2 OR user3, where-as we want user1 AND user2 AND user 3

**Pull request closed without merging**
