### PR TITLE
Adding the useWinUI3 and useHermes tag in the Readme

### PR DESCRIPTION
**Pull request by imrishabh18**
Issue - #7426 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7788)

### CODE REVIEW

**Comment by asklar** [comment]
change looks fine to me except for the unrelated changes (deletes?) to bin.js in several directories, any idea where that's coming from?

**Comment by asklar** [comment]
Also please run `yarn change` from root of repo to generate a change file.

**Comment by asklar** [comment]
We'll also want to update the docs in https://microsoft.github.io/react-native-windows/docs/getting-started which are sourced from https://github.com/microsoft/react-native-windows-samples/blob/master/docs/getting-started.md
(we'll need a separate PR for that since it's in a different repo)

**Comment by imrishabh18** [comment]
Okay, I deleted those unnecessary bin.js files in different directories. And I have already made a PR for the other repo here https://github.com/microsoft/react-native-windows-samples/pull/438

**Review by dannyvv — APPROVED** [review]
Thank you @imrishabh18 for your contribution, making react-native-windows better!

**Pull request merged**
