### PR TITLE
Always write nuget.config in init CLI

### PR DESCRIPTION
**Pull request by asklar**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7528)

### CODE REVIEW

**Review by dannyvv — APPROVED** [review]

**Comment by dannyvv** [comment]
Note: We should backport this to older versions too and maybe have a blog post since Customers will run into this soon as well...

**Comment by dannyvv** [comment]
Note: Don't want to hold up the PR. This is great to unblock us. Just want to make sure we follow through with addressing the full break we got subjected to

**Comment by dannyvv** [comment]
FYI: Took the liberty of merging main branch to get past the CI issues.

**Comment by asklar** [comment]
@dannyvv do we still need this in master? I thought CI is flushed and working now?

**Comment by NickGerleman** [comment]
Wouldn't we need this to avoid every customer project from hitting the issue?

**Comment by asklar** [comment]
@NickGerleman I thought so too, but the CLI builds in CI are passing now so I'm not sure how those are now passing

**Comment by NickGerleman** [comment]
> @NickGerleman I thought so too, but the CLI builds in CI are passing now so I'm not sure how those are now passing

@asklar A few theories:
1. Different jobs run on different pools, with different update schedules. It is possible the CLI test machines haven't been updated to the new VS yet.
2. (Less likely) part of the config could be leaking from elsewhere. E.g. workaround for the issue was to set some global NuGet state. The agent machine could have that state set in in a root traversable location.

**Comment by NickGerleman** [comment]
> @NickGerleman I thought so too, but the CLI builds in CI are passing now so I'm not sure how those are now passing

@asklar A few theories:
1. Different jobs run on different pools, with different update schedules. It is possible the CLI test machines haven't been updated to the new VS yet.
2. (Less likely) part of the config could be leaking from elsewhere. E.g. workaround for the issue was to set some global NuGet state. The agent machine could have that state set in in a root traversable location.

**Comment by NickGerleman** [comment]
@dannyvv what agents do the CLI tests run on?

**Comment by AgneLukoseviciute** [comment]
Added these changes to 0.64 in #7548.

**Comment by NickGerleman** [comment]
If we added this to 0.64-stable, I think we should probably also merge this PR in master.

**Pull request merged**
