### PR TITLE
Update Lerna

### PR DESCRIPTION
**Pull request by dannyvv**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6191)

### CODE REVIEW

**Comment by NickGerleman** [comment]
@dannyvv missing a commit/file?

**Comment by dannyvv** [comment]
> @dannyvv Danny van Velzen FTE missing a commit/file?
Note: package.json at root does not get tracked by beachball..

**Comment by NickGerleman** [comment]
@dannyvv this is still showing as just a whitespace change for me. 
image

**Comment by dannyvv** [comment]
I'll check later what happened

**Pull request closed without merging**
