### PR TITLE
Tidy up PR build tasks

### PR DESCRIPTION
**Pull request by JunielKatarn**
Avoid hard-coded variables so the build process can be configured without the need of additional pull requests.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/3124)

### CODE REVIEW

**Comment by zzy0531** [comment]
[ https://github.com/microsoft/react-native-windows/pull/3124?email_source=notifications&email_token=AB73GJS3OVCAWKABAZOXVX3QJBZHHA5CNFSM4IVPFPFKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HKTQ32A | view it on GitHub ] 


发件人: "Julio César Rocha" <notifications@github.com> 
收件人: "microsoft/react-native-windows" <react-native-windows@noreply.github.com> 
抄送: "Subscribed" <subscribed@noreply.github.com> 
发送时间: 星期三, 2019年 9 月 11日 下午 12:41:23 
主题: [microsoft/react-native-windows] Inject build variables from Library. (#3124) 



Avoid hard-coded variables so the build process can be configured without the need of additional pull requests. 
You can view, comment on, or merge this pull request online at: 


[ https://github.com/microsoft/react-native-windows/pull/3124 | https://github.com/microsoft/react-native-windows/pull/3124 ] Commit Summary 


    * Use variables from library. 
    * Link variable group. 
File Changes 


    * M [ https://github.com/microsoft/react-native-windows/pull/3124/files#diff-0 | .ado/windows-vs-pr.yml ] (45) 
Patch Links: 


    * [ https://github.com/microsoft/react-native-windows/pull/3124.patch | https://github.com/microsoft/react-native-windows/pull/3124.patch ] 
    * [ https://github.com/microsoft/react-native-windows/pull/3124.diff | https://github.com/microsoft/react-native-windows/pull/3124.diff ]

**Comment by JunielKatarn** [comment]
> I'd rather these were in the yaml files.
> 

The permissions implication can be fixed by adjusting who has write access to those variables.
I'll open a discussion offline.

Let's at least allow the test filters to be settable externally.
That way, if a test starts failing, we can deactivate it or tune immediately, without a full PR.

**Comment by acoates-ms** [comment]
The test filtering is also going to want to be per branch.

**Comment by JunielKatarn** [comment]
> The test filtering is also going to want to be per branch.

Done.

**Pull request merged**
