### PR TITLE
1219

### PR DESCRIPTION
**Pull request by asklar**
# DO NOT CHECK IN
rebasing canhual's PR onto master - 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6785)

### CODE REVIEW

**Comment by asklar** [comment]
@licanhua I rebased your branch onto master and it isn't failing on latest :) CC @dannyvv

**Comment by dannyvv** [comment]
@asklar: Thank you! 
This is still pending Python dependency you mentioned. My understanding was that VS now installs Python so IC's shouldn't worry... I do agree that is is annoying as I had to update the CI scripts. 

Note that the customer packages do not have this dependency right? It is only e2etest that depended on appium/windriver..

**Comment by asklar** [comment]
@dannyvv VS only installs python if you select the python workload in the installer, I hadn't selected it and ran into the issue.
The problem is not isolated to e2etest. Running yarn at the root of the repo will try to use node-gyp which will try to use python, so I believe this affects everyone.

**Comment by dannyvv** [comment]
devs workign on RNW repo, not customers USING react-native-windows right?

**Comment by asklar** [comment]
> devs workign on RNW repo, not customers USING react-native-windows right?

I haven't tried the using scenario, it but that's a good question for canhua :) it might be ok if it's defined as a devdependency? unsure.
Still, we shouldn't just add a whole workload just for this if we can avoid it. Why do we need this package and can we get the same behavior without requiring python?

**Pull request closed without merging**
