### PR TITLE
Update WinAppSDK from 1.5 to 1.6 (1.6.240923002)

### PR DESCRIPTION
**Pull request by JesseCol**
## Description
This change updates our WinAppSDK package from WinAppSDK 1.5.240227000 to 1.6.240923002.

Note that WinAppSDK 1.6 has a nuget package dependency on WebView2, so this change introduces a dependency on that package as well.

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
This updates the WinAppSDK package, which brings new bug fixes and features we'll be able to take advantage of later.

### What
I've updated WinUI.props to use the new version, and picked up the packages.lock.json updates made by nuget restore.

## Testing
I ran playground-composition with the rntester bundle and verified that basic functionality still works.

## Changelog
Should this change be included in the release notes: Yes

"React Native Windows has been updated to build on WinAppSDK 1.6."
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/13977)

### CODE REVIEW

**Review by chiaramooney — APPROVED** [review]
👍

**Comment by TatianaKapos** [comment]
if we want this in 0.76, we will need to backport it after this is merged in! 
Backport instructions here: https://github.com/microsoft/react-native-windows/wiki/Backporting-a-Change

**Review by chiaramooney — APPROVED** [review]
👍

**Pull request merged**
