### PR TITLE
Don't new up C++ exceptions

### PR DESCRIPTION
**Pull request by namrog84**
You shouldn't new up exceptions in c++.  

#3364 

This likely a small memory leak. 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/3398)

### CODE REVIEW

**Comment by namrog84** [comment]
I can't tell if build machine is flakey, and how to try rerunning, or is it a legitimate build failure?

**Comment by stecrain** [comment]
> I can't tell if build machine is flakey, and how to try rerunning, or is it a legitimate build failure?

It's complaining that you don't have a changes file for the change log.
You can run 'yarn change' at the root of the repo to generate a change file.

**Comment by namrog84** [comment]
> You can run 'yarn change' at the root of the repo to generate a change file.

```
F:\GS\repo\RNW>yarn change
yarn run v1.15.2
$ node ./node_modules/beachball/bin/beachball.js change
Defaults to "origin"
Target branch is "origin/master"
Checking for changes against "origin/master"
fetching latest from remotes
No change files are needed
```

I don't see any files changed.  So I am not sure if I am doing something wrong?  
I have never used yarn change before so I am not sure if there were extra steps needed.

**Comment by acoates-ms** [comment]
Did you run that from your branch?

**Comment by namrog84** [comment]
I think I got it working and what to do better next time.

**Pull request merged**
