### PR TITLE
[0.63] Win32 Polite/Aggressive Focus API (#6711)

### PR DESCRIPTION
**Pull request by dannyvv**
* Adding Polite/Aggressive Focus APIs

* Adding FocusManager API for polite/aggresive focus for win32

Co-authored-by: samuelfreiberg <Samuel.Freiberg@microsoft.com>
Co-authored-by: Nick Gerleman <nick@nickgerleman.com>

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6731)

### CODE REVIEW

**Comment by dannyvv** [comment]
Backport of: #6711

**Review by samuelfreiberg — APPROVED** [review]

**Comment by NickGerleman** [comment]
Reminder that we should bring the change into 0.64 if bringing into 0.63. Office Win32 is still on 0.62, so we may need it there as well.

**Comment by dannyvv** [comment]
@NickGerleman: Thanks, 0.64 is already merged.

**Comment by Khalef1** [comment]
@dannyvv : I'm approving but please also check if this needs to be backported to 62. Office is still on that version and isn't ready to move to 63 yet.

**Review by Khalef1 — APPROVED** [review]

**Pull request merged**
