### PR TITLE
Suppress warning for false positives of [experimental] warning in MIDL

### PR DESCRIPTION
**Pull request by dannyvv**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8302)

### CODE REVIEW

**Comment by acoates-ms** [comment]
I had been wondering about these warnings, and if they are an indication that we are doing something wrong.  Are we sure these are false positives?

**Comment by dannyvv** [comment]
I'm planning to enable `/warnaserror` on the msbuild invocation once we are at zero warnings.

**Comment by dannyvv** [comment]
> I had been wondering about these warnings, and if they are an indication that we are doing something wrong. Are we sure these are false positives?

@asklar: I'll have to reply on your MIDL expertise.. I could not find any documentation around this, but from inference it seems that midl is generating types IFoo for class Foo in it's internal structure, does not annotate that with [Experimental] And it's static analysis in a later phase flags that as an issue...

**Comment by asklar** [comment]
@dannyvv IIRC this was a bug in MIDL that was fixed in a recent SDK. I'm not sure if there is a way to silence it, does this PR already work or are you looking for a way to make it work?

**Comment by dannyvv** [comment]
@asklar. This PR suppresses the warning by adding `/no_warn:5135` to the MIDL invocations.

**Comment by dannyvv** [comment]
It does seem it did not take for Project Reunion...

**Comment by asklar** [comment]
The fix is in the 19041 SDK, we should not turn on this warning as it might hide legitimate problems now that we are mostly on 19041. See https://task.ms/30935318

**Comment by dannyvv** [comment]
@asklar: okay, let me run a build without and see if only in Reunion. I'll turn on warnaserror for the other projects and file a bug to do so for reunion once that is updated.

**Comment by dannyvv** [comment]
Confirmed warnings were only in ProjectReunion builds, no other builds. Created new PR to enable warnaserror for all builds except ProjectReunion.

**Comment by dannyvv** [comment]
Confirmed warnings were only in ProjectReunion builds, no other builds. Created new PR to enable warnaserror for all builds except ProjectReunion.

**Pull request closed without merging**
