### PR TITLE
Removes unnecessary prop settings on VM base class

### LINKED ISSUE #9050: FrameworkElementViewManager sets layout props on XAML
### Problem Description

Yoga should be the only thing that manages the layout for RN views. There are settings in FrameworkElementViewManager that unnecessarily sets the `width`, `height`, `(min|max)(Width|Height)` props to corresponding XAML properties on FrameworkElement.

### Steps To Reproduce

1. It's easy to contrive a bug caused by the existing logic:
```js

class BugExample extends React.Component<$FlowFixMeProps> {
  state = {
    toggle: false,
  };

  render() {
    const circleStyle = {
      flexDirection: 'row',
      backgroundColor: '#f6f7f8',
      borderWidth: 0.5,
      borderColor: '#d6d7da',
      marginBottom: 2,
    };
    return (
      <View>
        <Text
          style={{
            maxWidth: this.state.toggle ? '50%' : 200,
            height: 20,
          }}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
          ullamcorper eros quis libero hendrerit, eget interdum mi lacinia.
        </Text>
        <Button
          title="Test"
          onPress={() => this.setState({toggle: !this.state.toggle})}
        />
      </View>
    );
  }
}
```

When you toggle between a numeric layout prop and a string layout prop, XAML retains the numeric prop. Here's the example running:

https://user-images.githubusercontent.com/1106239/140188434-d1df775e-2632-4aa6-b56c-cb321ccd88d1.mp4

### Expected Results

https://user-images.githubusercontent.com/1106239/140184588-cc507e4c-ed26-4a75-8cc5-944f09795018.mp4

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

_No response_

### Target Device(s)

_No response_

### Visual Studio Version

_No response_

### Build Configuration

_No response_

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by rozele**
### Type of Change
_Erase all that don't apply._
- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

This is possibly a breaking change in case any third-party view managers are relying on these XAML values being set before Yoga layout calculation runs, but this is another case where these components would be relying on a buggy implementation detail rather than an expected feature of react-native-windows.

### Why

Removes bug-prone application of Yoga layout props to XAML layout properties on FrameworkElement as layout should be done by Yoga.

react-native-windows as special casing some numeric layout prop values and setting them as XAML layout properties. These kinds of special cases lead to a very poor experience, as it might be unclear to some why measurement might behave differently if you specify a numeric prop value for, e.g., `maxWidth` vs. a string prop value like `'50%'`. Additionally, it's odd to set these XAML properties only for some of the sizing parameters. Many other flex properties affect sizing, like `flex`, and positional layout properties like `top`, `left`, `bottom`, and `right` do not receive special treatment.

Resolves #9050

### What

Removes the explicit setting of layout prop values on FrameworkElementViewManager for:
- width
- height
- minWidth
- minHeight
- maxWidth
- maxHeight

Setting these values can cause the bug described in #9050 due to the special treatment of numeric values for these props.

These props should not be needed at all. If a view is self-measuring, Yoga hands the parameters of layout via the self-measuring callback, and at any rate the width and height props are cleared before measuring:
https://github.com/microsoft/react-native-windows/blob/8adef58a52ed3400ba288fa4299e73fb8eef8384/vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp#L70-L71

And the `min` / `max` props will be accounted for in the Yoga layout calculation when setting the width/height bounds and measurement modes.

## Screenshots
Add any relevant screen captures here from before or after your changes. 

Before:

https://user-images.githubusercontent.com/1106239/140188434-d1df775e-2632-4aa6-b56c-cb321ccd88d1.mp4

After:

https://user-images.githubusercontent.com/1106239/140186127-f233ddbd-e4b6-4dcf-98d0-6c39d6ec9438.mp4

## Testing

_Optional_: Describe the tests that you ran locally to verify your changes.

I contrived an example that would be broken in RNTester and tested before and after:
```

class BugExample extends React.Component<$FlowFixMeProps> {
  state = {
    toggle: false,
  };

  render() {
    const circleStyle = {
      flexDirection: 'row',
      backgroundColor: '#f6f7f8',
      borderWidth: 0.5,
      borderColor: '#d6d7da',
      marginBottom: 2,
    };
    return (
      <View>
        <Text
          style={{
            maxWidth: this.state.toggle ? '50%' : 200,
            height: 20,
          }}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
          ullamcorper eros quis libero hendrerit, eget interdum mi lacinia.
        </Text>
        <Button
          title="Test"
          onPress={() => this.setState({toggle: !this.state.toggle})}
        />
      </View>
    );
  }
}
```

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9051)

### CODE REVIEW

**Review by acoates-ms — APPROVED** [review]

**Comment by asklar** [comment]
@rozele Could you please validate that this doesn't change the behavior of react-native-xaml? We don't have automated tests to validate this, so we'd need manual verification.

**Review by asklar — CHANGES_REQUESTED** [review]
pending validation that it doesn't break react-native-xaml

**Comment by rozele** [comment]
@asklar - I'd be surprised if it did break react-native-xaml. If react-native-xaml is dependent on this behavior, then it's likely broken for many RN use cases.

**Comment by rozele** [comment]
@asklar react-native-xaml example works the same before and after fix...

Before:

https://user-images.githubusercontent.com/1106239/140232664-9a28465c-d61e-4507-b671-e7bc1ff9f82b.mp4

After:

https://user-images.githubusercontent.com/1106239/140232670-72d53ec3-5911-4422-a988-512757d7fb7c.mp4

**Review by asklar — APPROVED** [review]
thanks for validating!

**Review by jonthysell — APPROVED** [review]

**Pull request merged**
