### PR TITLE
Support 'focusable' prop on all ControlViewManager-derived components

### LINKED ISSUE #8423: [0.64] ScrollViewManager is missing handler for 'focusable' prop
The `focusable` prop is used to toggle the IsTabStop property on a component. This prop is exposed on ScrollViewProps (by way of inheriting from ViewProps) and supported by ViewViewManager, but appears to be missing from the ScrollViewManager inheritance chain.

The effect is that there's no way to mark a ScrollView as focusable. This is needed if a ScrollView has no focusable children (say, only text) in order to provide a target to tab to and then use other keys to scroll.

I suggest adding a handler to ControlViewManager since it's the parent class that already has a handler for tabIndex.

### PR DESCRIPTION
**Pull request by aschultz**
This resolves #8423.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8450)

### CODE REVIEW

**Review by NickGerleman — APPROVED** [review]

**Comment by aschultz** [comment]
@NickGerleman Can you complete these? I don't have permissions to check in.

**Comment by asklar** [comment]
I think we already have this property, why do we need this?

**Review by asklar — CHANGES_REQUESTED** [review]
let's sync with Agne on why we need this

**Comment by NickGerleman** [comment]
@asklar there is context in the referenced issue

@aschultz PRs with the AutoMerge label are merged automatically if they have sign off and have been out for at least 10 hours.

**Review by asklar — APPROVED** [review]

**Comment by Brouilles** [comment]
Available in which version? I also need it.
Thanks.

**Comment by asklar** [comment]
> Available in which version? I also need it.
> Thanks.

it will be available in 0.66

**Pull request merged**
