### PR TITLE
Use boost::numeric_cast.

### PR DESCRIPTION
**Pull request by hansenyy**
There a various places where we check for overflow before using static_cast to perform an integer conversion. Since we already depend on boost, we should just use boost::numeric_cast for this. This PR performs said change.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/3676)

### CODE REVIEW

**Comment by tudorms** [comment]
It looks like we don't actually depend on boost now; the change is adding the boost dependency to these 3 projects that didn't have it before. It seems a bit overkill to bring in this heavy dependency for a SafeCast helper thing

**Comment by hansenyy** [comment]
> It looks like we don't actually depend on boost now; the change is adding the boost dependency to these 3 projects that didn't have it before. It seems a bit overkill to bring in this heavy dependency for a SafeCast helper thing

**Comment by hansenyy** [comment]
> It looks like we don't actually depend on boost now; the change is adding the boost dependency to these 3 projects that didn't have it before. It seems a bit overkill to bring in this heavy dependency for a SafeCast helper thing

Are we planning on getting rid of boost dependency all together? I still see it being in used in many other projects.

**Comment by JunielKatarn** [comment]
> > It looks like we don't actually depend on boost now; the change is adding the boost dependency to these 3 projects that didn't have it before. It seems a bit overkill to bring in this heavy dependency for a SafeCast helper thing
> 
> Are we planning on getting rid of boost dependency all together? I still see it being in used in many other projects.

No, we are not getting rid of boost.
That said, the amount of written code this change saves is not significant, and because boost is a header-only library, it could be increasing our binary sizes notably without a major justification.

In my opinion, we should increase the dependency level on any third party code if it's not essential.

**Comment by hansenyy** [comment]
> > > It looks like we don't actually depend on boost now; the change is adding the boost dependency to these 3 projects that didn't have it before. It seems a bit overkill to bring in this heavy dependency for a SafeCast helper thing
> > 
> > 
> > Are we planning on getting rid of boost dependency all together? I still see it being in used in many other projects.
> 
> No, we are not getting rid of boost.
> That said, the amount of written code this change saves is not significant, and because boost is a header-only library, it could be increasing our binary sizes notably without a major justification.
> 
> In my opinion, we should increase the dependency level on any third party code if it's not essential.

Sounds reasonable. Abandoning this PR.

**Comment by NickGerleman** [comment]
@tudorms @hansenyy Folly already has a dependency on Boost, and is going to be in the same DLL as the changes. Seems like we shouldn't pay more for binary size for anything we don't directly use? I don't like how we separately ask to import Boost, but maybe we could organize our projects in a way where we only express the dependency in one area.

**Pull request closed without merging**
