### PR TITLE
Update react-native dependency to 0.59

### PR DESCRIPTION
**Pull request by rozele**
Updates dependencies to match react-native@0.59, includes fixes to metro config, Alert module and updated reference to @react-native-community/cli

### CODE REVIEW

**Comment by rozele** [comment]
Still needs some work updating references to @react-native-community/cli

**Comment by rozele** [comment]
Fixed issue with template generator, one more issue to resolve for metro in generated projects.

**Comment by matthargett** [comment]
doesn't Yoga also need to be synced?

**Comment by matthargett** [comment]
I'm tracking an upstream issue where apps for out-of-tree platforms get this error when trying to run jest tests after an upgrade to 0.59:
https://github.com/facebook/react-native/issues/20460

The error is the same, but the reasons appear to be different than those mentioned in the thread. 
I can reproduce when I try adding a jest test to the Playground app. @rozele @acoates-ms, can you reproduce?

**Comment by rozele** [comment]
@matthargett good point - I'll also update yoga

**Comment by rozele** [comment]
@matthargett - on second thought - I'll time box the fixes to update to the latest Yoga, as every upgrade seems to result in breaking changes to layout. If it takes more than a couple hours, we'll ship 0.59 as is and add a backlog item to get Yoga updated.

**Comment by rozele** [comment]
Ugh - seemed to be an issue with enum bitfields 🙄. Disabling those fixes the layout.

**Comment by timols** [comment]
Hi @rozele, any updates on this PR? Android is requiring 64bit builds as of Aug 1 which naturally places some time pressure on this upgrade in order to maintain platform compatibility across iOS, Android and Windows.

**Pull request merged**
