### PR TITLE
Avoid double transpilation of TS overrides

### PR DESCRIPTION
**Pull request by NickGerleman**
Metro with its default preset can already transform TS through babel, so there is no need to run the TypeScript compiler as well during the build. This change uses built-in Metro logic for transpilation, which also ensures the devMode metro config produces identical results to production.

We remove tsc compilation from the build to save time, but add it as a linting step with noEmit to check for type errors.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6455)

### CODE REVIEW

**Comment by acoates-ms** [comment]
The react-native-windows and react-native-win32 projects should be shipping JS, not TS.  We shouldn't require users of these projects to have the TS transpile as part of their builds.  Just checking that the published packages will still be JS with this change.

**Comment by NickGerleman** [comment]
@acoates-ms this would mean we ship TS. This doesn't mean users need to build it though, since Metro through Babel is already able to parse TS with the default config, just stripping annotations. It's similar to how RN ships Flow.

The case where this wouldn't work would be if there was a very custom metro config that omitted the TS parser.

The positives would be less opinionated transforms, likely better metro source maps, playground being transpilled in the same way between dev and prod, and marginally faster build.

**Comment by orta** [comment]
There's something which feels _a bit off_ about shipping code which needs to be transpiled, but I agree - generally speaking this is going to result in better code for clients. Especially as this was previously set to ES5, which I doubt is the baseline runtime for RNW

The precedent is that [react-native itself](https://unpkg.com/browse/react-native@0.63.3/index.js) ships flow types in it's JS by default, and assuming this was tested out by a client and works (maybe the default metro config knows to transpile RN by default). I think it's probably a good call.

**Comment by dannyvv** [comment]
@NickGerleman Since this is to improve the dev-loop, how about splitting between debug and release?

**Comment by NickGerleman** [comment]
> @NickGerleman Since this is to improve the dev-loop, how about splitting between debug and release?

Dev loop isn't really the primary reason imo, but more of a bonus that pushed me over the edge to take a look at this change. We have a custom Metro config for playground that already lets us avoid building by having Metro transpile src directly instead of avoiding the build.

This also means though that dev + production libraries have subtly different behavior, which is non-idea. I think raw TS is likely the better option compared to the double transpile given we know anything bundling RN has strong support for raw TS already.

**Comment by alloy** [comment]
In principle I think that distributed packages should be prebuilt, but as @orta mentioned the precedent here is already set with how upstream distributes Flow code and one could also argue that RN is the type of fundamental dependency that may introduce its own build configuration—presumably as babel preset or other means of reducing configuration friction.

Having said that, the thing that I wonder more about is having heard about changing core RNW code from Flow to TS in the past. Is that still the plan? If so, introducing possible build configuration work to customers now and again in the near future might be asking a bit much.

**Comment by NickGerleman** [comment]
@alloy moving from TS to Flow is still the sentiment here, but hasn't bubbled up to be a high enough priority for anyone to bulk convert everything yet. We've been slowly moving the direction though, by virtue of opportunistic changes, or lean core efforts which remove custom components. At this point the remaining TS for the XAML version is mostly slated to eventually be removed. Some of these (e.g. Flyout) will be removed eventually but not in the near-term. NetUI platform is overall in a worse state in terms of TS usage. 

But yeah, I agree with all of the sentiments about this feeling kind of off in principal, but also recognize a lot of the principal is more from experience with Web/Node. Out of curiosity, I looked at a few community modules using TS, and of the two I surveyed, both did compile to JS.

I'm kind of conflicted about all of this. This change does improve a number of facets in real use cases, and was dirt cheap to create, but goes against precedent and as such carries risk. It will also eventually be superseeded, so it arguably might make more sense to just wait and do the work for bulk conversion. I'm not sure when bulk conversion would make sense though.

**Comment by NickGerleman** [comment]
> If so, introducing possible build configuration work to customers now and again in the near future might be asking a bit much.

Just realized I didn't fully respond to this point. We do already ship Flow, in the same capacity as RN, so that shouldn't have customer impact. For metro most configs, the TS change shouldn't have impact, since the metro Babel preset is set to understand TS, but I'm less sure about very custom Metro configs, or the defaults of something like Haul.

**Comment by NickGerleman** [comment]
Hmm, there's enough doubt here that the more I think about this, I'm not sure it's worth the risk.

**Pull request closed without merging**
