### PR TITLE
Implement SyncMethod and Constant for TurboModule

### PR DESCRIPTION
**Pull request by ZihanChen-MSFT**
## Implemented

- `REACT_SYNC_METHOD`
- `REACT_CONSTANT`
- Add test cases to Microsoft.ReactNative.IntegrationTests

## Not Yet Implemented

- `OneCallback` and `TwoCallbacks` for `REACT_METHOD`

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5171)

### CODE REVIEW

**Comment by TheSavior** [comment]
My understanding is that TurboModules, unlike NativeModules, don't support constants. My understanding is that TurboModules just recommends using a `getConstants` method just like any other method.

**Comment by ZihanChen-MSFT** [comment]
> My understanding is that TurboModules, unlike NativeModules, don't support constants. My understanding is that TurboModules just recommends using a `getConstants` method just like any other method.

Authors can do `getConstants` by themselves. Here I keep the same shape of native modules and turbo modules, they share the same piece of native code, they should also look the same in JavaScript.

**Comment by TheSavior** [comment]
> they should also look the same in JavaScript

The constants aren't exposed to JS for TurboModules. Constants in NativeModules require runtime reflection at startup and native has to tell JS the constants so they are available on the JS object. In TurboModules nothing is loaded until a method is called, so the JS object wouldn't have any properties for the constants.

**Comment by acoates-ms** [comment]
This is a case where we exposed some functionality that made sense for native modules, but probably doesn't need to be mapped to turbomodules.

Long term we certainly want to ensure that getConstants is treated as any other sync method as far as TurboModules are concerned.  In the near term, we want to enable our modules to run as either a nativemodule, or a turbomodule, so we need to do some special things for getConstants.

We should look into if we can make the special thing on the NativeModule side, rather than the turbo module side.  -- We may want to look into deprecating REACT_CONSTANT. -- We should discuss this further.

**Comment by TheSavior** [comment]
Ah, got it.

For us at Facebook to prepare for modules to run as both a NativeModule and as a TurboModule we had to migrate those modules and callsites to use a getConstants method. Essentially, this is a known breaking change between NativeModules and TurboModules in core.

**Pull request merged**
