### PR TITLE
Update to newer cppwinrt, 2-3% reduction in binary size

### LINKED ISSUE #6841: Update version of  C++/WinRT to 2.0.201201.7 or later
The version 2.0.201201.7 is adopted internally by some Microsoft teams. We should do the update too.
According to @kennykerr it has the following notable changes: 
- Many coroutine improvements
- C++20 coroutine conformance
- Clang conformance improvements
- try_capture and try_create_instance helpers (https://github.com/microsoft/cppwinrt/pull/663)
- Improved compile-time and run-time diagnostics
- Add value type support to as() and try_as() (https://github.com/microsoft/cppwinrt/pull/695)
- Enable conversion between winrt::clock and std::chrono::system_clock (https://github.com/microsoft/cppwinrt/pull/698)
- Add multi-threaded collections (https://github.com/microsoft/cppwinrt/pull/692)
- Add try_get_activation_factory overloads with class name (https://github.com/microsoft/cppwinrt/pull/769)
- Support boxing delegates

### PR DESCRIPTION
**Pull request by asklar**
Closes #6841 

There are some regressions in cppwinrt package that means we want to hold off and wait until they are fixed in a new nuget before we go ahead with this PR, but this work needs to happen to find the regressions :)
- https://github.com/microsoft/cppwinrt/issues/884
- https://github.com/microsoft/cppwinrt/issues/871
- https://github.com/microsoft/cppwinrt/issues/885

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7352)

### CODE REVIEW

**Comment by vmoroz** [comment]
To switch to a newer C++/WinRT we must change more files. All files where we use the C++/WinRT. These are almost all projects, sample projects, templates, Nuget package config files. If we change it only only in one place we introduce an inconsistency where some projects use one version, while others require a different one.

**Review by vmoroz — CHANGES_REQUESTED** [review]
:clock1:

**Comment by NickGerleman** [comment]
> Can we postpone this change until we cut the 0.64 release?

Anything in the master branch since November will be targeting 0.65 unless cherry-picked. Seems safe to do now (assuming we do it everywhere, like your previous comment).

**Comment by vmoroz** [comment]
BTW, this PR should close this issue: #6841

**Comment by vmoroz** [comment]
Please also update the version for the new projects in this file: https://github.com/microsoft/react-native-windows/blob/master/packages/%40react-native-windows/cli/src/generator-windows/index.ts

**Comment by vmoroz** [comment]
Please change C++ projects in the packages folder such as Playground, Samples and E2E test.

**Review by vmoroz — APPROVED** [review]
:shipit:

**Comment by asklar** [comment]
@vmoroz clearing your status since I don't want to merge this yet as I've found several blocking bugs in the cppwinrt package that we need to get fixed first.

**Pull request merged**
