### PR TITLE
Fix activation startup issue

### PR DESCRIPTION
**Pull request by ryfow**
This is missing a cpp version but I'd like to make sure you think I'm on the right track before spending more time on that template.

Without this change, the executable just exits if activation happens to a not-running application.

I pushed a sample app that lets you send a toast and mess with launching from that toast here: https://github.com/ryfow/rnwtoastactivation

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6086)

### CODE REVIEW

**Comment by asklar** [comment]
@ryfow I think you may want to make this change in the platform reactapplication instead of the app template. See here: vnext/Microsoft.ReactNative/ReactApplication.cpp

**Comment by ryfow** [comment]
Thanks @asklar! I put this change in the template because that's where the OnLaunched version of very similar logic is: https://github.com/microsoft/react-native-windows/blob/master/vnext/template/cs-app/src/App.xaml.cs#L47

Should the OnLaunched code get moved to ReactApplication.cpp too?

**Comment by asklar** [comment]
> Thanks @asklar! I put this change in the template because that's where the OnLaunched version of very similar logic is: https://github.com/microsoft/react-native-windows/blob/master/vnext/template/cs-app/src/App.xaml.cs#L47
> 
> Should the OnLaunched code get moved to ReactApplication.cpp too?

Maaaaybe. The template allows for this stuff to be easily overridden but also how likely is it that people will need to override it in the first place? Main thing to ensure that this works for most people: vanilla launch activation of stock RNW app and vanilla launch of a UWP app that hosts RNW in it (and therefore _may_ not be using ReactApplication). The rest would be good to get working including toast activation, etc. Paging @jonthysell to take a look too since this may end up going into the template.

**Comment by acoates-ms** [comment]
I think we should move everything out of ReactApplication, and just put it in the template.  That way people still have full control over all their application behaviors, and we don't end up with a high policy wrapper between the OS and RNW.

The only hesitation I have is that we still do not a have a good tool for upgrades that will apply changes to the template to existing apps.

**Pull request closed without merging**
