### PR TITLE
Stop using /fp:strict to build yoga.cpp

### PR DESCRIPTION
**Pull request by htpiv**
Compiling yoga.cpp with `/fp:strict` causes #8675. We use this flag to address #4122, but in my manual testing, as well by inspecting the disassembly that seemed to be responsible for issue 4122, this workaround is no longer necessary.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8725)

### CODE REVIEW

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
LGTM. Our UI tests should catch the issue of different measurements if it happens with MSVC version used by CI infra.

**Comment by dannyvv** [comment]
@htpiv It seems you missed `yarn change`. I hope it is okay I took the liberty of running it on your behalf.

**Review by dannyvv — APPROVED** [review]

**Comment by htpiv** [comment]
> @htpiv It seems you missed `yarn change`. I hope it is okay I took the liberty of running it on your behalf.

Thanks! 🙂

**Comment by dannyvv** [comment]
@htpiv: It seems your change introced some behavioral changes caught by the e2e unit tests, as both x64 (hermes and v8) tests failed, even on reruns...
I suspect as you mentioned some of the floating point math on x64 platforms is affected and results in different offsets:
```diff
<           "Left": 24,
>           "Left": 29,
```

```diff
<   "Height": 395,
>   "Height": 360,
```
```diff
<       "Height": 32,
>       "Height": 30,
```

```diff
<       "Height": 144,
>       "Height": 66,
```

I would have to suggest to see if the new renderings are desirable or not.. 
The values are swinging quite a lot, so I am alittle bit worried.... @chiaramooney/@nickgerleman : Do you have any insights if these swings are acceptable?

**Review by asklar — CHANGES_REQUESTED** [review]
it looks like it is still needed since the e2e tests are saying the layout changes (regresses to before we made the FP change)

**Comment by NickGerleman** [comment]
Bulk marking PRs without activity in the last 14 days as needing author feedback. This helps keep all active PRs visible on the first page of PRs. msftbot will close this PR in two weeks if the label is not removed. Please feel free to remove the label if you are still actively working on this.

**Comment by htpiv** [comment]
> it looks like it is still needed since the e2e tests are saying the layout changes (regresses to before we made the FP change)

Yup, turns out we need to remove the undefined behavior from how CompactValue.h is using a union for type-punning. The Yoga code should compile fine.... people have used unions this way for decades, but VC++ seems to have broken something accidentally. I'm getting a linker repro put together to report to them via devcommunity, but in the meantime we can also fix the Yoga code to avoid undefined behavior without causing any trouble (in C++20, via std::bit_cast, downlevel, you just use memcpy and every serious C++ compiler knows how to optimize `memcpy(&flt, &u32, 4)`. Confirmed via godbolt)

**Review by NikoAri — APPROVED** [review]
:shipit:

**Review by asklar — APPROVED** [review]

**Pull request merged**
