### PR TITLE
Bump NuGet packages to latest stable versions

### PR DESCRIPTION
**Pull request by matthargett**
Sync with netstandard branch and privately deployed upgrades. All non-ignored unit tests pass and Playground works in Net46 and UWP.

### CODE REVIEW

**Comment by rozele** [comment]
@matthargett not sure what's wrong with your git config, but the .csproj files are full rewrites rather than single line changes.

**Comment by matthargett** [comment]
@rozele implemented your feedback, let me know if there's anything else you'd like me to do.

**Comment by rozele** [comment]
What's the purpose of the upgrade?

**Comment by matthargett** [comment]
Rx.NET and Json upgrades bring it in line with private forks multiple users have. NUnit upgrade brings it inline with netstandard. UWP and fresco bump is just keeping up with patch releases.

**Pull request merged**
