### PR TITLE
Update vnext/Microsoft.ReactNative.Cxx/README.md

### PR DESCRIPTION
**Pull request by ZihanChen-MSFT**
- File sharing from `react-native-windows` to `react-native-macos` is done.
- Update the instruction so that future works on affected files are able to themselves keep cross-platform.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6202)

### CODE REVIEW

**Review by alloy — APPROVED** [review]
Yup, this description of the process looks good to me 👍

**Comment by ZihanChen-MSFT** [comment]
> /azp run

What happened? @dannyvv

**Review by jonthysell — APPROVED** [review]

**Comment by dannyvv** [comment]
> > /azp run
> 
> What happened? @dannyvv Danny van Velzen FTE

@ZihanChen-MSFT There was a hickup in the [bridge between ADO and GH](https://developercommunity.visualstudio.com/content/problem/1210382/azure-devops-fails-to-trigger-on-github-commit.html)

**Review by dannyvv — APPROVED** [review]

**Pull request merged**
