### PR TITLE
Fixes issue with Run text getting overwritten

### LINKED ISSUE #7534: Virtual text children overwritten when no textTransform specified
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Apply the repro from this commit to RNTester: https://github.com/rozele/react-native-windows/commit/cda922d71b7913a12f5648c8515fc8a7f1326a80
2. Open the Text component example
3. Notice that the last line in the textTransform example should be "xYz" but is instead "zYz".

## Expected Results
The last line of the textTransform example should be: 'Should be "xYz": xYz'
Instead it is: 'Should be "xYz": zYz'

## Snack, code example, screenshot, or link to a repository:
Repro in this commit for RNTester: https://github.com/rozele/react-native-windows/commit/cda922d71b7913a12f5648c8515fc8a7f1326a80

Here's a screenshot:
playground 4_5_2021 9_44_50 AM

### PR DESCRIPTION
**Pull request by rozele**
There are a few issues with how `textTransform` is currently implemented, but one particular issue is that the shallow application algorithm for the `textTransform` inadvertently applies the text of the last Run in the InlineCollection to all runs in the collection when trying to apply an inherited transform.

Please note, this fix is a temporary patch to eliminate the specific bug described in #7534.  Obviously this change has a major limitation where the original state of raw text is not kept anywhere, but I believe this patch makes things no worse than they already are. There is a more comprehensive fix that I will send a follow-up PR for related to #7535. 

Fixes #7534

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7536)

### CODE REVIEW

**Comment by rozele** [comment]
This PR is irrelevant if we merge #7538

**Review by rectified95 — APPROVED** [review]

**Comment by dannyvv** [comment]
FYI: Took the liberty of merging master to get past the CI issues.

**Comment by dannyvv** [comment]
@asklar Since you reviewed #7538 and I volunteered you to merge that one, Ill `volunteer` you for merging or closing this one based on what you do for #7538 :)

**Comment by asklar** [comment]
thanks @dannyvv :P Eric said we don't need this PR if we merge 7538 (@rozele please let us know if that's no longer true)

**Comment by rozele** [comment]
Closing, since we'll merge #7538

**Pull request closed without merging**
