### PR TITLE
Add missing include folder to fix CI

### PR DESCRIPTION
**Pull request by dannyvv**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7652)

### CODE REVIEW

**Comment by dannyvv** [comment]
The error was in [CI](https://dev.azure.com/ms/react-native-windows/_build/results?buildId=159671&view=logs&j=432cbd55-b638-5192-1ee3-9f73166a6e38&t=c530a7be-5249-52c6-7271-a78e67984c9d)

This test uses folly, but did not include the format library as a dependency.
@acoates-ms I considered adding the dependency in `vnext\PropertySheets\React.Cpp.props` next to `$(FollyDir)` but I saw that you added the dependency manually in other places, so followed that pattern.

**Review by AgneLukoseviciute — APPROVED** [review]

**Comment by asklar** [comment]
> The error was in [CI](https://dev.azure.com/ms/react-native-windows/_build/results?buildId=159671&view=logs&j=432cbd55-b638-5192-1ee3-9f73166a6e38&t=c530a7be-5249-52c6-7271-a78e67984c9d)
> 
> This test uses folly, but did not include the format library as a dependency.
> @acoates-ms I considered adding the dependency in `vnext\PropertySheets\React.Cpp.props` next to `$(FollyDir)` but I saw that you added the dependency manually in other places, so followed that pattern.

I think adding the dependency in the props file is correct. I ran into an issue where in a new app, without building fmt first, Microsoft.reactnative failed to build until I built fmt, it'd be good to make it automatic

**Comment by acoates-ms** [comment]
Hmm yeah, React.cpp.props looks like its probably the right place.
For some reason I only found ReactCommunity.cpp.props when I was looking where to put it, and I didn't want it there since that would add it to external users include paths too.

**Comment by dannyvv** [comment]
Thanks all, I moved it to react.cpp.props and removed all others since those projects already include that props file.

**Review by acoates-ms — APPROVED** [review]

**Pull request merged**
