### PR TITLE
Integration 9/12/22

### PR DESCRIPTION
**Pull request by TatianaKapos**
### Integration 9/12/22
https://github.com/facebook/react-native/compare/9ac437f25...b0aba1b6f

- [feat: added accessibility value aliases](https://github.com/facebook/react-native/commit/e8739e962de3398bc7e42675b1d87ab35993f705)
- [feat: adding aria-label alias for accessibilityLabel](https://github.com/facebook/react-native/commit/720cdbc658aa0b513d106526eb81d749fa957c99)
- [feat: added aria-live as a alias for accessibility-live-region](https://github.com/facebook/react-native/commit/7ea54a408734ccde9ee01a12942bf5722e9cf7c1)
- [Feat/accessibility state alias](https://github.com/facebook/react-native/commit/98d84e571df64b00e1ed3484923a1d8169dcfda1)
- [feat: Add id prop to Text, TouchableWithoutFeedback and View](https://github.com/facebook/react-native/commit/3e97d5fe58c20567f2e653b82f821b856306087b)
- [feat: Add tintColor prop to Image component](https://github.com/facebook/react-native/commit/7a6f0e44b26b7a6eddb25d5e05948a1992a1629e)
- Update hermes to matching version, Vladmir will backfill stub methods in JSI files at a later date

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10768)

### CODE REVIEW

**Review by vmoroz — APPROVED** [review]
LGTM

**Review by AgneLukoseviciute — APPROVED** [review]

**Comment by AgneLukoseviciute** [comment]
LGTM, did you get a chance to check out if the accessibility aliasing works for us out-of-the-box?

**Comment by TatianaKapos** [comment]
@AgneLukoseviciute I minimally went through the accessibility page in RNTester with Narrator and everything seemed to announce as expected :) Not sure if there's more/a better way to test accessibility aliasing

**Comment by AgneLukoseviciute** [comment]
> @AgneLukoseviciute I minimally went through the accessibility page in RNTester with Narrator and everything seemed to announce as expected :) Not sure if there's more/a better way to test accessibility aliasing

Awesome. Yeah if those aliased examples announce same as the props they are standing in for, then we're good (e.g., aria-label announcing same as accessibilityLabel).

**Pull request merged**
