### PR TITLE
[wpf]new feature/add SetOverflow in BaseViewManager

### PR DESCRIPTION
**Pull request by scott108**
[wpf]new feature/add SetOverflow in BaseViewManager

### CODE REVIEW

**Comment by rozele** [comment]
Thanks @scott108, did you check if this approach is compatible with layout animation and transforms? We had to do some tricks to make sure this worked properly on UWP, although we didn't have a simple `ClipToBounds` property on FrameworkElement, we had to specify the clipping `Rect`.

**Comment by rozele** [comment]
Also @matthargett @kevinvangelder @pre10der89 can you review this PR?

**Comment by kevinvangelder** [comment]
I didn't clone this down and test it, but the property is valid and the code looks correct.

**Comment by rozele** [comment]
@scott108 if you sign the CLA, we can merge this PR. Thanks for your contribution!

**Pull request merged**
