### PR TITLE
Ensure onMouseLeave doesn't fire when pointer down

### LINKED ISSUE #9171: onMouseLeave behavior should be consistent regardless of whether the pointer is inside the ReactRootView
### Problem Description

The `onMouseLeave` event is fired on all views when `PointerExited` fires on the `ReactRootView`, even if the pointer is down.

This is inconsistent with how we currently suppress `onMouseEnter` / `onMouseLeave` while inside the bounds of the `ReactRootView`.

These two behaviors need to be consistent so we have a reliable contract for `onMouseEnter` / `onMouseLeave`.

### Steps To Reproduce

1. Open RNTester > Mouse Events example
2. Hold the pointer down over a view and drag the pointer outside the bounds of the ReactRootView.
3. When the mouse exits the ReactRootView - it should not fire `onMouseLeave` until the pointer is released.
4. Notice that `onMouseLeave` didn't fire while the pointer was down inside the `ReactRootView`, but it does once the pointer exits it's bounds.

### Expected Results

The `onMouseEnter` / `onMouseLeave` events should be consistent regardless of whether the pointer is inside the bounds of the `ReactRootView`, so either:
a) Always suppress `onMouseLeave` while pointer is down, or...
b) Do not suppress `onMouseLeave` at all while pointer is down.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

_No response_

### Target Device(s)

_No response_

### Visual Studio Version

_No response_

### Build Configuration

_No response_

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/1106239/142464151-f5e64831-ff1c-4230-bf9a-7fe9f69a5ee4.mp4

### PR DESCRIPTION
**Pull request by rozele**
### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
Generally, `onMouseLeave` does not fire until pointer up if `onMouseEnter` previously fired while pointer down.

However, the `TouchEventHandler` also wires up the `PointerExited` event to clear all hover states. Since we now also clean up hover states in `TouchEventHandler::OnPointerConcluded` (#8526), we can safely make the behavior more consistent with hover state handling inside the bounds of the `ReactRootView` and suppress calling `onMouseLeave` while pointer is down from `OnPointerExited`.

Resolves #9171

### What
Checks if the pointer ID of the `PointerExited` `PointerRoutedEventArgs` is attached to an active gesture, and if so, suppresses the call to `UpdatePointersInViews` which would clear all hover states.

## Testing

https://user-images.githubusercontent.com/1106239/142458747-06481569-2dd7-4fdf-8d81-bcad682f946f.mp4

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9172)

### CODE REVIEW

**Review by asklar — CHANGES_REQUESTED** [review]
Agree with Andrew that it seems odd to tie mouse leave to button down. The web api doesn't mention any exception for button down: https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event

**Comment by rozele** [comment]
@acoates-ms @asklar From your comments then, `onMouseLeave` is already broken today in RNW. This PR just fixes the inconsistency - namely that we fire `onMouseLeave` when the pointer exits the root view while pointer is down, but not while the pointer remains in the window.

I'd ask that we do one of two things:
1. Fix the inconsistency if we want to retain the behavior of suppressing `onMouseEnter` / `onMouseLeave` events while pointer is down by accepting this PR.
2. Agree to change the behavior for `TouchEventHandler` to fire `onMouseEnter` / `onMouseLeave` events even while the pointer is down (I'll follow up with another PR).

**Comment by rozele** [comment]
@asklar @acoates-ms - If this change doesn't make sense, I recommend that we take #9173 instead.

**Comment by rozele** [comment]
#9173 was accepted - closing this PR

**Pull request closed without merging**
