### PR TITLE
Update FlyoutViewManager.cpp

### PR DESCRIPTION
**Pull request by lyahdav**
This is a nit from @appden :)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6241)

### CODE REVIEW

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
@lyahdav you will have to run "yarn change" at the root of the repo to generate a change file.

**Review by asklar — APPROVED** [review]

**Comment by dannyvv** [comment]
@lhyadev: I took the liberty of adding the change file for you, but it looks like you still need to (re)sign the CLA.

**Comment by lyahdav** [comment]
> @lyahdav: I took the liberty of adding the change file for you, but it looks like you still need to (re)sign the CLA.

Awesome, thanks!! I just signed CLA.

**Comment by lyahdav** [comment]
As a meta point: It's very convenient to be able to make small changes as PRs via the edit feature on the GH website. That's how I created this PR, which is why it didn't have the change file. Is there any way we could get to a state where we can make edits directly from the GH website and that the change file could automatically be generated?

**Comment by NickGerleman** [comment]
@lyahdav the idea behind the change file is kind of similar to what the OSS RN repo does with changelog comments. Basically, to collect any semantic information about the change that effects how it is published/documented. Usually, Beachball will ask questions about which semver to bump (patch vs minor vs major vs prerelease), and allow a custom changelog comment different from the commit message. For the main RNW package, some of this is a bit moot since we only allow prerelease version bumps or none, but we eventually want to collect semantic information here as well, like whether the change is breaking.

There's tradeoffs between the models. I agree the current model isn't particularly friendly for new contributors, or anyone who doesn't have the repo locally. OTOH the explicitness of presenting options is kind of useful.

**Comment by dannyvv** [comment]
Thank you @lyahdav, for your contribution and making react-native-windows better!

**Comment by lyahdav** [comment]
> @lyahdav the idea behind the change file is kind of similar to what the OSS RN repo does with changelog comments. Basically, to collect any semantic information about the change that effects how it is published/documented. Usually, Beachball will ask questions about which semver to bump (patch vs minor vs major vs prerelease), and allow a custom changelog comment different from the commit message. For the main RNW package, some of this is a bit moot since we only allow prerelease version bumps or none, but we eventually want to collect semantic information here as well, like whether the change is breaking.
> 
> There's tradeoffs between the models. I agree the current model isn't particularly friendly for new contributors, or anyone who doesn't have the repo locally. OTOH the explicitness of presenting options is kind of useful.

I don’t know much about how the change log is managed in OSS RN repo, but what if you forced any breaking changes/semver info directly in the commit message to obviate the need for a separate change log?

**Comment by NickGerleman** [comment]
@lyahdav I like the idea of having that as an option, but it would likely be a pretty large amount of work. We use [beachball](https://microsoft.github.io/beachball/) for versioning, changelog generation, publishing, etc in RNW along with some other external and internal repos. My understanding is that it's pretty coupled to the idea of change files. We have added features to Beachball before where we needed them, but generally for more scoped issues.

**Comment by lyahdav** [comment]
For the future, I found that you can create the change file directly on your GH repo's fork from the web UI on the same branch as the PR if you want to avoid cloning the repo locally.

**Pull request merged**
