### PR TITLE
Use --sourcemap-use-absolute-path when creating release bundles

### PR DESCRIPTION
**Pull request by jonthysell**
## Description

This PR adds `--sourcemap-use-absolute-path` to the command run by Visual Studio to build a bundle when building in release, to enable more straight-forward direct debugging.

### Type of Change

- Bug fix (non-breaking change which fixes an issue)

### Why

The last string at the bottom of a bundle is the path to the sourcemap for that bundle. Right now, we just put the name of the sourcemap, assuming that it will be kept side-by-side with the bundle. However by default we don't put the sourcemap side-by-side with the bundle output.

This change to use `--sourcemap-use-absolute-path` will put an absolute path to the sourcemap, which makes it possible to direct debug bundles when using Chakra, with Visual Studio.

Note: Hermes direct debug always requires Metro, so this change doesn't improve the Hermes debugging experience.

Also, this shouldn't affect many internal CI systems as they often overwrite this line anyway as sourcemaps get moved to shared build servers.

### What

Added `--sourcemap-use-absolute-path` to the command run by Visual Studio to build a bundle when building in release.

## Screenshots
N/A

## Testing
Verified that I can direct debug the E2Etest app with Visual Studio after running the app with `yarn windows --no-packager --msbuildprops UseBundle=true`
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/11533)

### CODE REVIEW

**Comment by acoates-ms** [comment]
Using a full path for sourcemaps doesn't make sense in release.  It seems pretty unlikely that the developer debugging the JS bundle is going to be at the same machine as the build lab machine that likley produced the final release bundle.

**Comment by jonthysell** [comment]
> Using a full path for sourcemaps doesn't make sense in release. It seems pretty unlikely that the developer debugging the JS bundle is going to be at the same machine as the build lab machine that likely produced the final release bundle.

Right, so then if they want to direct debug an issue locally, then they can't. We purposely don't put the sourcemap into the same output folder as the bundle, because we want the bundle to be included in the app package, but not the sourcemap. So right now it's always a useless path that gets stamped into bundle.

This change would at least enable the scenario of F5 direct debugging bundles locally with VS, but we could also just tell people to modify their BundlerExtraArgs prop.

**Comment by acoates-ms** [comment]
We publish the sourcemap to a symbol server, then restamp the sourcemap URL in the bundle as part of our ship process. -- I'd imagine others would do something similar as part of a real shipping process.

Isn't the default to have a relative sourcemap path, at which point the dev can just copy the sourcemap next to the bundle if they need to debug?  Or they can point their debugger at the sourcemap file manually?

**Comment by chiaramooney** [comment]
PR Triage: Took a glance. Waiting on @jonthysell to answer follow-up q's.

**Comment by jonthysell** [comment]
Closing this, it only improves a very specific case for Chakra users doing local direct debugging of release bundles, and we're trying to prioritize the move to Hermes.

**Pull request closed without merging**
