### PR TITLE
Add cache to SolidColorBrushFrom()

### PR DESCRIPTION
**Pull request by RobMeyer**
#2116

- Loading Universal.SampleApp\index.uwp, number of solid color brushes created reduced from 63 to 19.
- Upon unloading and loading the same bundle a second time, verified that weak references fail to resolve, thus the SolidColorBrushes are getting released when they are no longer referenced beyond the cache.

### CODE REVIEW

**Comment by ahimberg** [comment]
Can brushes be shared between UI threads?  I was thinking about this a bit before and thought we'd want to cache per ui thread, and on shutdown of react root view should we clear it (though its possible to have multiple root views on the same ui thread)

**Comment by kmelmon** [comment]
Good question - all objects in XAML have UI thread affinity and cannot be shared across UI threads.  XAML creates a UI thread for each ApplicationView, so this caching scheme won't work in a multi-view app.  We've run into exactly the same issue in WinUI, and we fixed the issue by storing each cache in as a property on the CoreApplicationView or thread-local-storage (it's a little complicated).  I'll send you a copy of this code.

---
In reply to: [473471022](https://github.com/Microsoft/react-native-windows/pull/2160#issuecomment-473471022) [](ancestors = 473471022)

**Comment by RobMeyer** [comment]
Added thread_local to the cache, though I wasn't sure how to verify it using the sample app. It appears adding a pane doesn't create a window as they're both operating on the same UI thread. Verified that thread_local doesn't impact the single-windowed workflow.

**Pull request merged**
