### PR TITLE
Renamed folder "src"->"patches"

### LINKED ISSUE #7616: Rename "src" in RN Platforms to "patches"
The "src" directory contains a number of JS files that are added to the base copy of RN. It is not a complete source tree itself. Renaming to "patches" would increase clarity of intent, and follow OSS "patch-package" conventions.

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Closes #7616 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7639)

### CODE REVIEW

**Comment by asklar** [comment]
@himanshu007-creator Please run `yarn change` from root of repo to generate a change file.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Please run `yarn change` from root of repo to generate a change file.

I tried but following error pops up
<code>yarn run v1.22.10
$ lage build -- --color
'lage' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</code>

i have installed <code>lage</code> still the error persists.

**Comment by asklar** [comment]
you may have not yet run `yarn` at the root

**Comment by NickGerleman** [comment]
@himanshu007-creator this change is going to require a bit more work. This directory is in a few places, and there are scripts and such that refer to it.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator this change is going to require a bit more work. This directory is in a few places, and there are scripts and such that refer to it.

okay, i will work on that as well. Please help me out here , how to proceed.

**Pull request closed without merging**
