### PR TITLE
Migrate 'AppState' to turbo module

### PR DESCRIPTION
**Pull request by ZihanChen-MSFT**
- Migrate 'AppState' to turbo module

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5395)

### CODE REVIEW

**Comment by NickGerleman** [comment]
Do we still use the bridge while web debugging for migrated modules?

**Comment by ZihanChen-MSFT** [comment]
> Do we still use the bridge while web debugging for migrated modules?

Hi @NickGerleman , when web debugging is enabled it is registered as a native module.

**Comment by kmelmon** [comment]
> > Do we still use the bridge while web debugging for migrated modules?
> 
> Hi @NickGerleman , when web debugging is enabled it is registered as a native module.

Is this done for all the modules we're converting to turbo modules?  I'm curious as we're seeing problems in RNTester with the sample turbo module.  See https://github.com/microsoft/react-native-windows/issues/5348

**Comment by ZihanChen-MSFT** [comment]
> Is this done for all the modules we're converting to turbo modules? I'm curious as we're seeing problems in RNTester with the sample turbo module. See #5348

This is manually controlled for each modules. TurboModuleRegistry.getEnforcing should work when you have registered a module using that name in either native module or turbo module. But we don't recommended people using turbo module when web debugging is on, because it doesn't support web debugging.

**Pull request merged**
