### PR TITLE
Add vnext to rnpm-plugin-windows version

### PR DESCRIPTION
**Pull request by kmelmon**
We're about to publish the latest changes to the CLI to support RNWCPP.  Adding vnext tag for safety.

For some reason the current version checked in says 0.2.9.  However the latest published version up on npm is 0.2.8.  Hence I've changed the version to 0.2.8-vnext.1.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2308)

### CODE REVIEW

**Comment by acoates-ms** [comment]
I'm not sure we want to publish this pacakge as vnext.  That would change the setup steps to require the user to install the vnext version of this.  The way its currently written this package should be able to work for either the C# version of the cpp version. 
Which I guess leads to questions of weather we should be making changes to this package in the master branch rather than the preview branch.

**Comment by kmelmon** [comment]
I was discussing same question with Margaryta.  She suggested starting with vnext and removing it later.  I took a look at her changes - it looks like you need to now supply a template parameter that either says "csharp" or "vnext".  Isn't that essentially a breaking change to the CLI?  If so I think publishing with vnext for now makes sense.

---
In reply to: [484304421](https://github.com/Microsoft/react-native-windows/pull/2308#issuecomment-484304421) [](ancestors = 484304421)

**Comment by marlenecota** [comment]
> it looks like you need to now supply a template parameter that either says "csharp" or "vnext". Isn't that essentially a breaking change to the CLI? If so I think publishing with vnext for now makes sense.
> 
> In reply to: [484304421](https://github.com/Microsoft/react-native-windows/pull/2308#issuecomment-484304421) [](ancestors = 484304421)

What if we make this optional so it defaults to csharp?

**Comment by kmelmon** [comment]
that's a good suggestion.  I suppose the right thing to do is make it default to csharp, publish as 0.2.9, and then integrate this change into master.

---
In reply to: [484307962](https://github.com/Microsoft/react-native-windows/pull/2308#issuecomment-484307962) [](ancestors = 484307962)

**Pull request merged**
