### PR TITLE
Correctly implement font style cascading in nested text

### PR DESCRIPTION
**Pull request by reseul**

### CODE REVIEW

**Comment by rozele** [comment]
Specifically, TextInput, the parent RichTextBlock view manager, RawText, etc. probably also each have this problem, don't they?

---
In reply to: [383181584](https://github.com/Microsoft/react-native-windows/pull/1800#issuecomment-383181584) [](ancestors = 383181584)

**Comment by rozele** [comment]
[https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs#L248](https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs#L248)
[https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputShadowNode.cs#L355](https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputShadowNode.cs#L355)
[https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Views/TextInput/ReactPasswordBoxShadowNode.cs#L255](https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Views/TextInput/ReactPasswordBoxShadowNode.cs#L255)


---
In reply to: [383186187](https://github.com/Microsoft/react-native-windows/pull/1800#issuecomment-383186187) [](ancestors = 383186187,383181584)

**Comment by reseul** [comment]
As far as I understand top levels (TextInput, RichTextBlock) do need platform defaults because they don't come from elsewhere (like from React).
And react doesn't support full CSS style nesting. You can't set a font for the whole page or so.
It seems this cascading is expected to work only in this nested Text thing. So basically I had to fix it in the Span only.

Now, I fixed it for all the props in the shadow node because I saw the outlier prop in the real node (color) worked. But I may be wrong, I may have to "clear value" there as well rather than setting a "null" brush.
To test I'd have to set some color and then reset it.



---
In reply to: [383186983](https://github.com/Microsoft/react-native-windows/pull/1800#issuecomment-383186983) [](ancestors = 383186983,383186187,383181584)

**Comment by reseul** [comment]
Update: I fixed "color" and "textDecorations" (this is just for WPF :) ) cases, I think it's complete now.

---
In reply to: [383188350](https://github.com/Microsoft/react-native-windows/pull/1800#issuecomment-383188350) [](ancestors = 383188350,383186983,383186187,383181584)

**Pull request merged**
