### PR TITLE
Work around regression in app packaging in VS 16.5-16.6

### LINKED ISSUE #4836: Generating a new certificate in VS 16.5+ breaks app signing
@qmatteoq ran into this, filing on his behalf.

> Today I was working on a React Native for Windows project and I’ve noticed something wrong with Visual Studio 16.5.4. Maybe it’s something you’re already aware and it’s already fixed in internal versions, but better to double check 😊
I had to create a new self-signing certificate to sign the UWP app, so I’ve proceeded using the UI wizard which is available in the Packaging section of the manifest. Everything completed fine but, when I tried to run the React Native scripts which signs and deploys the package through PowerShell, I got the following error:
 
`Certificates specifies an incompatible key usage`
 
> From the documentation, it seems the problem is related to the certificate missing the extended key usage flags required for code signing. At this point I tried to generate a new certificate manually using the guidance here: https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-create-a-package-signing-certificate
The certificate generated this way, instead, works fine. The package is signed and deployed just fine.
 
VS folks said this is a known issue: https://developercommunity.visualstudio.com/content/problem/1012921/uwp-packaging-generates-incompatible-certificate.html

This will be fixed in VS 16.7 but in the meantime 16.5 and 16.6 will be broken.
The certificates created by VS 16.5 and up in the VS UI are going to be broken in the sense that `Add-AppxPackage`  will error out:
> There are two scenarios that introduce the blocked EKU’s. They are:
> 1)	The user generates a signing certificate through the Packaging Wizard or Manifest Designer. The cert we generate contains one of the new EKUs designating it as one generated within the UWP UX.
> 2)	The user packages the app for store and checks the box to generate test artifacts to run WACK (on by default) without specifying a certificate manually. In this case we’ll generate a disposable cert containing both new EKUs.
> Certs generated through powershell with the proper code signing EKU, or certs generated in versions of VS prior to 16.5 will continue to work unimpeded.

### PR DESCRIPTION
**Pull request by asklar**
Fixes #4836 
Works around a regression in app packaging introduced in VS 16.5 which will be fixed in 16.7. For the time being, shipping a private copy of Add-AppDevPackage that has the fix for the issue.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4958)

### CODE REVIEW

**Comment by kmelmon** [comment]
Since version 61 is the current default, anyone using the CLI to create a new will have a broken build out of the box.  We should consider backporting this to 61.

**Comment by NickGerleman** [comment]
Backported to 0.62 but not yet 0.61.

**Comment by NickGerleman** [comment]
Moving from "Request Backport" to "Backport Approved" after earlier discussion.

**Comment by NickGerleman** [comment]
@asklar this doesn't cleanly apply to 0.61 and I'm not familiar enough with the area to feel confident in merging myself. Would you be able to backport this to 0.61?

**Comment by asklar** [comment]
> @asklar this doesn't cleanly apply to 0.61 and I'm not familiar enough with the area to feel confident in merging myself. Would you be able to backport this to 0.61?

@NickGerleman sure. Did 0.61 support VS 2017 or only VS 2019? The code I have in 63 doesn't deal  with 2017 FWIW.

**Comment by NickGerleman** [comment]
@asklar I think we recommended installing V141 tools on top of VS 2019.

**Comment by NickGerleman** [comment]
It looks like our CI machines were running with VS 2017 from what I can tell.

**Comment by NickGerleman** [comment]
So, CI won't see the issue, but I'm not sure what the user story is.

**Comment by NickGerleman** [comment]
Removing "Backport to 0.61" since we're about to rename it to "Backported to 0.61" as part of backporting label migration.

**Comment by NickGerleman** [comment]
Intent is still to backport to 0.61 to my understanding, so leaving "backport approved" to indicate outstanding work.

**Comment by Khalef1** [comment]
Backported to 0.61 as #5100

**Pull request merged**
