### PR TITLE
[0.62] TextWin32 focusable property backport

### PR DESCRIPTION
**Pull request by PPatBoyd**
Enable a focusable property on TextWin32 to differentiate focus from selection.  The selectable property enables character-based selection, where focusable only enables whole-label focus and copy hotkey/menu.  This difference is important because selection comes with a high perf cost for any non-trivial count of labels.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7059)

### CODE REVIEW

**Comment by NickGerleman** [comment]
Master branch targets 0.65. Does this change also need to go into 0.63, 0.64?

**Comment by PPatBoyd** [comment]
> Master branch targets 0.65. Does this change also need to go into 0.63, 0.64?

Yep, hooray backporting to the .62-.64 swath.

**Comment by NickGerleman** [comment]
> > Master branch targets 0.65. Does this change also need to go into 0.63, 0.64?
> 
> Yep, hooray backporting to the .62-.64 swath.

Yeah... current state isn't great. There's work to run bots to automate it, but I think the long term is getting macos able to keep up.

**Comment by PPatBoyd** [comment]
> > > Master branch targets 0.65. Does this change also need to go into 0.63, 0.64?
> > 
> > 
> > Yep, hooray backporting to the .62-.64 swath.
> 
> Yeah... current state isn't great. There's work to run bots to automate it, but I think the long term is getting macos able to keep up.

Hopefully the diffs for .63 and .64 won't be much different than one of these two... .62 and .65 were fairly different

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
You'll need to run "yarn api" for this in 0.62/0.63

**Comment by PPatBoyd** [comment]
The last check [ PR (Sample Apps PR X64Release) ] isn't showing completed, but completed successfully

**Pull request merged**
