### PR TITLE
E2E Test docs wrong url in rnw-dependencies

### PR DESCRIPTION
**Pull request by linkstrifer**
It was trying to load a markdown file but now is a HTML file

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4801)

### CODE REVIEW

**Comment by asklar** [comment]
I'm surprised `unbroken` didn't catch it. @jonthysell are we not running it in CI?

**Comment by asklar** [comment]
Hey @linkstrifer thanks for submitting this. This html page is actually produced by docusaurus during our CI build based on the content in the microsoft/react-native-windows-samples repo. 

The link you mention was actually removed yesterday, see https://github.com/microsoft/react-native-windows-samples/commit/6fdf4f29e2b394db7e38aed897f02924149b8e3e
This should update the website soon (not sure how often this runs but maybe @jonthysell  or @harinikmsft  know).

The e2e-testing content can be found in the repo here: [E2ETesting](https://github.com/microsoft/react-native-windows/blob/master/docs/e2e-testing.md)

**Comment by linkstrifer** [comment]
Thanks for the response :D 

I though it was a human mistake xD

**Comment by asklar** [comment]
@linkstrifer  no problem :) I'm thinking we should bring the contributor documents to our [website](https://microsoft.github.io/react-native-windows/)
PR: https://github.com/microsoft/react-native-windows-samples/pull/91
Stay tuned!

**Pull request closed without merging**
