### PR TITLE
fix build error

### PR DESCRIPTION
**Pull request by enm10k**
I'm still getting the same build error reported on https://github.com/microsoft/react-native-windows/issues/2531.
As @aiya000 described on the issue, after changing the file encoding, build completed successfully.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/3422)

### CODE REVIEW

**Comment by kmelmon** [comment]
Thanks for submitting a fix!  You'll need to include a change file, this why the CI loop is failing.
Please run yarn change from the root of your enlistment, follow the steps, then push this change up.

**Comment by enm10k** [comment]
@kmelmon 
I appreciate your explanation.
I added a change file.

**Comment by enm10k** [comment]
@kmelmon 
Unfortunately, some checks failed.
It looks similar to this issue https://github.com/microsoft/react-native-windows/issues/3444.
I would appreciate if you could advise me on how to handle the situation.

**Comment by enm10k** [comment]
@licanhua 
All checks have passed successfully now.
Could we get this merged?

**Pull request merged**
