### PR TITLE
Allow ABIViewManagers to use `overflow: hidden`

### PR DESCRIPTION
**Pull request by rozele**
### Type of Change
_Erase all that don't apply._
- Bug fix (non-breaking change which fixes an issue)

### Why
Currently, `overflow: hidden` is only implemented on `<View>`, but any node should be allowed to use this style.

### What
This moves the logic to handle clipping to ViewManagerBase. This change also removes the Clip related properties from ViewPanel, forcing a breaking change (because ViewPanel is exposed through the ABI).

## Testing

RNTester `overflow: 'hidden'`:
image

Test app:

https://user-images.githubusercontent.com/1106239/195151620-ad0ff0df-449f-4950-9f08-18ec6a323450.mp4

Please note, prior to this change, there was also a bug where, after being enabled, disabling the clip did not work correctly because the Clip property was only applied in ArrangeOverride.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10717)

### CODE REVIEW

**Comment by rozele** [comment]
One thing to note here...

9ba1c1d1d8e255142256575582cd8dcda25a5573 eliminated the ClipGeometry in the case that an outer border was used on the ViewPanel (because Border elements clip by default). We can re-introduce this, but it may introduce too much complexity. The worst case I guess is now when someone sets `border*` props and `overflow: hidden`, we will have both a ClipGeometry and `Border` element.

We just need to decide whether allowing arbitrary views to use `overflow: 'hidden'` is worth this extra cost.

**Comment by rozele** [comment]
Also, it's not clear from the docs whether ClipGeometry does appropriate pixel rounding. Previously, ViewPanel used the ActualWidth and ActualHeight properties to set the ClipGeometry. This uses Yoga values rounded to whole numbers.

**Comment by rozele** [comment]
This change will also make it simpler to experiment with various XAML control types for `View` (e.g., Canvas to avoid Measure/ArrangeOverride and Grid to avoid the need for an inner or outer border).

**Comment by rozele** [comment]
@asklar - since you previously raised concerns about breaking changes, pinging you here. I think this particular breaking change is warranted for a few reasons:

1. There is an unreconcilable bug if ArrangeOverride is not called and the clip property updates. See test plan, which calls out that ArrangeOverride is not a reliable place to update the Clip for `overflow="hidden"`.
2. If we're not updating the Clip in the ViewPanel::ArrangeOverride method, then leaving the `ClipChildren` property in place on `ViewPanel.idl` is possible, but it would be effectively dead code. I'd rather be explicit that app code needs to change if it was previously depending on this property than silently no-op when they try to set ClipChildren from outside React Native.
3. This functionality should never have been exposed on ViewPanel in the first place, it's a leak of an implementation detail.

**Comment by chiaramooney** [comment]
ping @jonthysell

**Review by jonthysell — APPROVED** [review]

**Comment by jonthysell** [comment]
@rozele Sorry for taking so long - I see more changes last month, is this done?

**Comment by rozele** [comment]
@jonthysell I think it was just a rebase last month.

**Pull request merged**
