### PR TITLE
Additional compiler & linker flags for binary size 

### PR DESCRIPTION
**Pull request by AgneLukoseviciute**
## Description
As part of an EIM initiative, did a compiler options pass for recommended flags to reduce binary size. We are mostly good; this adds the three we were missing. 

Minor savings since we had the majority set up already, but did slightly decrease binary size:
Microsoft.ReactNative.dll: 2,869,248 bytes -> 2,865,152 bytes (-4,096) 
                                 .pdb: 113,397,760 bytes -> 113,364,992 bytes (-32,768)

Comparing through SizeBench, biggest impact was on the .rdata section. 

Internal link for recommended flags [here](https://www.osgwiki.com/wiki/Compiler_and_linker_flags_recommended_for_binary_size#MSBuild_equivalents). 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10244)

### CODE REVIEW

**Review by asklar — APPROVED** [review]

**Comment by asklar** [comment]
@dmachaj fyi

**Comment by dmachaj** [comment]
>     <LinkIncremental>false</LinkIncremental>

It might make sense to separate some of these by Release vs. Debug.  Incremental linking is bad for a release build but probably good for a debug inner loop build.

---
Refers to: vnext/PropertySheets/Release.props:10 in 7c17053. [](commit_id = 7c170530dd79897975a6e73bf45568688b4d9c27, deletion_comment = False)

**Comment by dmachaj** [comment]
>     <LinkIncremental>false</LinkIncremental>

Although since this file is named `release.props` perhaps you already have them separated at the file level?

---
In reply to: [1176775420](https://github.com/microsoft/react-native-windows/pull/10244#issuecomment-1176775420) [](http://example.com/codeflow?ancestors=1176775420)

---
Refers to: vnext/PropertySheets/Release.props:10 in 7c17053. [](commit_id = 7c170530dd79897975a6e73bf45568688b4d9c27, deletion_comment = False)

**Comment by AgneLukoseviciute** [comment]
> > ```
> > <LinkIncremental>false</LinkIncremental>
> > ```
> 
> Although since this file is named `release.props` perhaps you already have them separated at the file level?
> 
> In reply to: [1176775420](https://github.com/microsoft/react-native-windows/pull/10244#issuecomment-1176775420)
> 
> Refers to: vnext/PropertySheets/Release.props:10 in [7c17053](https://github.com/microsoft/react-native-windows/commit/7c170530dd79897975a6e73bf45568688b4d9c27). [](commit_id = [7c17053](https://github.com/microsoft/react-native-windows/commit/7c170530dd79897975a6e73bf45568688b4d9c27), deletion_comment = False)

yep, exactly!

**Review by dmachaj — APPROVED** [review]
:shipit:

**Pull request merged**
