### PR TITLE
feat(Portable): Extract ChakraBridge into shared project, add Net46 variant

### PR DESCRIPTION
**Pull request by matthargett**

### CODE REVIEW

**Comment by rozele** [comment]
Would love to have @mpodwysocki take a look at this when he gets time.

**Comment by matthargett** [comment]
Note: I turned of Pre-Compiled Headers, as they stopped working once I starting using the Shared Project. I timed it before and after, and there was no notable difference in wall clock time for the build on my Surface Pro 3 (i5).

**Comment by kevinvangelder** [comment]
I believe a newer PR that's already been merged replaced this one, right?

**Comment by matthargett** [comment]
Some of the other merged PRs were extracted from this one, but only this one has the ChakraBridge C++ changes. I'd like to leave this open, since we will want to merge the C++ changes later.

**Comment by rozele** [comment]
Closing this PR. Still easy to reference as closed.

**Pull request closed without merging**
