### PR TITLE
Fix native modules not being re-initialized on reload

### PR DESCRIPTION
**Pull request by tido64**
When calling `ReactNativeHost::ReloadInstance()`, `ReactPackageProvider`s are not reiterated and thus not calling `AddAttributedModules()`. As a consequence, the native modules that were loaded the first time the app was loaded, no longer "exist" after a reload.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6159)

### CODE REVIEW

**Comment by tido64** [comment]
@acoates-ms: I hit this issue while trying to figure out why my `DevSettings` override is not loaded after a reload (https://github.com/microsoft/react-native-test-app/pull/212). Not sure if this is the right fix so I would appreciate it if you could take a look or ping someone who can.

**Comment by acoates-ms** [comment]
@vmoroz - Seems good to me but want you to check.  This also seems bad.  I'm surprised other people haven't hit it.  It probably needs backporting?

**Comment by NickGerleman** [comment]
@acoates-ms instance reload was IIRC very unreliable in MSRN until 0.63. We didn't really hear feedback on it, so I'm kind of curious what development workflow looks like for the average RNW user.

**Comment by vmoroz** [comment]
> @vmoroz - Seems good to me but want you to check. This also seems bad. I'm surprised other people haven't hit it. It probably needs backporting?

@acoates-ms - yes, the change is good. We did the same in private repo for the CodePush implementation. @tido64, thank you for fixing it!

**Review by vmoroz — APPROVED** [review]
:shipit:

**Comment by vmoroz** [comment]
@tido64, please run `yarn change` to create the change file. It is the only check that is failing.

**Comment by tido64** [comment]
Thanks for the super quick review ❤️

**Pull request merged**
