### PR TITLE
Fix an intermittent InvalidOperationException in AddRootNode() 

### PR DESCRIPTION
**Pull request by matthargett**
Fix an intermittent InvalidOperationException when AddRootNode() is being called via AttachMeasuredRootViewToInstance() from the UI thread and UpdateViewHierarchy() is being called from the Native Modules thread. Thanks to my colleague Nick for tracking down this tricky issue and devising a fix.

### CODE REVIEW

**Comment by rozele** [comment]
I thought we had fixed this with a lock at some point. Will need to review the history to see why that changed.

**Comment by rozele** [comment]
cc @reseul - I thought the ShadowNodeRegistry was moved to single threaded access - why was the locking mechanism removed in 9e88628f9c8e7e66d26ba70f33eda9ff50dd3d47?

**Comment by rozele** [comment]
Ah - I believe we changed something so that `AttachMeasuredRootViewToInstance` is actually called from the layout thread... let me see...

**Comment by rozele** [comment]
Disregard @reseul - all interactions with the ShadowNodeRegistry are performed on the layout thread, even the call to `AddRootNode`, which dispatches here:
https://github.com/Microsoft/react-native-windows/blob/f0d365e2a2907b414c982d5c368fb1d3d37121a4/ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs#L143-L146

@matthargett - I think this bug find might be a bit stale, please confirm and close if this is no longer an issue in the latest code.

**Comment by reseul** [comment]
@rozele @matthargett Yeah, that data structure is accessed by layout manager only now (well, maybe except construction, garbage collection, etc.).
As far as I know the similar threading issue has been fixed in Android version too.

Now, since nothing is lost, I have a similar issue in the multi window code that I have to fix. The structures that deal with mapping UI operations to the right queue are supposed to be called by LM thread only, yet we have the "animation sync update" and other exceptions :(.
I'll fix it soon.

**Comment by matthargett** [comment]
nice. not having to use a synchronized collection will be more performance anyway. I'm glad this was fixed at the design level. /cc @CaptainNic

**Pull request closed without merging**
